### ISSUE TITLE
Add Unit tests

### ISSUE THREAD

**Issue by trevorwang** [trevorwang/retrofit.dart#10]

**Comment by devkabiir** [comment]
Checkout: https://pub.dev/packages/source_gen_test
This package makes testing generators very easy.
Example
```dart
@ShouldGenerate(
r'''
class _RestClient implements RestClient {
/// generated methods and constructor
}
'''
)
@RestApi()
class RestClient{
/// Constructors and methods
}
```

**Comment by trevorwang** [comment]
@devkabiir  It will be really appreciated if you can help add some tests.

**Comment by devkabiir** [comment]
@trevorwang Sure, when I get time, I'll send a PR
