### ISSUE TITLE
Using mocked data with refrofit fails

### ISSUE THREAD

**Issue by vanlooverenkoen** [trevorwang/retrofit.dart#101]
I use a custom client adapter to mock my requests like this:

```
class MyAdapter extends HttpClientAdapter {
  DefaultHttpClientAdapter _adapter = DefaultHttpClientAdapter();

  @override
  Future<ResponseBody> fetch(RequestOptions options,
      Stream<List<int>> requestStream, Future cancelFuture) async {
    Uri uri = options.uri;
    // hook requests to  google.com
    if (uri.host == "google.com") {
      return ResponseBody.fromString("Too young too simple!", 200);
    }
    return _adapter.fetch(options, requestStream, cancelFuture);
  }

  @override
  void close({bool force = false}) {
    _adapter.close(force: force);
  }
}
```

I always get an error like this:

`type 'String' is not a subtype of type 'Map<String, dynamic>'`

This is my service:

```
  @override
  @GET('/v1/public/switch')
  Future<Switch> getSwitch();
```

This is my generated request:

```
  @override
  getSwitch() async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final Response<Map<String, dynamic>> _result = await _dio.request(
        '/v1/public/switch',
        queryParameters: queryParameters,
        options: RequestOptions(
            method: 'GET',
            headers: <String, dynamic>{},
            extra: _extra,
            baseUrl: baseUrl),
        data: _data);
    final value = Switch.fromJson(_result.data);
    return Future.value(value);
  }
```

https://github.com/flutterchina/dio/issues/194

**Comment by trevorwang** [comment]
`jsonEncode` is recommended to build your response
https://github.com/trevorwang/retrofit.dart/blob/894199fec9191998acd374c27b4254367117cd98/generator/test/src/task_data.dart#L11


And here's a way to use `mock_web_server` to test your code
https://github.com/trevorwang/retrofit.dart/blob/894199fec9191998acd374c27b4254367117cd98/generator/test/demo_test.dart#L24


I close this issue.  Please reopen it if any question

**Comment by vanlooverenkoen** [comment]
Yes indeed I used and even if you use jsonEncode you **MUST** add a `content-type: application/json` header

**Comment by trevorwang** [comment]
Yes. You are right.

**Comment by vanlooverenkoen** [comment]
That took me only 1 full day to figure that out 😂

**Comment by trevorwang** [comment]
It seemed that it also took me several hours. O(∩_∩)O

**Comment by vanlooverenkoen** [comment]
Thanks anyway. It is the way dio handles the responses
