### ISSUE TITLE
@Part() doesn't generate MultipartFile

### ISSUE THREAD

**Issue by RakaAlrian** [trevorwang/retrofit.dart#105]
**Describe the bug**
I just update flutter to 43.0.1, retrofit to ^1.1.0+1 and retrofit_generator to ^1.1.0+1. It give me error when I run build_runner, because I have to use @Part() instead of @Field() to send File data type. But when I look to the generated file, the File is not generated to MultipartFile like when I used @Field() before updating version. The file is definitely not sent to the server.

**To Reproduce**
1. update flutter to 43.0.1, retrofit to ^1.1.0+1 and retrofit_generator to ^1.1.0+1
2. use @Part() instead of @Field() to send File data type

**Screenshots**
This is my method

> @POST(defaultPath)
  Future<DoNotModel> postDoNotWithImage(@Field() String title,
      @Field() String reason,
      @Field() String image,
      @Part() File file,);

This is the generated method

> @override
  postDoNotWithImage(title, reason, image, file) async {
    ArgumentError.checkNotNull(title, 'title');
    ArgumentError.checkNotNull(reason, 'reason');
    ArgumentError.checkNotNull(image, 'image');
    ArgumentError.checkNotNull(file, 'file');
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _data = {'title': title, 'reason': reason, 'image': image};
    final Response<Map<String, dynamic>> _result = await _dio.request('/donot',
        queryParameters: queryParameters,
        options: RequestOptions(
            method: 'POST',
            headers: <String, dynamic>{},
            extra: _extra,
            baseUrl: baseUrl),
        data: _data);
    final value = DoNotModel.fromJson(_result.data);
    return Future.value(value);
  }

**Smartphone (please complete the following information):**
 - Device: emulator
 - OS: Android API 21

**Comment by trevorwang** [comment]
Please DO not use both  @field and @Part at the same time.

@Field is not supported when content-type is multipart.

Replace all @Field with @@part

**Comment by RakaAlrian** [comment]
Ohh, my bad. Thanks :D
