### ISSUE TITLE
retrofit and json_serializable

### ISSUE THREAD

**Issue by pacey** [trevorwang/retrofit.dart#11]
Hey! Sorry if raising an issue isn't the best way to talk about this, but I wasn't sure where else I could ask.

I see in your example you are using json_serializable to create a `Result` class, but that isn't used anywhere yet. Do you know if it's possible to use the `Result` class as the generic type for the `Response` class? Or does retrofit only work in returning strings? I'm trying to do that in my project with my own api result class and I get the error:

```
I/flutter ( 9176): DioError [DioErrorType.DEFAULT]: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'LaunchPage'#0      Dio._assureResponse (package:dio/src/dio.dart:1006:9)
```

**Comment by trevorwang** [comment]
Hi @pacey 
Currently retrofit.dart just simply wrappers Dio library.  Only limit types are supported by dio.
Please refer to  https://github.com/flutterchina/dio/issues/77

A powerful Generic support is in consideration.

**Comment by pacey** [comment]
Thanks for linking to that issue on the Dio library, makes sense.

Thanks for your work on retrofit too, really useful!
