### ISSUE TITLE
Can't upload file with @Part anottation

### ISSUE THREAD

**Issue by romawizard** [trevorwang/retrofit.dart#110]
After Change @Field to @Part code gen dosn't generate FormData

**Comment by trevorwang** [comment]
Please provide your sample code  and dart env.

**Comment by awanishraj** [comment]
Facing the same issue, the generated code doesn't contain FormData for the file

Input:
 @POST("user/files/upload")
  @MultiPart()
  Future<UploadFileAPIResponse> uploadFile(
      @Header("Authorization") String token, @Part("file") File file);

Code-gen Output:
 @override
  uploadFile(token, file) async {
    ArgumentError.checkNotNull(token, 'token');
    ArgumentError.checkNotNull(file, 'file');
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final Response<Map<String, dynamic>> _result = await _dio.request(
        'user/files/upload',
        queryParameters: queryParameters,
        options: RequestOptions(
            method: 'POST',
            headers: <String, dynamic>{'Authorization': token},
            extra: _extra,
            baseUrl: baseUrl),
        data: _data);
    final value = UploadFileAPIResponse.fromJson(_result.data);
    return Future.value(value);
  }
