### ISSUE TITLE
Support custom options for each request

### ISSUE THREAD

**Issue by yjouyang** [trevorwang/retrofit.dart#115]
I'd like to use this library [dio_http_cache](https://pub.dev/packages/dio_http_cache)

**Comment by trevorwang** [comment]
You can use `@Extra` as a workaround.

https://github.com/trevorwang/retrofit.dart/blob/c8ba1df9a7ff66457c1812ddaa695869263bf063/annotation/lib/dio.dart#L6 
```
Options buildConfigurableCacheOptions(
    {Options options,
    Duration maxAge,
    Duration maxStale,
    String primaryKey,
    String subKey,
    bool forceRefresh}) {
  if (null == options) {
    options = Options();
  } else if (options.responseType == ResponseType.stream) {
    throw Exception("ResponseType.stream is not supported");
  }
  options.extra.addAll({DIO_CACHE_KEY_TRY_CACHE: true});
  if (null != maxAge) {
    options.extra.addAll({DIO_CACHE_KEY_MAX_AGE: maxAge});
  }
  if (null != maxStale) {
    options.extra.addAll({DIO_CACHE_KEY_MAX_STALE: maxStale});
  }
  if (null != primaryKey) {
    options.extra.addAll({DIO_CACHE_KEY_PRIMARY_KEY: primaryKey});
  }
  if (null != subKey) {
    options.extra.addAll({DIO_CACHE_KEY_SUB_KEY: subKey});
  }
  if (null != forceRefresh) {
    options.extra.addAll({DIO_CACHE_KEY_FORCE_REFRESH: forceRefresh});
  }
  return options;
}
```

**Comment by trevorwang** [comment]
Considering to support it in future release.

**Comment by yjouyang** [comment]
> You can use `@Extra` as a workaround.
> 
> https://github.com/trevorwang/retrofit.dart/blob/c8ba1df9a7ff66457c1812ddaa695869263bf063/annotation/lib/dio.dart#L6
> 
> ```dart
> Options buildConfigurableCacheOptions(
>     {Options options,
>     Duration maxAge,
>     Duration maxStale,
>     String primaryKey,
>     String subKey,
>     bool forceRefresh}) {
>   if (null == options) {
>     options = Options();
>   } else if (options.responseType == ResponseType.stream) {
>     throw Exception("ResponseType.stream is not supported");
>   }
>   options.extra.addAll({DIO_CACHE_KEY_TRY_CACHE: true});
>   if (null != maxAge) {
>     options.extra.addAll({DIO_CACHE_KEY_MAX_AGE: maxAge});
>   }
>   if (null != maxStale) {
>     options.extra.addAll({DIO_CACHE_KEY_MAX_STALE: maxStale});
>   }
>   if (null != primaryKey) {
>     options.extra.addAll({DIO_CACHE_KEY_PRIMARY_KEY: primaryKey});
>   }
>   if (null != subKey) {
>     options.extra.addAll({DIO_CACHE_KEY_SUB_KEY: subKey});
>   }
>   if (null != forceRefresh) {
>     options.extra.addAll({DIO_CACHE_KEY_FORCE_REFRESH: forceRefresh});
>   }
>   return options;
> }
> ```

That should be work. Thanks
