### ISSUE TITLE
Mutate headers globally

### ISSUE THREAD

**Issue by woprandi** [trevorwang/retrofit.dart#117]
Add the ability to mutate global headers (`dio.options.headers`). I'd like to be able to set headers dynamically for each request (add a auth token from `shared_preferences` for example).

**Comment by trevorwang** [comment]
Interceptors are a better solution for this
https://github.com/flutterchina/dio#interceptors

**Comment by woprandi** [comment]
Thanks @trevorwang  I didn't find it myself
