### ISSUE TITLE
Support baseUrl definition from _dio.options.baseUrl

### ISSUE THREAD

**Issue by stewemetal** [trevorwang/retrofit.dart#124]
As of now, the `RestClient`/`RestApi`/`RestService` class (it really doesn't matter how we call it) that represents network API calls doesn't take into account the passed `Dio` instance's `options.baseUrl` value.

The current solution:

```dart
@RestApi(baseUrl: "http://example.com/api/v2") // We have to use the full baseUrl here
abstract class TodoApi {
  factory TodoApi(Dio dio, {String baseUrl}) = _TodoApi;

  // Methods representing REST calls
}

final dio = Dio();
final TodoApi(dio);
```

What I'd like to do is the following:

```dart
@RestApi(baseUrl: "/api/v2") // This would only be a postfix to the baseUrl defined in the provided Dio instance
abstract class TodoApi {
  factory TodoApi(Dio dio, {String baseUrl}) = _TodoApi;

  // Methods representing REST calls
}

final dio = Dio();
dio.options.baseUrl = "https://example.com"; // This can be the real baseUrl
final TodoApi(dio);
```

Currently the code generator would generate something like this for the abstract methods of `TodoApi`:

```dart
@override
getTodo(id) async {
  ArgumentError.checkNotNull(id, 'id');
  const _extra = <String, dynamic>{};
  final queryParameters = <String, dynamic>{};
  final _data = <String, dynamic>{};
  final Response<Map<String, dynamic>> _result = await _dio.request(
      '/todos/$id',
      queryParameters: queryParameters,
      options: RequestOptions(
          method: 'GET',
          headers: <String, dynamic>{},
          extra: _extra,
          baseUrl: baseUrl), // The generated code only respects the baseUrl provided in the RestApi annotation
      data: _data);
  final value = Todo.fromJson(_result.data);
  return Future.value(value);
}
```

With a fairly small modification to the code generator, respecting the baseUrl of the provided `Dio` instance could be implemented in a safe and backwards compatible way:

```dart
@override
getTodo(id) async {
  ArgumentError.checkNotNull(id, 'id');
  const _extra = <String, dynamic>{};
  final queryParameters = <String, dynamic>{};
  final _data = <String, dynamic>{};
  final Response<Map<String, dynamic>> _result = await _dio.request(
      '/todos/$id',
      queryParameters: queryParameters,
      options: RequestOptions(
          method: 'GET',
          headers: <String, dynamic>{},
          extra: _extra,
          baseUrl: "${_dio.options.baseUrl ?? ""}$baseUrl"), // The provided Dio instance's baseUrl will be used, if set. This would ensure backwards compatibility, because the not set baseUrl would result in appending RestClien's baseUrl to an empty String.
      data: _data);
  final value = Todo.fromJson(_result.data);
  return Future.value(value);
}
```

Please consider implementing this small change to make `retrofit.dart` even more flexible and also, work more like `Retrofit` on Android.

**Comment by trevorwang** [comment]
It should work without change anything. Have a try.

**Comment by stewemetal** [comment]
I'm using the lastest version (1.3.0) and it still doesn't respect the `baseUrl` defined in Dio's options.

For reference, I'm trying to do this exactly:

```dart
@RestApi(baseUrl: "/api/v2")
abstract class PokeApi {
  factory PokeApi(Dio dio, {String baseUrl}) = _PokeApi;
    
  @GET("/pokemon/{id}")
  Future<NetworkPokemon> getPokemon(@Path() int id);
}
```

And to try things out quickly, I wrote a test that drives the class above the way I described it in the opening comment:

```dart
void main() {
  group("PokeApi test:", () {
    test("Get Pokemon call", () async {
      final dio = Dio();
      dio.options.baseUrl = "https://pokeapi.co";

      final api = PokeApi(dio);

      final pokemon = await api.getPokemon(1);
      print(pokemon);
    });
  });
}
```

Running this test yields the following error:

<details><summary>Test result</summary>
<p>
00:00 +0: PokeApi tests: Get Pokemon call

00:00 +0 -1: PokeApi tests: Get Pokemon call [E]

  DioError [DioErrorType.DEFAULT]: RangeError (index): Invalid value: Only valid value is 0: 1
  #0      List.[] (dart:core-patch/growable_array.dart:149:60)
  #1      RequestOptions.uri (package:dio/src/options.dart:301:29)
  #2      DefaultHttpClientAdapter.fetch (package:dio/src/adapters/io_adapter.dart:35:72)
  #3      DioMixin._dispatchRequest (package:dio/src/dio.dart:919:46)
  <asynchronous suspension>
  #4      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:849:37)
  #5      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1118:22)
  #6      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:846:22)
  #7      new Future.<anonymous closure> (dart:async/future.dart:176:37)
  #8      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
  #9      StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
  #10     _rootRun (dart:async/zone.dart:1122:38)
  #11     _CustomZone.run (dart:async/zone.dart:1023:19)
  #12     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
  #13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
  #14     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
  #15     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
  #16     _rootRun (dart:async/zone.dart:1126:13)
  #17     _CustomZone.run (dart:async/zone.dart:1023:19)
  #18     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
  #19     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
  #20     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
  #21     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
  #22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

  package:dio/src/dio.dart 963:7                                DioMixin._dispatchRequest
  ===== asynchronous gap ===========================
  dart:async/future_impl.dart 24:43                             _Completer.completeError
  dart:async/future.dart 462:45                                 Future.any.<fn>
  package:stack_trace/src/stack_zone_specification.dart 141:26  StackZoneSpecification._registerBinaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 141:14  StackZoneSpecification._registerBinaryCallback.<fn>
  dart:async/zone.dart 1146:38                                  _rootRunBinary
  dart:async/zone.dart 1039:19                                  _CustomZone.runBinary
  dart:async/future_impl.dart 153:20                            _FutureListener.handleError
  dart:async/future_impl.dart 692:47                            Future._propagateToListeners.handleError
  dart:async/future_impl.dart 713:24                            Future._propagateToListeners
  dart:async/future_impl.dart 532:5                             Future._completeError
  dart:async-patch/async_patch.dart 38:15                       _AsyncAwaitCompleter.completeError
  package:dio/src/dio.dart                                      DioMixin._dispatchRequest
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1064:19                                  _CustomZone.registerBinaryCallback
  dart:async/future_impl.dart 804:10                            _registerErrorHandler
  dart:async/future_impl.dart 280:19                            Future.then
  dart:async/future.dart 465:14                                 Future.any
  package:dio/src/dio.dart 976:19                               DioMixin.listenCancelForAsyncTask
  package:dio/src/dio.dart 843:18                               DioMixin._request._interceptorWrapper.<fn>
  package:stack_trace/src/stack_zone_specification.dart 129:26  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 129:14  StackZoneSpecification._registerUnaryCallback.<fn>
  dart:async/zone.dart 1134:38                                  _rootRunUnary
  dart:async/zone.dart 1031:19                                  _CustomZone.runUnary
  dart:async/future_impl.dart 139:18                            _FutureListener.handleValue
  dart:async/future_impl.dart 680:45                            Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 709:32                            Future._propagateToListeners
  dart:async/future_impl.dart 524:5                             Future._completeWithValue
  dart:async/future_impl.dart 554:7                             Future._asyncComplete.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 43:21                      _microtaskLoop
  dart:async/schedule_microtask.dart 52:5                       _startMicrotaskLoop
  dart:isolate-patch/timer_impl.dart 393:30                     _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 418:5                      _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 174:12                  _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055:19                                  _CustomZone.registerUnaryCallback
  dart:async/future_impl.dart 275:23                            Future.then
  package:dio/src/dio.dart 890:21                               DioMixin._request
  package:dio/src/dio.dart 764:12                               DioMixin.request
  package:pokedex_arch/data/network/poke_api.g.dart 44:63       _PokeApi.getPokemon
  test\poke_api_test.dart 56:30                                 main.<fn>.<fn>
  package:test_api/src/backend/declarer.dart 171:27             Declarer.test.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1055:19                                  _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 73:23                       _asyncThenWrapperHelper
  package:test_api/src/backend/declarer.dart                    Declarer.test.<fn>.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 242:15              Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 1518:10                                  _runZoned
  dart:async/zone.dart 1465:12                                  runZoned
  package:test_api/src/backend/invoker.dart 239:5               Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/declarer.dart 169:33             Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 1518:10                                  _runZoned
  dart:async/zone.dart 1465:12                                  runZoned
  package:test_api/src/backend/declarer.dart 168:13             Declarer.test.<fn>
  package:test_api/src/backend/invoker.dart 392:25              Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  dart:async/future.dart 176:37                                 new Future.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1122:38                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 949:23                                   _CustomZone.bindCallback.<fn>
  dart:async-patch/timer_patch.dart 23:15                       Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 384:19                     _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 418:5                      _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 174:12                  _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 964:22                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 54:45                                   new Timer
  dart:async/timer.dart 91:9                                    Timer.run
  dart:async/future.dart 174:11                                 new Future
  package:test_api/src/backend/invoker.dart 391:21              Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 1518:10                                  _runZoned
  dart:async/zone.dart 1465:12                                  runZoned
  package:test_api/src/backend/invoker.dart 378:9               Invoker._onRun.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 430:15              Invoker._guardIfGuarded
  package:test_api/src/backend/invoker.dart 377:7               Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 101:24                     Chain.capture.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 1518:10                                  _runZoned
  dart:async/zone.dart 1465:12                                  runZoned
  package:stack_trace/src/chain.dart 99:12                      Chain.capture
  package:test_api/src/backend/invoker.dart 376:11              Invoker._onRun
  package:test_api/src/backend/live_test_controller.dart 185:5  LiveTestController._run
  package:test_api/src/backend/live_test_controller.dart 40:37  _LiveTest.run
  dart:async/future.dart 202:37                                 new Future.microtask.<fn>
  dart:async/zone.dart 1122:38                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 43:21                      _microtaskLoop
  dart:async/schedule_microtask.dart 52:5                       _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 118:13                  _runPendingImmediateCallback
  dart:isolate-patch/isolate_patch.dart 175:5                   _RawReceivePortImpl._handleMessage

00:00 +0 -1: Some tests failed.
</p>
</details>

I traced back the error in `options.dart` to this code:

```dart
/// generate uri
Uri get uri {
  var _url = path;
  if (!_url.startsWith(RegExp(r'https?:'))) { // If @RestApi's baseUrl is not a full http uri...
    _url = baseUrl + _url;
    var s = _url.split(':/');
    _url = s[0] + ':/' + s[1].replaceAll('//', '/'); // ...this line fails with index out of bounds.
  }
  var query = Transformer.urlEncodeMap(queryParameters);
  if (query.isNotEmpty) {
    _url += (_url.contains('?') ? '&' : '?') + query;
  }
  // Normalize the url.
  return Uri.parse(_url).normalizePath();
}
```

My proposed change would solve this without breaking existing functionality while **also** supporting the usage of the Dio client's `baseUrl`.

**Comment by trevorwang** [comment]
My bad. It seemed that it didn't generate right code when I tested.

Any special reason that you have to use the suffix at that position?

It's not very difficult to support this case but it will make the `baseUrl` misunderstanding.

From my side, The `baseUrl` at `options`, `RestApi` and `RestClient` are the same thing. The difference is only the last two will replace the one in options.

**Comment by stewemetal** [comment]
The only reason I was trying to achieve defining the `baseUrl` in `dio.options.baseUrl` is that from the DI point of view it makes sense. I would build a Dio client based on the build flavor of the app and defining the `baseUrl` in the client would be convenient.

For example, on Android - using OkHttp + Retrofit + Dagger - we can define the base URL by flavor in the *build.gradle* file. Let's call that constant `BASE_URL`.

Then, when building a `Retrofit` instance, we can provide `BASE_URL` to the `Retrofit.Builder` (Kotlin ahead):

```kotlin
@Provides
@Singleton
fun provideRetrofit(okHttpClient: OkHttpClient): Retrofit {
    return Retrofit.Builder()
            .addCallAdapterFactory(CoroutineCallAdapterFactory())
            .addConverterFactory(GsonConverterFactory.create())
            .client(okHttpClient)
            .baseUrl(BASE_URL)  //  <- here, BASE_URL example: "https://pokeapi.co/"
            .build()
}
```

With Retrofit on Android, you can describe an Api/Service/"Client" like this:

```kotlin
interface PokeApi {
    @GET("pokemon/{id}")
    fun getPokemon(@Path("id") int id): Deferref<NetworkPokemon>
}
```

If I understand correctly, in your - and the lib's - terminology the abstract class annotated with `@RestApi` serves as the API definition and the client as one.

So sure, I could easily go with a solution like this (back to Dart):

```dart
const BASE_URL = "https://pokeapi.co";

@RestApi(baseUrl: "$BASE_URL/api/v2")
abstract class PokeApi {
  factory PokeApi(Dio dio, {String baseUrl}) = _PokeApi;
    
  @GET("/pokemon/{id}")
  Future<NetworkPokemon> getPokemon(@Path() int id);
}
```

But from my point of view, this creates a direct dependency between the `BASE_URL` and `PokeApi` - the client.

By using the base URL from the provided Dio client - `dio.options.baseUrl` this tight coupling would loosen and it would create a more logically flexible solution. For example, one could re-route the client in runtime by setting its Dio instance's `baseUrl` to a different address - a niche feature, but someone may need it.

On the other hand:

> And we also need to consider how to support multiple endpoints with one `RestClient`.

Event with the current implementation, as a user of your library, one can define multiple "`RestClient`" classes, organized by the server they need to access for example.

If I would like to get Pokémon data, and let's say Todos in the same app, I would most definitely not use one class for both with different URLs on the endpoint methods. I'd do something like the following, one class for each server (domain):

```dart
// poke_api.dart
@RestApi(baseUrl: "https://pokeapi.co/api/v2")
abstract class PokeApi {
  factory PokeApi(Dio dio, {String baseUrl}) = _PokeApi;
    
  @GET("/pokemon/{id}")
  Future<NetworkPokemon> getPokemon(@Path() int id);
}

// todo_api.dart
@RestApi(baseUrl: "https://jsonplaceholder.typicode.com/")
abstract class TodoApi {
  factory TodoApi(Dio dio, {String baseUrl}) = _TodoApi;
    
  @GET("/todos/{id}")
  Future<NetworkPokemon> getTodo(@Path() int id);
}
```

These two classes could also use different Dio instances for more control over what's happening.

(Sorry for the long comment again, your lib seems promising and I'd like it to improve. :) )

**Comment by trevorwang** [comment]
Please try the below code. 
```
var client = PokeApi(BASE_URL)
```
There's a named parameter `baseUrl` here to support the multiple endpoints. 
The value in annotation will be ignored when you pass a value to named parameter `baseUrl`.

**Comment by stewemetal** [comment]
Thanks, I completely missed `baseUrl` parameter on the API class. This way it works as you described it, and kind of how I wanted things to behave.

This behavior should be documented though, as it's not trivial how this works without looking at the generated code (which won't be the first thing people would do, I guess).

So, about changing the `baseUrl` dynamically in runtime based on the Dio instance's `options.baseUrl`, is it completely off the table? 😄

**Comment by trevorwang** [comment]
If you want to use the `baseUrl` from Dio's instance, please use an empty `@RestApi()`

**Comment by trevorwang** [comment]
Feel free to reopen it if future question
