### ISSUE TITLE
[DioErrorType.DEFAULT]: type 'int' is not a subtype of type 'double' 

### ISSUE THREAD

**Issue by a43mrk** [trevorwang/retrofit.dart#142]
Hi there!
cast int to double is needed for scenarios when double value is supposed to be deserialized but number is rounded like 100 and not 100.0 :(
is there an work round for this issue?

**Comment by trevorwang** [comment]
Can you provide a sample code for this issue?

It should be an issue of [json_serializable](https://github.com/dart-lang/json_serializable) by your description

**Comment by a43mrk** [comment]
Thank you @trevorwang 
it only an endpoint that return a single double on the body.
the signature is:
  @GET("/foo/barById/{id}")
  Future<double> getFooBarById(@Path() int id);
that generates:
  @override
  getFooBarById(id) async {
    ArgumentError.checkNotNull(id, 'id');
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final Response<double> _result = await _dio.request('/foo/barById/$id',
        queryParameters: queryParameters,
        options: RequestOptions(
            method: 'GET',
            headers: <String, dynamic>{},
            extra: _extra,
            baseUrl: baseUrl),
        data: _data);
    final value = _result.data;
    return Future.value(value);
  }

Exceptions occurs when he assign that Response<T> from request :(
the exception message is:
Exception has occurred.
DioError (DioError [DioErrorType.DEFAULT]: type 'int' is not a subtype of type 'double'
#0      DioMixin.assureResponse (package:dio/src/dio.dart:1138:9)
#1      DioMixin._request.<anonymous closure> (package:dio/src/dio.dart:904:14)
#2      _rootRunUnary (dart:async/zone.dart:1134:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#7      Future._complete (dart:async/future_impl.dart:514:7)
#8      _SyncCompleter.complete (dart:async/future_impl.dart:53:12)
#9      Future.any.<anonymous closure> (dart:async/future.dart:459:45)
#10     _rootRunUnary (dart:async/zone.dart:1134:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#16     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)

**Comment by trevorwang** [comment]
It's not an issue of retorfit but [`dio`](https://github.com/flutterchina/dio),   please ask for help here.

It's recommended to return an object instead of only one basic value.

**Comment by a43mrk** [comment]
making `final Response<double> _result = await _dio.request('/foo/barById/$id',` dynamic:
`final  _result = await _dio.request('/foo/barById/$id',` and casting _result.data like _result.data.toDouble() solve my problem. but i don't want to edit generated code everytime:(

**Comment by trevorwang** [comment]
Please make sure that you return a number of  double instead of `int` value. The below code works for me.

```dart
  @GET("/")
  Future<double> getValue();
}
```
```dart
  @override
  getValue() async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final Response<double> _result = await _dio.request('/',
        queryParameters: queryParameters,
        options: RequestOptions(
            method: 'GET',
            headers: <String, dynamic>{},
            extra: _extra,
            baseUrl: baseUrl),
        data: _data);
    final value = _result.data;
    return Future.value(value);
  }

```

```dart

  test("test double value", () async {
    _server.enqueue(headers: _headers, body: jsonEncode(2.toDouble()));
    final result = await _client.getValue();
    print(result);
    expect(result, 2);
  });
}

```

**Comment by a43mrk** [comment]
hello @trevorwang 
i m not the owner of the api :(

**Comment by trevorwang** [comment]
convert the value to a float value by adding an interceptor to dio

**Comment by a43mrk** [comment]
ow :( this will cost performance..

**Comment by a43mrk** [comment]
thank you @trevorwang

**Comment by trevorwang** [comment]
A framework should provide a solution for all the common cases.  You know that the scenario is too special. 

It works when the content type and return value are set properly.  You have to do a hack as a workaround.
