### ISSUE TITLE
multipart list of files generation issues

### ISSUE THREAD

**Issue by romatroskin** [trevorwang/retrofit.dart#143]
When using MultiPart file upload with the list of files, like
```
@POST('/save')
@MultiPart()
Future<HttpResponse<void>> save(
      {@Part(data') Data data,
      @Part('attachments') List<File> attachments});
````

The generated sources for FormData looks like:
```
final _data = FormData.fromMap(<String, dynamic>{
  'post': jsonEncode(data ?? <String, dynamic>{}).toString(),
  'attachments': attachments
    ?.map((i) => MultipartFile.fromFileSync(i.path,
    filename: i.path.split(Platform.pathSeparator).last))
    ?.toList()
});
```

but according to the dio readme in this case: 
> The upload key eventually becomes "attachments[]"，This is because many back-end services add a middle bracket to key when they get an array of files.

also can be referred to https://github.com/flutterchina/dio/issues/633 

If you don't want “[]”，you should create FormData as follows（Don't use FormData.fromMap）:
```
final _data = FormData();
    _data.fields.add(
        MapEntry('data', jsonEncode(data ?? <String, dynamic>{}).toString()));
    _data.files.addAll(attachments?.map((i) => MapEntry(
        'attachments',
        MultipartFile.fromFileSync(i.path,
            filename: i.path.split(Platform.pathSeparator).last))));
```
so in case of generated solution it's not working usually in normal cases when the back-end services not adding middle bracket to key.
Looks like there should be some kind of choice between these two types of generated multipart requests, or maybe some kind to specify manual method implementation.
Also would be nice to provide the contentType for the files.
Thanks for work and attention.
Sincerely,
Roman.

**Comment by trevorwang** [comment]
Could you help test the workaround?

@romatroskin   @don-prog

**Comment by romatroskin** [comment]
looks like works fine for a usual back-end without "[]".
