### ISSUE TITLE
Return default Dio `Response`

### ISSUE THREAD

**Issue by fabiancrx** [trevorwang/retrofit.dart#146]
**Is your feature request related to a problem? Please describe.**
I want to be able to generate methods that return the default Response from Dio as:
```
  @POST("/Api/logout",)
  Future<Response>  logout(@Header('Authorization') String Authorization,
      {@Header('Content-Type') String contentType = 'application/json'});
```
Currently Response is treated as an object and the generator tries to  return:
```
    final value = Response<dynamic>.fromJson(_result.data);
```

**Describe the solution you'd like**
Add a conditional to the generator for when the type is Response
and instead of returning:
```
    final value = Response<dynamic>.fromJson(_result.data);
```
```
    final value = _result;
```

**Describe alternatives you've considered**
Returning the data as a String as :
```  
@POST("/Api/logout",)
  Future<Response>  logout(@Header('Authorization') String Authorization,
      {@Header('Content-Type') String contentType = 'application/json'});

```
this way the response.data is returned but the status codes and other parameters of the dio `Response` are lost.

**Additional context**
If you consider this feature interesting or worth included to the package i could issue a pull request

**Comment by trevorwang** [comment]
Try this 

https://github.com/trevorwang/retrofit.dart#get-orignal-http-reponse
