### ISSUE TITLE
Retrofit 2 CallAdapter 

### ISSUE THREAD

**Issue by ayalma** [trevorwang/retrofit.dart#147]
Hi and thank you in advance
I need something like [CallAdapter ](https://github.com/square/retrofit/wiki/Call-Adapters) in Retrofit2 

I need it to create something like [this](https://github.com/android/architecture-components-samples/blob/master/GithubBrowserSample/app/src/main/java/com/android/example/github/util/LiveDataCallAdapter.kt)

**Comment by trevorwang** [comment]
dart reflection API `dart:mirrors` is not allowed to be used in `flutter`.

There's no way to handle the nested generic types.
We will consider supporting this when there's a solution.
