### ISSUE TITLE
HEAD request should not require a body response object

### ISSUE THREAD

**Issue by d-silveira** [trevorwang/retrofit.dart#148]
Hi,

currently I needed to create an object to put on the interface endpoint stub signature as the Future response, otherwise the generated api has an error.

I would expect that no response should be needed, since the HEAD response should not have a body 

Regards

**Comment by trevorwang** [comment]
Please provide the sample code and the detailed logs here.

**Comment by trevorwang** [comment]
try ` Future<void>` as a return type
