### ISSUE TITLE
Allow observables to be defined as return instead of futures, like Android's retrofit does

### ISSUE THREAD

**Issue by d-silveira** [trevorwang/retrofit.dart#149]
Hi,

I don't really use futures unless I'm required to. What I'de really like is for this lib to 
allow observables to be defined as return instead of futures, like Android's retrofit does

Loving using this lib,
Thanks,
Regards

**Comment by d-silveira** [comment]
Hi, what do you think about it?

I personally don't have much use for futures, so What I do currently is in every call Observable.fromFuture(retrofit.endpoint());
Which I would like to avoid,to keep the code cleaner.

Thanks
Regards

**Comment by trevorwang** [comment]
I think it's good. But I won't have time to implement this in a coming couple of weeks. 
I am appreciated to take PR here.
