### ISSUE TITLE
How to set request time out?

### ISSUE THREAD

**Issue by Asad4132** [trevorwang/retrofit.dart#159]

**Comment by trevorwang** [comment]
Please use `dio.options.connectTimeout`

**Comment by kostadin-damyanov-prime** [comment]
> Please use `dio.options.connectTimeout`
> 
> All the basic HTTP configurations are set by`dio`

This sets timeout for the whole http client, correct? Does retrofit support setting a timeout per request? Dio supports it I think but it is not exposed by retrofit.
