### ISSUE TITLE
There is now way to handle 201 responses

### ISSUE THREAD

**Issue by ISvengali** [trevorwang/retrofit.dart#166]
`.....
}).catchError((Object obj) {

          switch (obj.runtimeType) {

            case DioError:

                    //handle any error but not 201
 
           default:

                    //here we have the 201 response 
                   // How to get them !!
`
And 201 not suppose to be at the catchError case at the first place !!

**Comment by trevorwang** [comment]
201 is right response so you cannot catch any error.

try this

https://github.com/trevorwang/retrofit.dart#get-orignal-http-reponse

**Comment by trevorwang** [comment]
Please reopen this issue if any further question.
