### ISSUE TITLE
Assume return type is void if not specified any

### ISSUE THREAD

**Issue by TarekkMA** [trevorwang/retrofit.dart#167]
**Describe the bug**
When the return type of a method is without any generic type attached the library should consider it as void instead of explicitly stating it .

- The following code snippet works fine.
```dart
  @POST("/user/signout")
  Future<void> signout(@Body() SignoutRequest request);
```
- But the following don't
```dart
  @POST("/user/signout")
  Future signout(@Body() SignoutRequest request);
```

The library assumes the type ,which is ``dynamic``, and attempt to call ``dynamic.fromJson(_result.data)``.

**Comment by trevorwang** [comment]
It should be `dynamic`. I add code to check whether it is `dynamic` or not before it calls `fromJson` method.
