### ISSUE TITLE
如何处理自定义解析json

### ISSUE THREAD

**Issue by JasonHezz** [trevorwang/retrofit.dart#172]
我使用[dart-json-mapper](https://github.com/k-paxian/dart-json-mapper)做json解析 避免重复代码
在生成代码中我想替换如下代码

```
final value = T.fromJson(_result.data) ;
```
成
 ```
final value = JsonMapper.deserialize<T>(_result.data);
```
应该如何处理比较好

**Comment by trevorwang** [comment]
这个需要修改generator的代码 

https://github.com/trevorwang/retrofit.dart/blob/master/generator/lib/src/generator.dart  搜索 `fromJ'son`

欢迎PR

**Comment by JasonHezz** [comment]
我的方案是在RestApi 增加String parser

parser 为JsonSerializable则是生成旧模式

parse为DartJsonMapper则生成JsonMapper.deserialize

默认值为JsonSerializable

不知道这个方案可行吗 如果可行 我会尝试在周末提交PRc

**Comment by trevorwang** [comment]
OK.    parser考虑使用枚举类型

**Comment by vanlooverenkoen** [comment]
Can someone explain me what this ticket exactly does?

**Comment by JasonHezz** [comment]
@vanlooverenkoen I'm sorry for that .

This is a discussion about how to custom deserialize json. 
I use dart json mapper and I prefer generate code 
```
final value = JsonMapper.deserialize<T>(_result.data);
```
rather than
```
final value = JsonMapper.deserialize<T>(_result.data);
```
That's the PR address.
If you want to use dart json mapper too.
Try code blow
```
@RestApi(
  baseUrl: 'http://111.229.144.56:7000/',
  parser: Parser.DartJsonMapper, 
)
abstract class RestClient {
}
```
But remember this only support deserialize , and `@Body` is not working because I have few time now , hopefully in next weeks I can finish that.
