### ISSUE TITLE
Dynamic responses

### ISSUE THREAD

**Issue by joshua-s** [trevorwang/retrofit.dart#174]
Thanks for building this useful tool! I am struggling with using it for one of the endpoints in my API.

In a normal case, the response will be a `List<CustomEntity>`. In the error case, the response will be a `Map<String, dynamic>` in the form `{"message": "An error message"}`.

If I define the endpoint as a `List<CustomEntity>`, the following code is generated:
```dart
final Response<List<dynamic>> _result = await _dio.request('endpoint',
    queryParameters: queryParameters,
    options: RequestOptions(
        method: 'GET',
        headers: <String, dynamic>{},
        extra: _extra,
        baseUrl: baseUrl),
    data: _data);
var value = _result.data
    .map((dynamic i) =>
        CustomEntity.fromJson(i as Map<String, dynamic>))
    .toList();
```

I also tried creating a `CustomResponse` class that has an overridden `fromJson` factory that can handle either the json as a list or a map, however the generated code is still blocking this use because it is forcing `Map<String, dynamic>`. It does so even if I set the endpoint to be `dynamic`:
```dart
final Response<Map<String, dynamic>> _result = await _dio.request(
        'endpoint',
        queryParameters: queryParameters,
        options: RequestOptions(
            method: 'GET',
            headers: <String, dynamic>{},
            extra: _extra,
            baseUrl: baseUrl),
        data: _data);
final value = CustomResponse.fromJson(_result.data);
```

**Comment by trevorwang** [comment]
Reflection is not working properly in flutter. It's not a good idea to handle different types of responses in one API.

My suggestion is to handle all errors in response with the 400 status code.  Then you can catch all error message from DioError

**Comment by joshua-s** [comment]
@trevorwang thanks for the response. Unfortunately, the API is external and I cannot make changes. Will try to figure out a way around this.
