### ISSUE TITLE
Failed to generate 'example.g.dart' file

### ISSUE THREAD

**Issue by jinjianxin** [trevorwang/retrofit.dart#176]
pubspec.yaml file:
  ```
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_banner_swiper: ^0.1.4
  dio: ^3.0.9
  dio_cookie_manager: 1.0.0
  retrofit: any
  logger: any  #for logging purpose
  json_annotation: ^3.0.0
  json_serializable: 3.2.0


dev_dependencies:
  retrofit_generator: any
  build_runner: any
  json_serializable: 3.2.0
  flutter_test:
    sdk: flutter
```

dart file:
```
import 'package:json_annotation/json_annotation.dart';
import 'package:retrofit/retrofit.dart';
import 'package:dio/dio.dart';

@RestApi(baseUrl: "https://5d42a6e2bc64f90014a56ca0.mockapi.io/api/v1/")
abstract class RestClient {
  factory RestClient(Dio dio, {String baseUrl}) = _RestClient;

  @GET("/tasks")
  Future<List<Task>> getTasks();
}

@JsonSerializable()
class Task {
  String id;
  String name;
  String avatar;
  String createdAt;

  Task({this.id, this.name, this.avatar, this.createdAt});

  factory Task.fromJson(Map<String, dynamic> json) => _$TaskFromJson(json);
  Map<String, dynamic> toJson() => _$TaskToJson(this);
}
```

flutter environment:

 ```
doctor --verbose
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.5 at /Users/xxx/Development/flutter
    • Framework revision 27321ebbad (4 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0
```

error message:
 
```
 flutter pub run build_runner build
[INFO] Generating build script...
[INFO] Generating build script completed, took 530ms

[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 12.4s

[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
[SEVERE] ../../../Development/flutter/.pub-cache/hosted/pub.flutter-io.cn/retrofit_generator-1.1.0/lib/src/generator.dart:700:39: Error: The method 'getDisplayString' isn't defined for the class 'DartType'. - 'DartType' is from 'package:analyzer/dart/element/type.dart' ('../../../Development/flutter/.pub-cache/hosted/pub.flutter-io.cn/analyzer-0.37.1+1/lib/dart/element/type.dart').Try correcting the name to the name of an existing method, or defining a method named 'getDisplayString'.      return refer(constant.typeValue.getDisplayString());                                      ^^^^^^^^^^^^^^^^
pub finished with exit code 78
```

**Comment by trevorwang** [comment]
https://github.com/trevorwang/retrofit.dart/blob/171921bd3806fd855d9d076bf71068774f544390/example/lib/example.dart#L9   Did you add the `part` line?

**Comment by jinjianxin** [comment]
new File:
 `import 'package:json_annotation/json_annotation.dart';
import 'package:retrofit/retrofit.dart';
import 'package:dio/dio.dart';

part 'example.g.dart';

@RestApi(baseUrl: "https://5d42a6e2bc64f90014a56ca0.mockapi.io/api/v1/")
abstract class RestClient {
  factory RestClient(Dio dio, {String baseUrl}) = _RestClient;

  @GET("/tasks")
  Future<List<Task>> getTasks();
}

@JsonSerializable()
class Task {
  String id;
  String name;
  String avatar;
  String createdAt;

  Task({this.id, this.name, this.avatar, this.createdAt});

  factory Task.fromJson(Map<String, dynamic> json) => _$TaskFromJson(json);
  Map<String, dynamic> toJson() => _$TaskToJson(this);
}`

error message:
`flutter pub run build_runner build
[INFO] Generating build script...
[INFO] Generating build script completed, took 539ms

[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 14.2s

[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
[SEVERE] ../../../Development/flutter/.pub-cache/hosted/pub.flutter-io.cn/retrofit_generator-1.1.0/lib/src/generator.dart:700:39: Error: The method 'getDisplayString' isn't defined for the class 'DartType'. - 'DartType' is from 'package:analyzer/dart/element/type.dart' ('../../../Development/flutter/.pub-cache/hosted/pub.flutter-io.cn/analyzer-0.37.1+1/lib/dart/element/type.dart').Try correcting the name to the name of an existing method, or defining a method named 'getDisplayString'.      return refer(constant.typeValue.getDisplayString());                                      ^^^^^^^^^^^^^^^^
pub finished with exit code 78
`

**Comment by trevorwang** [comment]
https://github.com/trevorwang/retrofit.dart/tree/master/flutter_example

**Comment by jinjianxin** [comment]
Th
