### ISSUE TITLE
Generated code causes analyzer error / warning

### ISSUE THREAD

**Issue by edwardaux** [trevorwang/retrofit.dart#178]
I recently upgraded Flutter and now I see a couple of issues in the generated code from retrofit. eg. using this as an input:
```
abstract class API {
  Future<User> login({String userid, String password});
}
```

## Problem 1 
Looks like `implicit_dynamic_parameter` is now an error, not a warning so the code here causes problems:

https://github.com/trevorwang/retrofit.dart/blob/8930a2d8ad2eb2da732e879420eb09405625cac5/generator/lib/src/generator.dart#L635
Can we emit `dynamic` in front of the `v` variable? eg.
```
blocks.add(Code("$_queryParamsVar.removeWhere((k, dynamic v) => v == null);")); 
```

## Problem 2
The generate function for login looks like:
```
@override
  login({userid, password}) async {
   ...
  }
```
Note that it has lost the return type. I can at suppress this one with the `always_declare_return_types` analyzer flag, but it would be good if I didn't need to.

## Versions I'm Using
FWIW, I'm using the following:
* Flutter 1.18.0-6.0.pre.80
* Analyzer 0.39.7
* Retrofit 1.3.3

BTW, thanks for a great library. I love it.

**Comment by szotp** [comment]
Or just add ignore_for_file to each generated file.

**Comment by nioncode** [comment]
In my project I use an `analysis_options.yaml` file to exclude all generated code from the analyzer:
```
analyzer:
  exclude:
    - "lib/generated/**"
    - "lib/*.g.dart"
```

**Comment by trevorwang** [comment]
The `exclude` option seems not working when enabling strong mode.

https://github.com/dart-lang/sdk/issues/25551


Try this when @nioncode 's workaround is not working .


Create a `build.yaml` file and add the following code 
```
targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - implicit_dynamic_parameter

```

This option will tell source_gen to generate `ignore_file` to the code

```
// ignore_for_file: implicit_dynamic_parameter
```

**Comment by edwardaux** [comment]
I already have a build.yaml that contains that entry (and I can see that it does get added to the generated file).  The problem is that it the analyzer is flagging it as an error, not a warning so it can't just be ignored.

If I turn off strong mode, the analyzer doesn't complain but I don't want to do that.

**Comment by trevorwang** [comment]
I think we have to disable the strong mode before the related issue is fixed by Dart team.

**Comment by edwardaux** [comment]
Umm... why not just explicitly set the type of `v` to `dynamic`? eg.
```
blocks.add(Code("$_queryParamsVar.removeWhere((k, dynamic v) => v == null);")); 
```
Unless I've missed something, this will solve the problem whether users are using strong mode or not.

**Comment by trevorwang** [comment]
I believe that you would encounter the same issue when you use a json_serializable

dart-lang/json_serializable/issues/557


I enabled the strong mode before, then I found that analyzer not working when I use `json_serializable` 

I'd like to fix this issue when analyzer working in the future.

**Comment by trevorwang** [comment]
Currently `json_serializable` is bundled in this library.  Considering adding a converter layer to decouple the dependency of any data serialization libs.

**Comment by edwardaux** [comment]
hmm... that's true... I was wondering why I wasn't seeing the same error for my json_serializable files... turns out that VS Code doesn't report any errors unless you actually open the files in VS Code (same for the files generated by retrofit).  As long as I don't actually open the file, I don't see any errors.

however, remembering to not open generated files isn't really a sustainable development pattern.  as you mentioned earlier, it looks like https://github.com/dart-lang/sdk/issues/25551 is the underlying problem... however, given that that has been open for over 4 years, I'm not holding out much hope that it is going to be fixed anytime soon.

I guess my point is that you're right we can't solve it for other dependencies, but in this case, it seems to me that this one is an easy one to solve for this project.

if it helps, I can create a PR

**Comment by trevorwang** [comment]
Yeah, I am really appreciated to take PRs.

**Comment by szotp** [comment]
I guess that's one way to keep issue list short...
