### ISSUE TITLE
Considering replacing json_seralizable by dart_json_mapper 

### ISSUE THREAD

**Issue by trevorwang** [trevorwang/retrofit.dart#183]
I am considering using `dart_json_mapper` as the default data serialization engine. 

Any ideas here?

**Comment by JasonHezz** [comment]
I'd love to do some PR, but this is a break change.

**Comment by trevorwang** [comment]
Yes. I am planning to do  refactoring on version 2

**Comment by JasonHezz** [comment]
Any roadmap?
As far as I can see, there are something we can improve.
Move json serialization logic out of generator.  Like [retrofit-converters](https://github.com/square/retrofit/blob/master/retrofit-converters/README.md#retrofit-converters)

**Comment by trevorwang** [comment]
Not yet. 

I will create a new issue discussing the roadmap.

**Comment by trevorwang** [comment]
dart_json_mapper has limitation on dart code obfuscate

https://pub.dev/packages/dart_json_mapper#known-limitations

keeping using json_serializable until there's a better solution.

**Comment by xVemu** [comment]
Any news on this after 3 years?
