### ISSUE TITLE
It does not override options values from Dio.Options

### ISSUE THREAD

**Issue by fifanrg** [trevorwang/retrofit.dart#186]
**Retrofit generator does not override Options passed to Dio**
For instance, if I create a dio() client with 
var dio = Dio();
dio.options.followRedirects = false;

then in the generated method, it does not override the value and still set to the default value, which is true. 

Is that possible to provide annotation on the options of Dio for instance? 

Thanks !

**Comment by trevorwang** [comment]
Yes. There's already a `DioOption` here.
https://github.com/trevorwang/retrofit.dart/blob/79c07cb5580bb0d39f67373c837a900b25d1b54b/example/lib/example.dart#L113
