### ISSUE TITLE
Will support RxDart?

### ISSUE THREAD

**Issue by Turbozanik** [trevorwang/retrofit.dart#189]
I am Android developer. It is glad to see this project. Will it support Rx pattern? Also, capture common errors like network unavailable, status code not 200 and throw exception.

It would be great to have an rxDart adapter as it was done for android retrofit lib.

You can have a look on a similar conversation for chopper https://github.com/lejard-h/chopper/issues/59.

If supported Rx pattern, assume to like it
||
V

```
import "dart:async";
import 'package:chopper/chopper.dart';

part "my_service.chopper.dart";

@ChopperApi(baseUrl: "/resources")
abstract class MyService extends ChopperService {
  static MyService create([ChopperClient client]) => _$MyService(client);

  @Get(url: "{id}")
  Observable<Response> getResource(@Path() String id);

  @Get(headers: const {"foo": "bar"})
  Observable<Response<Map>> getMapResource(@Query() String id);

  @Post(url: 'multi')
  @multipart
  Observable<Response> postResources(
    @Part('1') Map a,
    @Part('2') Map b,
    @Part('3') String c,
  );

  @Post(url: 'file')
  @multipart
  Observable<Response> postFile(
    @FileField('file') List<int> bytes,
  );
}
```

**Comment by trevorwang** [comment]
duplicated to #149

**Comment by flashiran1** [comment]
@trevorwang please support

**Comment by trevorwang** [comment]
@flashiran1   please refer to #194
