### ISSUE TITLE
wrong generated code when set `name` of @Path()

### ISSUE THREAD

**Issue by tungpham6195** [trevorwang/retrofit.dart#191]
hello, i got this problem when try to set the `name` of @Part(), but the generate code generated with wrong `name` 

```
@Part(name: 'token') String fcmToken
```

the generated code
```
_data.fields.add(MapEntry('fcmToken', fcmToken));
```
version of dependency i'm using is `retrofit_generator: 1.3.1+9`
please verify this, thank you

**Comment by trevorwang** [comment]
Please upgrade to latest generator
