### ISSUE TITLE
Question: Supporting absolute URLs

### ISSUE THREAD

**Issue by edwardaux** [trevorwang/retrofit.dart#197]
I'm raising this as a feature request, but perhaps the capability is already there and I just can't find it...

One my APIs returns JSON that looks something like:
```
{
  "name": "Blah",
  "detailURL": "https://x.x.x.x/api/v1/blah?foo=abr"
}
```
I've already got code that accepts this response, but now I need to call the detail API based on the value of the `detailURL` field. Conceptually, my retrofit definition might look something like:
```
abstract class myAPI {
  Future<DetailObject> fetchDetail(@GET Uri detailURL);
}
```
But I can't seem to find anything that I can use to do this. Maybe `@path`... but that seems to need a value parameter.  Essentially, I just want to be able to somehow pass a full URL for Retrofit to follow. 

Is there anything that I can use to achieve this? Thanks a lot.

**Comment by trevorwang** [comment]
Did you tried the below code ?
```
@Get("{url}")
abstract class myAPI {
  Future<DetailObject> fetchDetail(@Path("url")String url);
}u
```

**Comment by edwardaux** [comment]
well, that's embarrassing... I didn't think to try that 😊 works perfectly! 

thanks so much - not just for this advice, but for the whole library! 🙌
