### ISSUE TITLE
support concrete method implementations on the abstract Api

### ISSUE THREAD

**Issue by nioncode** [trevorwang/retrofit.dart#199]
It would be great if retrofit would support helper implementations in the Api class. E.g., the body of a json object must be a `Map<String, dynamic>`. Internally, my maps are all stored as `Map<int, dynamic>` though, since I use unique integer ids all over the place. To solve this, I have to map the keys from int to string.

Example:
```dart
@RestApi()
abstract class SampleApi {
  factory SampleApi(Dio dio, {String baseUrl}) => _SampleApi(dio, baseUrl);

  @PUT('/data')
  Future<void> _put(@Body() Map<String, SomeData> data);

  Future<void> put(Map<int, SomeData> data) {
    return _putUserdata(data.map((k, v) => MapEntry(k.toString(), v)));
  }
}
```

When doing this, however, I get a compilation error after generating the implementation with retrofit:
> error: Missing concrete implementation of 'SampleApi.put'. (non_abstract_class_inherits_abstract_member at [sample] lib/SampleApi.g.dart:107)

Is there a requirement for retrofit to `implement` the API class instead of `extending` it?

**Comment by trevorwang** [comment]
How about to add extension to add method to `Map`?

I think it's better than adding method for each method.

```
extension on Map<Int,dynamic> {
     Map<String,dynamic> toStringKey() {
           return this.map((k, v) => MapEntry(k.toString(), v))
    }
}
```
