### ISSUE TITLE
depends failed

### ISSUE THREAD

**Issue by nagate** [trevorwang/retrofit.dart#2]
Because every version of flutter from sdk depends on meta 1.1.6 and every version of retrofit depends on meta ^1.1.7, flutter from sdk is incompatible with retrofit.
So, because demo depends on both flutter any from sdk and retrofit any, version solving failed.
pub get failed (1)
exit code 1

**Comment by trevorwang** [comment]
Feel free to reopen it if this issue is reproduced.
