### ISSUE TITLE
header is constant.

### ISSUE THREAD

**Issue by sanalkv** [trevorwang/retrofit.dart#204]
I'm trying to set a variable in header, but its not accepting as the variable is not constant.
the variable value changes based on the user interactions, so i cannot make it as constant. Is it possible to provide non constant variables as headers ?

**Comment by trevorwang** [comment]
Can this solve your problem?

```
  @HEAD('/')
  Future headRquest4(@Header("hello") String hello);

```

And an interceptor is better for this scenario

**Comment by sanalkv** [comment]
if i use interceptor, it uses the initial value of the variable, later if the variable is updated, it doesn't have any impact on the interceptor header, as it still uses the initial value instead of updated value.

if i follow the above approach, i will have to pass variable in every method which is not ideal. Is there any other approach to provide dynamic header ?
