### ISSUE TITLE
如何支持返回泛型

### ISSUE THREAD

**Issue by ytsxg123** [trevorwang/retrofit.dart#205]
提示代码返回结果与实际出入较大。
实际多为{'code':200,'message':'成功','data':T }
这种结构的该如何包装。

**Comment by trevorwang** [comment]
目前没有好的办法 
flutter不支持反射 所以好多东西没有办法做

正在重构2.0的版本 计划加入converter  看看这不能怎么支持好点

**Comment by trevorwang** [comment]
https://github.com/google/json_serializable.dart/blob/bda9eb9ff51f68cbc0036cd8a923f6c03c46f91b/example/lib/json_converter_example.dart#L10

参考这里
