### ISSUE TITLE
Response is null when url is 404. 

### ISSUE THREAD

**Issue by fifanrg** [trevorwang/retrofit.dart#208]
**response is null when there is 404**
switch (error.runtimeType) {
      case DioError:
        Response response = (error as DioError).response;
//       response == null here when it is 404. 
        _errorResponseHandler(response);
        break;
      default:
        throw Exception("Unexpected error");
    }

**Comment by trevorwang** [comment]
It's handled by [dio](https://github.com/flutterchina/dio). Retrofit didn't do anything about this.
