### ISSUE TITLE
关于2.0 Convert 支持

### ISSUE THREAD

**Issue by jiechic** [trevorwang/retrofit.dart#210]
在2.0分支查看关于 Convert的实现，这个代码
按照逻辑是，比如判断isFormUrlEncoded才会进入，但如果我不需要这种逻辑，但是我需要进入convert 转换一个 http.get queryParameter 的 DateTime -> String 如何实现？希望convert能够来放开这样的转换。除了基本数据类型，不匹配的类型，都可用自定义转换器来进行转换

 if (!isFormUrlEncoded(request)) {
      if (converter != null) {
        newReq = converter.convertRequest(request);
        assert(newReq != null);
      }
    }

**Comment by jiechic** [comment]
或者参看下面的某个方法，在这里也希望能够提供
https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit2/Converter.java

`/**
     * Returns a {@link Converter} for converting {@code type} to a {@link String}, or null if
     * {@code type} cannot be handled by this factory. This is used to create converters for types
     * specified by {@link Field @Field}, {@link FieldMap @FieldMap} values, {@link Header @Header},
     * {@link HeaderMap @HeaderMap}, {@link Path @Path}, {@link Query @Query}, and {@link
     * QueryMap @QueryMap} values.
     */
    public @Nullable Converter<?, String> stringConverter(
        Type type, Annotation[] annotations, Retrofit retrofit) {
      return null;
    }`

**Comment by trevorwang** [comment]
这部分功能还在开发中，只是部分代码 后续有持续改进
