### ISSUE TITLE
How to remove %5B%5D Array [] in Flutter's Retrofit Get Call

### ISSUE THREAD

**Issue by do4Mother** [trevorwang/retrofit.dart#214]
**Describe the bug**
When I try to send Array in Flutter's Retrofit Get Call, I got the following errors:

I expect: https://127.0.0.1/api?someId=1&someId=2&someId=3&someId=4&someId=5&someId=6

I got: http://127.0.0.1/api?someId%5B%5D=1&someId%5B%5D=2&someId%5B%5D=3&someId%5B%5D=4&someId%5B%5D=5&someId%5B%5D=6

Is there any way to remove this %5B%5D in Dart/ Flutter. Retrofit.

**My source code**
`@GET("services")
  Future<List<Service>> searchServices(@Queries() List<String> filterGame);`

**Reftrofit generator**
`@override
  searchServices(filterGame) async {
    ArgumentError.checkNotNull(filterGame, 'filterGame');
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    queryParameters.addAll(filterGame?.toJson() ?? <String, dynamic>{});
    final _data = <String, dynamic>{};
    final Response<List<dynamic>> _result = await _dio.request('services',
        queryParameters: queryParameters,
        options: RequestOptions(
            method: 'GET',
            headers: <String, dynamic>{},
            extra: _extra,
            baseUrl: baseUrl),
        data: _data);
    var value = _result.data
        .map((dynamic i) => Service.fromJson(i as Map<String, dynamic>))
        .toList();
    return value;
  }`

on my pubspec.yaml
dio: ^3.0.9
retrofit: ^1.3.4
retrofit_generator: ^1.3.7

same problem as the following link https://stackoverflow.com/questions/61653846/how-to-remove-5b5d-array-in-flutters-retrofit-get-call

**Comment by trevorwang** [comment]
currently please use an interceptor to remove them

#100

**Comment by do4Mother** [comment]
> currently please use an interceptor to remove them
> 
> #100

ok thank you @trevorwang
