### ISSUE TITLE
Nullable @Field()

### ISSUE THREAD

**Issue by SBNTT** [trevorwang/retrofit.dart#217]
see this closed issue: https://github.com/trevorwang/retrofit.dart/issues/73

this comment (https://github.com/trevorwang/retrofit.dart/issues/73#issuecomment-546771470) does not helps at all

this (https://github.com/trevorwang/retrofit.dart/issues/73#issuecomment-546347644) is working but we must edit generated files manually

**Comment by 6h4n3m** [comment]
I second this, we just need an option to indicate a parameter may be null in the @Field() annotation, and the generator should just not add the ArgumentError.checkNotNull() method call for that particular parameter in the generated method.

In its current state, this is a really big issue when it comes to optional parameters in API calls, I can just add the optional parameters as null in 1 call or use many conditional statements to call the Retrofit functions with just the parameters needed (I prefer not to touch the generated files, especially during heave development when I'm just adding/removing api endpoints all the time).
