### ISSUE TITLE
Question about @POST

### ISSUE THREAD

**Issue by claudneysessa** [trevorwang/retrofit.dart#218]
Hello, I'm using this package, but I have a doubt, when I make a GET request it returns me a Map, if I do a POST it is giving me an error message [String must provide a `toJson ()` method which return a Map.
It is programmer's responsibility to make sure the String is properly serialized] if I try to receive a map, but it gets a string ... would POST return the instance of the class as well?

My JSON:

{
    "USN_COD": 6,
    "USN_NOM": "NAME",
    "CF_COD": 115,
    "CF_RSOCIAL": "NAME OF USER",
    "VD_COD": 1,
    "VD_NOM": "Name od user",
    "VD_TFUN": 99,
    "VD_TFUN_DESCRICAO": "Others",
    "USER_TOKEN": "7240ae35e5e923ab9803cb35c25e4ac1.9fc169efbf5e8d7f7dd5479fda06684b.501ef156aac018aa66dddba222c56f1a"
}

My Class:

import 'package:json_annotation/json_annotation.dart';

part 'usuario_token_dto.g.dart';

@JsonSerializable()
class UsuarioTokenDTO {
  @JsonKey(name: 'USN_COD')
  int usnCod;
  @JsonKey(name: 'USN_NOM')
  String usnNom;
  @JsonKey(name: 'CF_COD')
  int cfCod;
  @JsonKey(name: 'CF_RSOCIAL')
  String cfRsocial;
  @JsonKey(name: 'VD_COD')
  int vdCod;
  @JsonKey(name: 'VD_NOM')
  String vdNom;
  @JsonKey(name: 'VD_TFUN')
  int vdTfun;
  @JsonKey(name: 'VD_TFUN_DESCRICAO')
  String vdTfunDescricao;
  @JsonKey(name: 'USER_TOKEN')
  String userToken;

  UsuarioTokenDTO({
    this.usnCod,
    this.usnNom,
    this.cfCod,
    this.cfRsocial,
    this.vdCod,
    this.vdNom,
    this.vdTfun,
    this.vdTfunDescricao,
    this.userToken,
  });

  factory UsuarioTokenDTO.fromJson(Map<String, dynamic> json) => _$UsuarioTokenDTOFromJson(json);

  Map<String, dynamic> toJson() => _$UsuarioTokenDTOToJson(this);
}

Erro:

[INFO] Running build...
[WARNING] retrofit_generator:retrofit on lib/infrastructure/service/store/api_service_store.dart:        
String must provide a `toJson()` method which return a Map.
It is programmer's responsibility to make sure the String is properly serialized
[INFO] Running build completed, took 720ms

My Call on service

  @POST("authentication")
  Future<UsuarioDTO> postAuthentication(@Body() String body);

Whether and using string works

  @POST("authentication")
  Future<String> postAuthentication(@Body() String body);

**Comment by trevorwang** [comment]
You cannot use `@Body` to a string parameter

**Comment by claudneysessa** [comment]
Solved!
