### ISSUE TITLE
Equivalent of @FieldMap in Retrofit

### ISSUE THREAD

**Issue by cresusjpt** [trevorwang/retrofit.dart#219]
**Equivalent of @FieldMap.**
I'm rewriting an application for IOS purpose in flutter. In android version i use retrofit. i'm stuck on @fieldmap option wich permit to send data according to the value of a field. i'm not finding the same in this plugin. I'm wrong ? 

**Exemple of the code i'm trying to do**
```
@FormUrlEncoded
@POST("/ram")
Single<ResponseBody> avanceSwitch(@FieldMap HashMap<String, String> hashFields);
```
**Calling the post method**
```
tracker.avanceSwitch(pojo.mapData())
                                .subscribeOn(Schedulers.io())
                                .observeOn(AndroidSchedulers.mainThread())
                                .subscribeWith(fetchAvanceSwitch())
```
**And the content of mapData method**
```
public HashMap<String, String> mapData() {
        HashMap<String, String> map = new HashMap<>();
        map.put("d", getHourDate());
        map.put("b1", getBegin1());
        map.put("e1", getEnd1());
        map.put("b2", getBegin2());
        map.put("e2", getEnd2());
        map.put("b3", getBegin3());
        map.put("e3", getEnd3());
        map.put("b4", getBegin4());
        map.put("e4", getEnd4());
        map.put("p", getPower());

        if (calendar.isMonday())
            map.put("j1", getMonday());
        if (calendar.isTuesday())
            map.put("j2", getTuesday());
        if (calendar.isWednesday())
            map.put("j3", getWednesday());
        if (calendar.isThursday())
            map.put("j4", getThursday());
        if (calendar.isFriday())
            map.put("j5", getFriday());
        if (calendar.isSaturday())
            map.put("j6", getSaturday());
        if (calendar.isSunday())
            map.put("j7", getSunday());

        return map;
    }
```
if we are not monday for example the j1 field won't be send.

I'm not the author of the api, i can't change it.

How can i do the same in flutter ?

**Comment by 6h4n3m** [comment]
Have you tried using this?

`  @POST("/ram")
  Future<ResponseBody> avanceSwitch(
      @Body() Map<String, dynamic> map);
`

**Comment by cresusjpt** [comment]
> Have you tried using this?
> 
> ```
> @POST("/ram")
> Future<ResponseBody> avanceSwitch(@Body() Map<String, dynamic> map);
> ```
> 
> You would instantiate your map like this:
> 
> ```
> var data = Map<String, dynamic>();
> data['email'] = 'test@test.com';
> ```

Thanks for answering. I'll try and get back to you.

**Comment by 6h4n3m** [comment]
> 
> 
> > Have you tried using this?
> > ```
> > @POST("/ram")
> > Future<ResponseBody> avanceSwitch(@Body() Map<String, dynamic> map);
> > ```
> > 
> > 
> > You would instantiate your map like this:
> > ```
> > var data = Map<String, dynamic>();
> > data['email'] = 'test@test.com';
> > ```
> 
> Thanks for answering. I'll try and get back to you.

Can you confirm whether that is what you were looking for? if it is, then probably get the issue closed.

**Comment by cresusjpt** [comment]
> > > Have you tried using this?
> > > ```
> > > @POST("/ram")
> > > Future<ResponseBody> avanceSwitch(@Body() Map<String, dynamic> map);
> > > ```
> > > 
> > > 
> > > You would instantiate your map like this:
> > > ```
> > > var data = Map<String, dynamic>();
> > > data['email'] = 'test@test.com';
> > > ```
> > 
> > 
> > Thanks for answering. I'll try and get back to you.
> 
> Can you confirm whether that is what you were looking for? if it is, then probably get the issue closed.

@6h4n3m Sorry I'm late, I just tested it. It's exactly what I'm looking for. i'm closing the issue.

**Comment by cresusjpt** [comment]
Thanks
