### ISSUE TITLE
Ignore null attributes using @Body()

### ISSUE THREAD

**Issue by SBNTT** [trevorwang/retrofit.dart#221]
following the same principle as this issue: https://github.com/trevorwang/retrofit.dart/issues/217

Giving the following example:

```dart
@JsonSerializable()
class UpdateUserRequest {

  String firstName;
  String lastName;
  String email;

  UpdateUserRequest({
    this.firstName, 
    this.lastName, 
    this.email, 
  });

  factory UpdateUserRequest.fromJson(Map<String, dynamic> json) => _$UpdateUserRequestFromJson(json);
  Map<String, dynamic> toJson() => _$UpdateUserRequestToJson(this);
}
```

All `UpdateUserRequest` attributes are optionals, then some may be null

```dart
@PUT("/{uid}")
Future<void> update({
  @required @Path() String uid,
  @required @Body() UpdateUserRequest request,
});
```

generates:
```dart
@override
update({uid, request}) async {
  ArgumentError.checkNotNull(uid, 'uid');
  ArgumentError.checkNotNull(request, 'request');
  const _extra = <String, dynamic>{};
  final queryParameters = <String, dynamic>{};
  queryParameters.removeWhere((k, v) => v == null);
  final _data = <String, dynamic>{};
  _data.addAll(request?.toJson() ?? <String, dynamic>{});
  _data.removeWhere((key, value) => value == null);  // <------ This should be added
  await _dio.request<void>('/$uid',
      queryParameters: queryParameters,
      options: RequestOptions(
          method: 'PUT',
          extra: _extra,
          baseUrl: baseUrl),
      data: _data);
  return null;
}
```

**Comment by SBNTT** [comment]
Same when @Body() is of type Map

**Comment by SBNTT** [comment]
Seems like this issue fix has been reverted. We should reopen this one @trevorwang

**Comment by trevorwang** [comment]
it caused #224  issue. 

Please add more code to check this scenario and the unit test should be committed at the same time.

**Comment by SBNTT** [comment]
Oh, sorry it was a mistake on my side.

[This](https://github.com/trevorwang/retrofit.dart/pull/222/commits/d954fa5c94744e542fdc6173d782228e4fc4e932#diff-c32d94163bf53716580c4c7c7effcf0bR703) added line is not at the right place. It has to take place inside the `else` just above. 
That done, `_data` will necessarily be of type `Map<String, dynamic> so it's safe to remove all pairs where value is null.

i'll add some tests for all these scenarios and we'll be ready to go

**Comment by nirbar89** [comment]
guys. its not best practice...
dealing with null is not just removing them...
in somecases we want to pass null to the server
you need to do nullable flag or something
