### ISSUE TITLE
Add support for query arrays

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [trevorwang/retrofit.dart#228]
**Is your feature request related to a problem? Please describe.**
I'm trying to add a decorator to accept a list of strings. The API calls for query params like this
`a=1&include=x&include=y`. I saw `@Queries`, but it doesn't take parameters.

**Describe the solution you'd like**
Make a decorator like `@Queries` that takes a `List`

**Describe alternatives you've considered**
Manually entering it into the generated code following [this comment](https://github.com/flutterchina/dio/issues/315#issuecomment-496836071)

**Comment by ThinkDigitalSoftware** [comment]
Unstagnating issue

**Comment by amebrahimi** [comment]
Anyone has suggestion on this?

**Comment by ThinkDigitalSoftware** [comment]
> Anyone has suggestion on this?

Yeah, you need to use the xUri commands. dio.getUri, dio.postUri etc, and put them in there manually.
Here's an [issue](https://github.com/flutterchina/dio/issues/315) about the topic

**Comment by amebrahimi** [comment]
@ThinkDigitalSoftware how can I use this solution with retrofit?

**Comment by ThinkDigitalSoftware** [comment]
> @ThinkDigitalSoftware how can I use this solution with retrofit?

Generate the code with a regular param, then go in and edit the generated code to accept the param you need and pass it to the getUri function or whichever method you're using. You just need to find where it would use the regular method and replace it.

**Comment by amebrahimi** [comment]
That's bad because when I run `build_runner build` it will replace the generated modified file

**Comment by ThinkDigitalSoftware** [comment]
You're right.

**Comment by amebrahimi** [comment]
Don't close it please. I'm waiting for the fix.

**Comment by trevorwang** [comment]
try this #100 as a workaround

**Comment by amebrahimi** [comment]
@trevorwang I'm using it but I like to have a solid solution as part of the library.

**Comment by trevorwang** [comment]
A lot of changes are needed to fix this issue due to the former design. And right now I don't have much time working on this.

**Comment by ThinkDigitalSoftware** [comment]
Bumping this to ward off the stale-bot
