### ISSUE TITLE
Wrong line in example code

### ISSUE THREAD

**Issue by Lootwig** [trevorwang/retrofit.dart#23]
The line

`static final RestClient instance([Dio dio]) = _RestClient(dio);`

does not compile. The keyword "final" can't be used and the "equals" operation does not make sense (method on LHS, constructor on RHS).

**Comment by trevorwang** [comment]
Could you link to the source file?
It should be the following code in example file
`factory RestClient(Dio dio) = _RestClient;`

**Comment by Lootwig** [comment]
I'm talking about the readme:
https://github.com/trevorwang/retrofit.dart/blob/master/README.md
It's the first line within class "RestClient".

**Comment by trevorwang** [comment]
@Lootwig  Please run the example project to have a try. I will update the readme file later.
