### ISSUE TITLE
Handling empty response body

### ISSUE THREAD

**Issue by kay14** [trevorwang/retrofit.dart#230]
I have an API service which either returns a JSON in its response body or an empty response body.
When the empty response body is returned the generated file doesn't handle it gracefully and instead throws the following exception

> The type "String" can't be converted to type "Map<String,dynamic>"

Is there a way to handle this such that it is not treated as an error?

**Comment by trevorwang** [comment]
Can you describe why you have to return an empty body?

if you want to show an empty list, please give a "[]" as a response instead of empty string

**Comment by kay14** [comment]
I am using a 3rd part API service and the service is returning an empty response body under certain conditions and a JSON response under another condition.
Is there a way for me to handle it on the client side?

**Comment by trevorwang** [comment]
In this scenario you have to use `Response<String> to receive the result and covert to json manually.

**Comment by kay14** [comment]
Okay. Thank You.

I will try it out and let you know.
