### ISSUE TITLE
problem : retrofit Do not work with version Flutter    1.20.2 

### ISSUE THREAD

**Issue by s2yed** [trevorwang/retrofit.dart#231]
retrofit Do not work with version   1.20.2  

I reverted when I returned to the version before 1.20.2, which is 1.17.5

Please solve this problem with the latest release of Filters

Bad state: Unexpected diagnostics:
C: \ flutter \ bin \ cache \ dart-sdk \ lib \ core \ uri.dart: 3259: 39 - Expected an identifier.
[SEVERE] json_serializable: json_serializable on lib / data / api / api_client.dart:
Bad state: Unexpected diagnostics:
C: \ flutter \ bin \ cache \ dart-sdk \ lib \ core \ uri.dart: 3259: 39 - Expected an identifier.
[INFO] 2.2s elapsed, 1/17 actions completed.
[INFO] 3.3s elapsed, 1/17 actions completed.
[WARNING] No actions completed for 15.0s, waiting on:
- json_serializable: json_serializable on lib / data / model / categories_ / categories.dart
- json_serializable: json_serializable on lib / data / model / categories_ / data_categories.dart
- json_serializable: json_serializable on lib / data / model / categories_ / data_categories_pagination.dart
- json_serializable: json_serializable on lib / data / model / city_ / city.dart
- json_serializable: json_serializable on lib / data / model / city_ / data_city.dart
... and 11 more
[INFO] 17.2s elapsed, 1/17 actions completed.
[INFO] 18.3s elapsed, 1/17 actions completed.
[INFO] 19.3s elapsed, 1/17 actions completed.
[INFO] 20.4s elapsed, 1/17 actions completed.
[INFO] 21.5s elapsed, 1/17 actions completed.
[INFO] 22.6s elapsed, 1/17 actions completed.
[INFO] 23.7s elapsed, 1/17 actions completed.
[INFO] 24.8s elapsed, 1/17 actions completed.
[INFO] 25.8s elapsed, 1/17 actions completed.
[INFO] 26.9s elapsed, 1/17 actions completed.
[INFO] 28.0s elapsed, 1/17 actions completed.
[INFO] 29.0s elapsed, 1/17 actions completed.
[INFO] 30.1s elapsed, 1/17 actions completed.
[INFO] 31.2s elapsed, 1/17 actions completed.
[WARNING] No actions completed for 15.1s, waiting on:
- json_serializable: json_serializable on lib / data / model / categories_ / categories.dart
- json_serializable: json_serializable on lib / data / model / categories_ / data_categories.dart
- json_serializable: json_serializable on lib / data / model / categories_ / data_categories_pagination.dart
- json_serializable: json_serializable on lib / data / model / city_ / city.dart
- json_serializable: json_serializable on lib / data / model / city_ / data_city.dart
... and 11 more

**Comment by trevorwang** [comment]
due  to #229
