### ISSUE TITLE
Headers not work

### ISSUE THREAD

**Issue by flashiran1** [trevorwang/retrofit.dart#232]
**Describe the bug**
i cannot set headers for post request
has error in Headers

> Annotation must be either a const variable reference or const constructor invocation.

how fix ?

**Code**

```
import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';
import 'package:web/output.dart';
import 'package:web/model/task_model.dart';
import 'package:dio/dio.dart' hide Headers;

part 'api_service.g.dart';

@RestApi(baseUrl: "https://jsonplaceholder.typicode.com/")
abstract class ApiService {
  factory ApiService(Dio dio, {String baseUrl}) = _ApiService;
  final Map<String, dynamic> value;
  static ApiService create() {
    final dio = Dio();
    return ApiService(dio);
  }


  @Headers(<String, String>{"accept": "image/jpeg"})
  @POST("posts")
  Future<output22> getTasks(@Body() Input22 aaa);

}
```

**Desktop**
 - OS: Linux
 - Browser Chorme
 - Version 84

**Smartphone**
 - Device: Huawei ascend p7
 - OS: Android 5.1
 - Browser Chrome
 - Version 84

**Comment by kamilpowalowski** [comment]
@mbfakourii how did you fix that?

**Comment by nEdAy** [comment]
Annotation must be either a const variable reference or const constructor invocation. (Documentation) 
The name 'Headers' is defined in the libraries 'package:dio/src/headers.dart (via package:dio/dio.dart)' and 'package:retrofit/http.dart (via package:retrofit/retrofit.dart)'. (Documentation)  Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.
