### ISSUE TITLE
Concrete member variables in abstract retrofit class aren't implemented in code generator

### ISSUE THREAD

**Issue by parkgrrr** [trevorwang/retrofit.dart#238]
**Describe the bug**
If I try to add any member variable to my retrofit abstract class, then generate the implementation, I get this error:

Missing concrete implementations of 'getter NetworkServices.prefs' and 'setter NetworkServices.prefs'.

I can add the implementations manually and I believe it works, why doesn't the code generator do this for me?

**To Reproduce**
1. Create a abstract retrofit class like normal
2. add a concrete member variable
3. Run code gen for retrofit

**Expected behavior**
The concrete variable would work in the generated class, will all code added

**Desktop (please complete the following information):**
 - OS: Android Studio Mac OS

**Additional context**
It looks like in dart using implements instead of extends doesn't inherit any concrete variable. Is there a workaround or any plans to support concrete members in the future without having to modify generated code?

**Comment by ipcjs** [comment]
I currently bypass this restriction by inheriting the generated classes.

```
@RestApi(baseUrl: IHealthService.baseUrl)
abstract class IHealthService {
  static const baseUrl = 'http://xxx/';

  @POST('login/')
  Future<LoginResult> login(
    @Field('email') String name,
    @Field() String password,
  );
}

class HealthService extends _IHealthService {
  HealthService(Dio dio) : super(dio);

  void myMethod(){
    // pass
  }
}
```

Or you can use extension methods, see: https://github.com/trevorwang/retrofit.dart/issues/12#issuecomment-685281766
