### ISSUE TITLE
Add staitc HTTP Queries

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [trevorwang/retrofit.dart#239]
I need to add static queries to an api just like the static http headers
```dart
  @GET("/tasks")
  @Headers(<String, dynamic>{
      "Content-Type" : "application/json",
      "Custom-Header" : "Your header"
  })
  Future<Task> getTasks();
```

**Comment by ipcjs** [comment]
What is your question?

**Comment by ipcjs** [comment]
You can use interceptors to achieve this functionality.
see: https://github.com/flutterchina/dio#interceptors

**Comment by trevorwang** [comment]
https://github.com/trevorwang/retrofit.dart/blob/eafa30ee0cf6dcd8a6866a5db5da3e034d0becfd/example/lib/example.dart#L43

**Comment by AlaaEldeenYsr** [comment]
@ipcjs 
> You can use interceptors to achieve this functionality.

Actually i wanna achieve this on a specific api between the whole apis, And the interceptor fires with every request, And i have to make a check to the specific api url to target that one only, That leads to firing the checking with every request, I just wanna add those static queries to that only api in that syntax
```dart
  @Headers(<String, dynamic>{
      "Content-Type" : "application/json",
      "Custom-Header" : "Your header"
  })
```
But Queries instead of the Headers, It would be great if you kindly add that annotation for the Queries, Thank you.

**Comment by ipcjs** [comment]
If there is only one api that needs to add static query parameters, you should probably add a custom method.

```dart
@RestApi(baseUrl: 'zzz')
abstract class IHealthService {
  @GET('path')
  Future<void> getCodeImpl({
    @Query('email') String email,
    @Query('phone') String phone,
  });
}

/// @see https://github.com/trevorwang/retrofit.dart/issues/12
/// @see https://github.com/trevorwang/retrofit.dart/issues/238
class HealthService extends _IHealthService {
  HealthService(Dio dio) : super(dio);
  
  Future<AccountBean> getCode() async {
    return getCodeImpl(email: 'xxx', phone: 'yyy');
  }
}

void main() async {
    final service = HealthService(dio);
    // to use
    final code = await service.getCode();
}

```

**Comment by TekExplorer** [comment]
this is still kind of a dumb way to do things. being able to statically set some query parameters for some routes - interceptors are really bad at handling that sort of thing - would be pretty convenient. i cant always control the api, and i dont like to make workarounds when it really shouldnt be that hard
