### ISSUE TITLE
How to separate HttpRequests from RestClient

### ISSUE THREAD

**Issue by themadmrj** [trevorwang/retrofit.dart#247]
I would like to move the requests (e.g.)
```
  @GET("/tasks")
  Future<List<Task>> getTasks();
```
Out of the RestClient, into another .dart file but couldn' find any example as to how to proceed. Could you please indicate how? I have no structure if I have to put 400 httpRequests into the same file.

**Comment by trevorwang** [comment]
You can move it in any dart file. but you have to put there function in a class with annotation `@RestApi`

**Comment by PalakSDarji** [comment]
This is what I am facing. Did you get any solution?

**Comment by trevorwang** [comment]
You can put the function in any dart file.  RestClient is just an example.
