### ISSUE TITLE
Unable to get status code for a request

### ISSUE THREAD

**Issue by nirjanmunshi** [trevorwang/retrofit.dart#248]
I have created a model class and configured the basic structure of retrofit client

```
@RestApi(baseUrl: "https://baseurl.in/")
abstract class RetrofitService {
  factory RetrofitService(Dio dio, {String baseUrl}) = _RetrofitService;

  static RetrofitService create() {
    final dio = Dio();
    dio.interceptors.add(PrettyDioLogger());
    return RetrofitService(dio);
  }

  @GET("api/getConfiguration")
  Future<Config> getConfiguration();

}

```

Since I am getting `Future<Config>` in return so I have created a class to get this data.

```
  Future<Config> getConfiguration() {
    return _client.getConfiguration();
  }
```

but the problem arises when I am calling this method from `main()`. API returns the data successfully but I am unable to find any status code for the request.
I found if I include `Future<Response<Config>>` as a return type for the above mention function then it returns a response code but then the generated code by retrofit showing an error
```
@override
  getConfiguration() async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final Response<Map<String, dynamic>> _result = await _dio.request(
        'api/easha/getConfiguration',
        queryParameters: queryParameters,
        options: RequestOptions(
            method: 'GET',
            headers: <String, dynamic>{},
            extra: _extra,
            baseUrl: baseUrl),
        data: _data);

    // ERROR: Response<Config>.fromJson is not working here. which is logical
    final value = Response<Config>.fromJson(_result.data);
    return value;
  }
```
How to fix this issue?

**Comment by trevorwang** [comment]
try this  https://github.com/trevorwang/retrofit.dart#get-orignal-http-reponse

**Comment by nirjanmunshi** [comment]
Ya alreadt stared the repo and, I saw that. That is OK. but it captures the status code on the catchError block. I want to get the status code after something like this
```
if(response.statuscode == 200){
 // do 200 work
} else {
// do other work
}
```

**Comment by trevorwang** [comment]
This library depends on dio which throws non 200 response as an error.   
Currently, you have to follow this
