### ISSUE TITLE
Failing generating code

### ISSUE THREAD

**Issue by Katekko** [trevorwang/retrofit.dart#250]
**Describe the bug**
I'm trying to generate the code from readme and I'm getting error

**To Reproduce**
Just execute the command to generate:
flutter packages pub run build_runner build --delete-conflicting-outputs

**Expected behavior**
Need to create a generated file

**Screenshots**
<img width="712" alt="Captura de Tela 2020-09-28 às 15 09 45" src="https://user-images.githubusercontent.com/13632735/94469554-b2ba1e80-019c-11eb-8eec-cfdb3b6401a3.png">

**Desktop (please complete the following information):**
 - OS: MacBook Pro 2015

**Additional context**
My pubspec
```
name: arctekko
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  get: ^3.11.1
  dio: ^3.0.10
  logger: ^0.9.2
  get_storage: ^1.3.1
  hive: ^1.4.4
  darq: ^0.4.0+1
  retrofit: ^1.3.4

  dropdown_search: ^0.4.4

dependency_overrides:
  analyzer: ">=0.39.11 <0.41.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.3
  json_serializable: ^3.5.0
  retrofit_generator: ^1.3.8+1
  hive_generator: ^0.7.2+1

flutter:
  uses-material-design: true
```

My flutter doctor

<img width="662" alt="Captura de Tela 2020-09-28 às 15 13 51" src="https://user-images.githubusercontent.com/13632735/94469928-468bea80-019d-11eb-9ba7-b61eea751443.png">

**Comment by DmitryVoronko** [comment]
The same issue. No star marks in source code

**console outputs**

```console
[INFO] Generating build script...
[INFO] Generating build script completed, took 379ms

[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 12.1s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 632ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[INFO] Generating SDK summary...
[INFO] 3.5s elapsed, 0/4 actions completed.
[INFO] Generating SDK summary completed, took 3.5s

[INFO] 5.1s elapsed, 3/4 actions completed.
[SEVERE] retrofit_generator:retrofit on bin/auth_api_service.dart:

Could not format because the source could not be parsed:

line 14, column 32: Expected an identifier.
   ╷
14 │ final value = LoginResponseDto*.fromJson(_result.data);
   │                                ^
   ╵
[INFO] Running build completed, took 5.3s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 38ms

[SEVERE] Failed after 5.4s
pub finished with exit code 1
```

**source code**

```dart
  factory LoginResponseDto.fromJson(Map<String, dynamic> json) =>
      _$LoginResponseDtoFromJson(json);
```

**pubspec**


```yaml
environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  dio: 3.0.10
  json_annotation: 3.1.0
  json_serializable: 3.5.0
  retrofit: 1.3.4

dependency_overrides:
  analyzer: ">=0.39.11 <0.41.0"

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  retrofit_generator: 1.3.8
  build_runner: 1.10.3
```

**Comment by Katekko** [comment]
> <img alt="94469554-b2ba1e80-019c-11eb-8eec-cfdb3b6401a3" width="712" src="https://user-images.githubusercontent.com/121966/94708732-7db5f380-0377-11eb-94b4-d234537070f0.png">
> 
> Here's a star mark. Could you check your source code?

There is no start mark in my source code.

Try to use the last version of build runner, I'm guessing that is the problem.

But to use dart 2.10 we need to use build_runner at least 1.10.2

**Comment by Katekko** [comment]
I double checked now, the problem is in build_runner 1.10.3

**Comment by DmitryVoronko** [comment]
It seems that problem comes from ```analyzer```. I tried to update it to ```0.40.4``` for retrofit generator and run tests. A lot of tests failed and ```GenericCast``` test too.

**GenericCast test output**
```console

Could not format because the source could not be parsed:

line 12, column 20: Expected an identifier.
   ╷
12 │ final value = User*.fromJson(_result.data);
   │                    ^
   ╵

package:dart_style/src/dart_formatter.dart 142:7                DartFormatter.formatSource
package:dart_style/src/dart_formatter.dart 74:12                DartFormatter.format
package:retrofit_generator/src/generator.dart 93:28             RetrofitGenerator._implementClass
package:retrofit_generator/src/generator.dart 62:12             RetrofitGenerator.generateForAnnotatedElement
package:source_gen_test/src/generate_for_element.dart 85:8      generateForElement
package:source_gen_test/src/test_annotated_classes.dart 227:7   _AnnotatedTest._generate
package:source_gen_test/src/test_annotated_classes.dart 230:26  _AnnotatedTest._shouldGenerateTest

```

I investigated a little. It seems that star mark comes from https://pub.dev/documentation/analyzer/latest/dart_element_nullability_suffix/NullabilitySuffix-class.html

**Comment by Katekko** [comment]
I'm forcing my analyzer be: 

analyzer: ^0.39.16

and my build runner:

build_runner: ^1.10.1

It's working for now...

My flutter version is: 1.22.0-12.0.pre

**Comment by trevorwang** [comment]
Please use the method mentioned by @Katekko as a workaround first.

Further investigation is needed.

**Comment by vanlooverenkoen** [comment]
@trevorwang I had the same problem with my Kiwi generator.

https://github.com/vanlooverenkoen/kiwi/issues/49 

Because my kiwi generator does not yet support nullability I disabled the `withNullabilityFlag`
https://github.com/vanlooverenkoen/kiwi/pull/52/files#diff-79ef6cd752af7079f4a73856231c222d

Maybe you can take a look at this. And create a seperate nullability release? (That is what I will do with the kiwi generator)

**Comment by vanlooverenkoen** [comment]
Starting from 0.40.1 `ElementImpl.toString() uses getDisplayString(withNullability: true).`And this is causing the * & ? symbols

**Comment by trevorwang** [comment]
Thanks, @vanlooverenkoen   just  restricted  the analyzer dependency to 0.39

**Comment by trevorwang** [comment]
#252
