### ISSUE TITLE
retrofit generator incompatible with build runner 1.10.3: version solving failed

### ISSUE THREAD

**Issue by bar4488** [trevorwang/retrofit.dart#252]
when running pub get with retrofit generator and build runner, some versions are colliding.
these are the versions i have:
retrofit: ^1.3.4
retrofit_generator: ^1.3.8+2
build_runner: ^1.10.3

this is the error:
```
Because build_runner >=1.10.3 depends on build_resolvers ^1.4.0 which depends on analyzer ^0.40.1, build_runner >=1.10.3 requires analyzer ^0.40.1.

And because retrofit_generator 1.3.8+2 depends on analyzer <=0.39.17 and no versions of retrofit_generator match >1.3.8+2 <2.0.0, build_runner >=1.10.3 is incompatible with retrofit_generator ^1.3.8+2.
```

**Comment by trevorwang** [comment]
Please use a lower version of build_runner

**Comment by bar4488** [comment]
With version 1.10.2 of build runner im not encountering the issue anymore. 
Although it is still undesirable that this package does not work with the latest build runner version. Is there a reason for not upgrade to analyzer ^0.40.x?

**Comment by trevorwang** [comment]
The latest build_runner support nullability which retrofit doesn't support

**Comment by akshaybhange** [comment]
In my case, I had to lower down the version of 2 dependencies. Please add support for analyzer 0.40.0.

**Comment by bar4488** [comment]
`hive_generateor` is also not compatible with retrofit generator. This is really bothering.

**Comment by trevorwang** [comment]
#259  is under development
