### ISSUE TITLE
Code generation error

### ISSUE THREAD

**Issue by TheMisir** [trevorwang/retrofit.dart#256]
**Describe the bug**
Whenever I try generating retrofit code I get this error. My colleague also reported same issue. I think this happened after major flutter upgrade which is related to null safety stuff.

**Dependencies**
```yaml
dev_dependencies:
  retrofit_generator: any
  build_runner: ^1.10.0
```

**Error message**
```
[SEVERE] retrofit_generator:retrofit on lib/data/services/api/my_api.dart:

Could not format because the source could not be parsed:

line 20, column 23: Expected an identifier.
   ╷
20 │ final value = Address*.fromJson(_result.data);
   │  
```

**Stack trace**
```
package:dart_style/src/dart_formatter.dart 142:7                        DartFormatter.formatSource
package:dart_style/src/dart_formatter.dart 74:12                        DartFormatter.format
package:retrofit_generator/src/generator.dart 85:32                     RetrofitGenerator._implementClass
package:retrofit_generator/src/generator.dart 61:12                     RetrofitGenerator.generateForAnnotatedElement
package:source_gen/src/generator_for_annotation.dart 53:30              GeneratorForAnnotation.generate
```

**Comment by TheMisir** [comment]
I checked `pubspec.lock` that I'm currently using latest version of retrofit which is v1.3.4+1.

**Comment by JeetTechie** [comment]
Cannot populate the required constructor argument: dio.
package:help/network/RestClient.dart:17:11
   ╷
17 │   factory RestClient(Dio dio,  {String baseUrl}) = _RestClient;
   │           ^
   ╵
[SEVERE] retrofit_generator:retrofit on lib/network/RestClient.dart (cached):

Could not format because the source could not be parsed:

line 42, column 25: Expected an identifier.
   ╷
42 │ final value = UserModel*.fromJson(_result.data);
   │                         ^
   ╵
line 22, column 27: Expected an identifier.
   ╷
22 │ final value = CommonModel*.fromJson(_result.data);

**Comment by trevorwang** [comment]
Please use the lower build_runner.   nullability is not supported yet.

**Comment by trevorwang** [comment]
duplicate to #252

**Comment by TheMisir** [comment]
> Please use the lower build_runner. nullability is not supported yet.

Which version would you suggest?

**Comment by trevorwang** [comment]
Actually, I have tried with build_runner 1.10.2. It seems to work well.   Did you use the latest dart?

```
  analyzer 0.39.17 (0.40.4 available)
  args 1.6.0
  async 2.4.2
  boolean_selector 2.0.0
  build 1.3.0 (1.5.0 available)
  build_config 0.4.2
  build_daemon 2.1.4
  build_resolvers 1.3.11 (1.4.1 available)
  build_runner 1.10.2 (1.10.3 available)
  build_runner_core 6.0.1 (6.0.3 available)
  built_collection 4.3.2
  built_value 7.1.0
```

```
Dart SDK version: 2.10.0 (stable) (Mon Sep 28 09:21:23 2020 +0200) on "macos_x64"
```

**Comment by TheMisir** [comment]
> Please check whether the version of `analyzer` is greater that 0.39.17 or not

`analyzer` version is 0.40.4. I think lowering the version would work but then other generators fails to build.

**Comment by trevorwang** [comment]
Currently, I don't have much time in this library.  PR is very appreciated if you could work on this.

**Comment by TheMisir** [comment]
> Currently, I don't have much time in this library.  PR is very appreciated if you could work on this. 

Actually yesterday I tried to fix but unfortunately didn't found anything related to error message. Do you have any idea why this is happening? I mean do you know which part of the code should be patched? I will create PR if I found the cause.

**Comment by trevorwang** [comment]
> > Currently, I don't have much time in this library.  PR is very appreciated if you could work on this.
> 
> Actually yesterday I tried to fix but unfortunately didn't found anything related to error message. Do you have any idea why this is happening? I mean do you know which part of the code should be patched? I will create PR if I found the cause.


Please refer https://github.com/trevorwang/retrofit.dart/issues/250#issuecomment-702611390

**Comment by TheMisir** [comment]
Ok I think I fixed it. I also had faced with same issue with `hive_generator`.

**Comment by TheMisir** [comment]
Should I set analyzer minimum version to 0.40.0? Because `withNullability` argument is not available in previous versions.

![image](https://user-images.githubusercontent.com/29130291/95729633-350f0c00-0c8e-11eb-8e0e-26ef552db739.png)
