### ISSUE TITLE
Cannot populate the required constructor argument: dio.

### ISSUE THREAD

**Issue by JeetTechie** [trevorwang/retrofit.dart#257]
Cannot populate the required constructor argument: dio.
package:help/network/RestClient.dart:17:11
   ╷
17 │   factory RestClient(Dio dio,  {String baseUrl}) = _RestClient;
   │           ^
   ╵
[SEVERE] retrofit_generator:retrofit on lib/network/RestClient.dart (cached):

Could not format because the source could not be parsed:

line 42, column 25: Expected an identifier.
   ╷
42 │ final value = UserModel*.fromJson(_result.data);
   │                         ^
   ╵
line 22, column 27: Expected an identifier.
   ╷
22 │ final value = CommonModel*.fromJson(_result.data);

**Comment by trevorwang** [comment]
duplicate to #252
