### ISSUE TITLE
Nested List<List<T>> is not supported by retrofit.

### ISSUE THREAD

**Issue by TheMisir** [trevorwang/retrofit.dart#262]
**Is your feature request related to a problem? Please describe.**
When I try to generate rest client for given request I get wrong code generated.

```dart
@GET('/redacted/{id}/redacted')
Future<List<List<Window>>> getDeliveryWindows(@Path('id') int id);
```

The generated code tries that:

```dart
data.map((dynamic i) => List<Window>.fromJson(i as Map<String, dynamic>))
```

Which is not possible.

**Describe alternatives you've considered**
I'm currently manually modifying generated code to support nested lists.

**Additional context**
I would create PR but I will need a bit help to know which part of the code is responsible for that part.

**Comment by trevorwang** [comment]
Below is the code to get the response type. You can dig deeper from here.

https://github.com/trevorwang/retrofit.dart/blob/67cf54f5b56582129488eed58123f159e0c0aecd/generator/lib/src/generator.dart#L255

**Comment by TheMisir** [comment]
> Below is the code to get the response type. You can dig deeper from here.
> 
> https://github.com/trevorwang/retrofit.dart/blob/67cf54f5b56582129488eed58123f159e0c0aecd/generator/lib/src/generator.dart#L255

I'll work on this issue when I got free time.

**Comment by TarekkMA** [comment]
Any update on this issue?
