### ISSUE TITLE
Unable to send file using Flutter Web

### ISSUE THREAD

**Issue by houdayec** [trevorwang/retrofit.dart#273]
**Describe the bug**
I am trying to upload a file (import from dart:io package). However on Flutter Web, dart:io is not available.

I'm getting the following error:

Multipart is only supported where dart.io is available.

Here is my method:

`@POST("/files")
  Future<WhateverModel> submitFile(
    @Part() File file,
    @Part() WhateverModel model,
  );
`

**Expected behavior**
Upload a file using dart:html?

How can I send a file using retrofit on Flutter Web?

**Comment by trevorwang** [comment]
Please provide more error details

**Comment by MysticalNobody** [comment]
> **Describe the bug**
> I am trying to upload a file (import from dart:io package). However on Flutter Web, dart:io is not available.
> 
> I'm getting the following error:
> 
> Multipart is only supported where dart.io is available.
> 
> Here is my method:
> 
> `@POST("/files") Future<WhateverModel> submitFile( @Part() File file, @Part() WhateverModel model, ); `
> 
> **Expected behavior**
> Upload a file using dart:html?
> 
> How can I send a file using retrofit on Flutter Web?

It's not a retrofit problem. 
In Web, we don't have access to file, because we have only a relative path.
But we can retrieve multipart file from bytes and retrofit supports it.

**For example:**
Generate a request like this:
```
  @POST("/media/upload")
  Future<void> uploadPhotos(@Part() List<int> file);
```
And use it:
```
/// Get image
final image = await ImagePicker.platform.pickImage(source: ImageSource.gallery);
/// Get bytes and convert in to List<int>
List<int> bytes = (await image.readAsBytes()).toList();
/// Send multipart
await RestClient.instance.uploadPhotos(bytes);
```

**Comment by houdayec** [comment]
> > **Describe the bug**
> > I am trying to upload a file (import from dart:io package). However on Flutter Web, dart:io is not available.
> > I'm getting the following error:
> > Multipart is only supported where dart.io is available.
> > Here is my method:
> > `@POST("/files") Future<WhateverModel> submitFile( @Part() File file, @Part() WhateverModel model, ); `
> > **Expected behavior**
> > Upload a file using dart:html?
> > How can I send a file using retrofit on Flutter Web?
> 
> It's not a retrofit problem.
> In Web, we don't have access to file, because we have only a relative path.
> But we can retrieve multipart file from bytes and retrofit supports it.
> 
> **For example:**
> Generate a request like this:
> 
> ```
>   @POST("/media/upload")
>   Future<void> uploadMedia(@Part() List<int> file);
> ```
> 
> And use it:
> 
> ```
> /// Get image
> final image = await ImagePicker.platform.pickImage(source: ImageSource.gallery);
> /// Get bytes and convert in to List<int>
> List<int> bytes = (await image.readAsBytes()).toList();
> /// Send multipart
> await RestClient.instance.uploadMedia(bytes);
> ```

Perfectly working, thank you very much. Sorry for late reply.
