### ISSUE TITLE
@Body() List<T> converting object to an encodable object failed

### ISSUE THREAD

**Issue by lyqiai** [trevorwang/retrofit.dart#274]
@POST('/manager/bookTableSetting/add')
 Future addBookTableSetting(@Body() List<BookingTableSetting> data);

@JsonSerializable()
class BookingTableSetting extends Object {

  static const APPLET_STATUS_ON = 'on';
  static const APPLET_STATUS_OFF = 'off';

  static const APP_STATUS_OFF = 'off';
  static const APP_STATUS_ON = 'on';

  static const USE_STATUS_ON = 'on';
  static const USE_STATUS_OFF = 'off';

  static const TABLE_TYPE_HALL = 'hall';
  static const TABLE_TYPE_ROOM = 'room';

  @JsonKey(name: 'storeId')
  int storeId;

  @JsonKey(name: 'tableId')
  int tableId;

  @JsonKey(name: 'tableName')
  String tableName;

  @JsonKey(name: 'minPersonNum')
  int minPersonNum;

  @JsonKey(name: 'maxPersonNum')
  int maxPersonNum;

  @JsonKey(name: 'tableType')
  String tableType;

  @JsonKey(name: 'usingStatus')
  String usingStatus;

  @JsonKey(name: 'appUsingStatus')
  String appUsingStatus;

  @JsonKey(name: 'appletUsingStatus')
  String appletUsingStatus;

  @JsonKey(name: 'areaId')
  int areaId;

  @JsonKey(name: 'areaName')
  String areaName;

  @JsonKey(name: 'storeName')
  String storeName;

  @JsonKey(name: 'maxPerson')
  int maxPerson;

  BookingTableSetting(this.storeId,this.tableId,this.minPersonNum,this.maxPersonNum,this.tableType,this.usingStatus,this.appUsingStatus,this.appletUsingStatus,this.areaId,this.areaName,this.storeName,this.maxPerson,);

  factory BookingTableSetting.fromJson(Map<String, dynamic> srcJson) => _$BookingTableSettingFromJson(srcJson);

  Map<String, dynamic> toJson() => _$BookingTableSettingToJson(this);

}

log error:
I/flutter (25202): DioError [DioErrorType.DEFAULT]: Converting object to an encodable object failed: Instance of 'MappedListIterable<BookingTableSetting, Map<String, dynamic>>'
I/flutter (25202): #0      _JsonStringifier.writeObject (dart:convert/json.dart:687:7)
I/flutter (25202): #1      _JsonStringStringifier.printOn (dart:convert/json.dart:876:17)
I/flutter (25202): #2      _JsonStringStringifier.stringify (dart:convert/json.dart:861:5)
I/flutter (25202): #3      JsonEncoder.convert (dart:convert/json.dart:261:30)
I/flutter (25202): #4      JsonCodec.encode (dart:convert/json.dart:171:45)
I/flutter (25202): #5      DefaultTransformer.transformRequest (package:dio/src/transformer.dart:61:21)
I/flutter (25202): #6      DioMixin._transformData (package:dio/src/dio.dart:1011:39)
I/flutter (25202): #7      DioMixin._dispatchRequest (package:dio/src/dio.dart:918:26)
I/flutter (25202): #8      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:849:37)
I/flutter (25202): #9      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1118:22)
I/flutter (25202): #10     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio

retrofit_generator: 1.4.0+1
retrofit: 1.3.4+1

**Comment by lyqiai** [comment]
dio transfomer Iterator to List can fix this issue.
fix code:
class IteratorInterceptor extends InterceptorsWrapper {
  @override
  Future onRequest(RequestOptions options) {
    if (options.data is Iterable) {
      options.data = options.data.toList();
    }
    return super.onRequest(options);
  }
}
or retrofit_generator code out put:
@override
  Future<dynamic> addBookTableSetting(data) async {
    ArgumentError.checkNotNull(data, 'data');
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _data = data.map((e) => e.toJson()).toList(); //fix code
    final _result = await _dio.request('/manager/bookTableSetting/add',
        queryParameters: queryParameters,
        options: RequestOptions(
            method: 'POST',
            headers: <String, dynamic>{},
            extra: _extra,
            baseUrl: baseUrl),
        data: _data);
    final value = _result.data;
    return value;
  }

**Comment by trevorwang** [comment]
Could you please submit a PR?

**Comment by wonpyohong** [comment]
Thanks. It works well. 
I dont know exactly why my code breaks suddenly (retrofit chamge? Or Dio?)
Anyway it works.

**Comment by lyqiai** [comment]
@trevorwang pr #280
