### ISSUE TITLE
Retrofit isn't working with Generic Type

### ISSUE THREAD

**Issue by alexaf2000** [trevorwang/retrofit.dart#275]
**Describe the bug**
When you have defined a Generic Type nested inside a Class using Json Serializer Retrofit fails.

This issue is coming because in one request I have a pagination, that means that I automatically get this request:

`{
    "current_page": 1,
    "data": [
        {
            "id": 2,
            "customer_id": 5,
            "name": "Ciudad de vaticano",
            "short_description": "Uno de los puntos más importantes de la ciudad y en los que podrás disfrutar de gran entretenimiento y tareas por hacer con la familia.",
            "long_description": "Esta es una descripción más larga del lugar del cual estaríamos hablando, que cuenta con una descripción algo más larga de lo normal y con espacios especialmente fantasticos para disfrutar con la familia.\r\n\r\nEn la época del renacimiento también fue conocido por ser tal.",
            "province": "Test",
            "postal_code": "43850",
            "address": "Passeig de les Palmeres, Cambrils, España",
            "latitude": 41.0654147,
            "longitude": 1.0611896,
            "active": 1,
            "access": 0,
            "link": "https://www.colon.org/fuga-placeat-distinctio-quia-illum-consectetur-adipisci-quod",
            "image": null,
            "video": null,
            "created_at": "2020-03-27 16:17:04",
            "updated_at": "2020-11-07 14:34:46",
            "image_url": null
        }
    ],
    "first_page_url": "https://website.test/api/cities?page=1",
    "from": 1,
    "last_page": 1,
    "last_page_url": "https://website.test/api/cities?page=1",
    "next_page_url": null,
    "path": "https://website.test/api/cities",
    "per_page": 10,
    "prev_page_url": null,
    "to": 1,
    "total": 1
}`

What I have are two classes then: Pagination and City.

**Pagination class:**

```
`import 'package:json_annotation/json_annotation.dart';

part 'pagination.g.dart';

@JsonSerializable(genericArgumentFactories: true)
class Pagination<T> {
  @JsonKey(name: "current_page")
  int currentPage;
  @JsonKey(name: "last_page")
  int lastPage;
  @JsonKey(name: "per_page")
  int perPage;

  List<T> data;

  Pagination(this.currentPage, this.lastPage, this.perPage, this.data);

  factory Pagination.fromJson(
          Map<String, dynamic> json,T Function(Object json) fromJsonT) =>
      _$PaginationFromJson<T>(json,fromJsonT);

  Map<String, dynamic> toJson(Object Function(T value) toJsonT) => _$PaginationToJson(this,toJsonT);
}
`
```
**What I'm getting is an error because retrofit automatically generates the "fromJson" method with just one parameter, but JsonSerializable expects to use 2 when using the new "genericArgumentFactories".**

This is what I wrote in my retrofit file:
```

  @GET("/audiopoints")
  Future<Pagination<City>> getCities(
      @Query("page") int page
  );

```

**Comment by hoanganhtran1010** [comment]
Anyone has answers?

**Comment by alexaf2000** [comment]
> Does anyone has answers?

I think that maybe has to be implemented as a new feature :(

**Comment by OysterQAQ** [comment]
same problem

**Comment by JenkinChen** [comment]
same problem

**Comment by subzero911** [comment]
+1 for generic types support

JsonSerializable supports T since 3.5.0
Retrofit currently generates `final value = Response<User>.fromJson(_result.data);`, omitting the 2nd parameter `fromJsonT`.

**Comment by trevorwang** [comment]
I don't have much time working on this.   

PRs are appreciated here.

**Comment by mumairofficial** [comment]
Same issue with `retrofit: ^4.0.1` latest Aug 5, 2023
