### ISSUE TITLE
Add and update Auth header

### ISSUE THREAD

**Issue by MotiBartov** [trevorwang/retrofit.dart#277]
Hi, 

Is it possible to add and update the AuthHeader after the client has been created?
Is there any access to dio from the the RestClient? 

Thanks for your support,
Moti.

**Comment by alexaf2000** [comment]
> Hi,
> 
> Is it possible to add and update the AuthHeader after the client has been created?
> Is there any access to dio from the the RestClient?
> 
> Thanks for your support,
> Moti.

If you want to use an Authentication header after a user has logged in, I usually set it manually in every request where I need it a @Header called token, and parse it as a parameter of the request.

If your application doesn't require a user authentication, just an API authentication you can generate a Dio Interceptor where if you detect that you don't have a token or if is expired generates another one.

I don't know if there is another way to do it, but I think that's the best.
