### ISSUE TITLE
Authorization problem only on Safari (Flutter Web)

### ISSUE THREAD

**Issue by qbait** [trevorwang/retrofit.dart#279]
My app is making a `GET` request with `Authorization` header

```
  @GET("/presentation/")
  Future<String> presentation(@Header("Authorization") String auth);
```
I'm calling request like:
```
      final dio = Dio(); // Provide a dio instance
      final client = RestClient(dio);

      final response = await client.presentation("Token hiden402a108784a3f67017ae9f5b64349ceba5");
```

It correctly works on:
- Chrome
- Firefox
- Edge
- mobile apps
- MacOS app

However, on Safari I'm getting 401 Unauthorised.

I know that an issue is in `Retrofit` because it works without a problem when I'm using `Dio` without `Retrofit` like

```
      Response response = await Dio().get(
        "https://api.pickle.care/api/presentation/",
        options: Options(
          headers: {
            'Authorization': "Token hiden402a108784a3f67017ae9f5b64349ceba5", // set content-length
          },
        ),
      );
```

Here is the screenshot from Safari Network Debugger
<img width="1280" alt="Screenshot 2020-11-17 at 15 50 04" src="https://user-images.githubusercontent.com/2264901/99451837-17833100-2923-11eb-9ba5-940139815e3c.png">

[EDIT]
That's how Safari Network Debugger looks like when there is a correct request from Dio:
<img width="748" alt="Screenshot 2020-11-17 at 22 32 08" src="https://user-images.githubusercontent.com/2264901/99453276-03403380-2925-11eb-81d1-00f255c926be.png">

I also found this thread:
https://stackoverflow.com/questions/50515514/receiving-401-status-with-safari-not-chrome-in-react

**Comment by qbait** [comment]
I found the exact problem.
`retrofit_generator` cuts the last `/`. When I put manually `/presentation/` instead of `/presentation` in my `api.g.dart`, it works as expected on Safari. Please don't cut the last `/`.

**Comment by alexaf2000** [comment]
The last `/` is required to not exists because the use of params on GET routes. 

For example: `https://website.com/presentation?search=th&date_start=02-02-1999`.

Maybe you need to improve your API and allow to not include the last `/`.

**Comment by qbait** [comment]
You are right, I fixed the issue.
