### ISSUE TITLE
Any documentation for generic support?

### ISSUE THREAD

**Issue by Auuufff** [trevorwang/retrofit.dart#285]
Will be nice to have some documentation for the generic support feature.

**Comment by mohn93** [comment]
Added here [289](https://github.com/trevorwang/retrofit.dart/pull/289), just waiting for the owner to merge

**Comment by fbertanha** [comment]
Hello friend, i've opened an issue with some examples. hope can help you https://github.com/trevorwang/retrofit.dart/issues/292

**Comment by sooxt98** [comment]
Hope it helps https://sooxt98.space/the-most-codeless-way-to-write-flutter-api/

**Comment by j05u3** [comment]
> the-most-codeless-way-to-write-flutter-api/

Hi, your link is not working anymore 😉

**Comment by trevorwang** [comment]
Please refer to https://github.com/google/json_serializable.dart/blob/master/example/lib/generic_response_class_example.dart
