### ISSUE TITLE
should return null if don't pass any generic types

### ISSUE THREAD

**Issue by TungPT95** [trevorwang/retrofit.dart#287]
here is a function in my service class

```
{
   ...
   
   @DELETE('customer/delete/{customerId}')
   Future<ResponseModel> deleteCustomer({@Path() int customerId});
   
   ...
}
```

my function is returning the `ResponseModel` with generic type

```
class ResponseModel<T> {
    bool status;
    Message message;
    T data;
    Error error;
    ...
}
```
sometime,`data` didn't return in the api's response, it's only `message` or `error` instead

so, i don't set type to `ResponseModel`, my `.g.dart` will be generated like this
```
  final value = ResponseModel<dynamic>.fromJson(
      _result.data,
      (json) => dynamic.fromJson(json),
    );
```

so, i aspect that it will be returned `null` if i didn't pass any specified types to `ResponseModel`

e.g:
```
  final value = ResponseModel<dynamic>.fromJson(
      _result.data,
      (json) => null,
    );
```

@trevorwang

**Comment by mohn93** [comment]
I think this is solved here [289](https://github.com/trevorwang/retrofit.dart/pull/289)

**Comment by mohn93** [comment]
@TungPT95  Could u please close this since it's solved
