### ISSUE TITLE
wrong type cast if i pass type as List<T>

### ISSUE THREAD

**Issue by TungPT95** [trevorwang/retrofit.dart#288]
this is my class using generic type

```
class ResponseModel<T> {
    bool status;
    Message message;
    T data;
    Error error;
    ...
}
```

my `data` is not only a single object but also is a `List<T>`

here is my `.g.dart` was generated 
```
...
    final value = ResponseModel<List<Campaign>>.fromJson(
        _result.data,
        (json) => (json as List<Campaign>) <== problem is here
            .map<Campaign>((i) => Campaign.fromJson(
                  i as Map<String, dynamic>,
                ))
            .toList());
...
```

i think ` (json as List<Campaign>)` should be `(json as List)`

@trevorwang

**Comment by Moujarkash** [comment]
any solution?

**Comment by TungPT95** [comment]
> any solution?

i think this issue is fixed in this PR https://github.com/trevorwang/retrofit.dart/pull/286, just follow it

**Comment by mohn93** [comment]
This is fixed in here [289](https://github.com/trevorwang/retrofit.dart/pull/289)

**Comment by TungPT95** [comment]
> This is fixed in here [289](https://github.com/trevorwang/retrofit.dart/pull/289)

i saw it, thanks @mohn93

**Comment by mohn93** [comment]
@TungPT95  Could u please close this since it's solved
