### ISSUE TITLE
Bean class support for @Body() annotation

### ISSUE THREAD

**Issue by seedinwind** [trevorwang/retrofit.dart#29]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by trevorwang** [comment]
Hi @seedinwind,

Currently you can use the`toJson()` method if you are using `JsonSerializable` plugin. 
You can refer the sample code [here](https://github.com/dart-lang/json_serializable/blob/5de34a43dfc59916812b8af45561be69f20c1882/example/lib/example.dart#L31)

**Comment by trevorwang** [comment]
@seedinwind  Please use generator v0.4.0
