### ISSUE TITLE
be able to use `genericArgumentFactories` as optional? instead of mandatory

### ISSUE THREAD

**Issue by tungpham6195** [trevorwang/retrofit.dart#291]
i had a class like this
```
@JsonSerializable(fieldRename: FieldRename.snake, explicitToJson: true)
class PageData<T> {
  factory PageData.fromJson(Map<String, dynamic> json) =>
      _$PageDataFromJson<T>(json);

  Map<String, dynamic> toJson() => _$PageDataToJson<T>(this);

   ...

  @MyConverter()
  List<T> items;
}
```

i don't use `genericArgumentFactories`, instead of that, i use `MyConverter` extend `JsonConverter` to handle converting

in this case, i don't want my `service.g.dart` generated with `genericArgumentFactories`

hope you understand this issue i'm facing @trevorwang @mohn93

**Comment by tungpham6195** [comment]
hi @trevorwang , @mohn93 do you guys have any solutions for this?

**Comment by Aqluse** [comment]
I suffer from this too

**Comment by rgushel** [comment]
very annoying issue

**Comment by mohn93** [comment]
Hey guys, Sorry for the delay, could you please test this branch [branch](https://github.com/mohn93/retrofit.dart/tree/fix_generic_argument_factories) I think I solved the problem there
Thanks in advance

**Comment by TungPT95** [comment]
> Hey guys
> Sorry for delay, could you please test this branch [fix_generic_argument_factories](https://github.com/mohn93/retrofit.dart/tree/fix_generic_argument_factories) I think I solved the problem there
> Thanks in advance
hope it will be merged soon @mohn93 🥳

@Aqluse , @rgushel you guys can try this branch first 😆

**Comment by tungpham6195** [comment]
> Hey guys
> Sorry for delay, could you please test this branch [fix_generic_argument_factories](https://github.com/mohn93/retrofit.dart/tree/fix_generic_argument_factories) I think I solved the problem there
> Thanks in advance

hope it will be merged soon @mohn93 🥳

@Aqluse , @rgushel you guys can try this branch first 😆

**Comment by mohn93** [comment]
> > Hey guys
> > Sorry for delay, could you please test this branch [fix_generic_argument_factories](https://github.com/mohn93/retrofit.dart/tree/fix_generic_argument_factories) I think I solved the problem there
> > Thanks in advance
> 
> hope it will be merged soon @mohn93 🥳
> 
> @Aqluse , @rgushel you guys can try this branch first 😆

Did you test it? , Does it work for you without problems?

**Comment by rgushel** [comment]
@mohn93 looks like your fix did the job. Nice!
