### ISSUE TITLE
an example for generic responses

### ISSUE THREAD

**Issue by fbertanha** [trevorwang/retrofit.dart#292]
Hello friends, i'm still confuse how to work with generic responses, i have already looked to all issues about 'generics' but nothing works. Can anyone have some examples? 

This is my base structure to all my responses, the T generic can be anything, a List, a Object..
```
class BaseResponse<T> {
  final String message;
  final T content;
  ...
}
```

This is a example for a response:

``` 
{
	"message": "Usuário autenticado com sucesso!",
	"content": {
		"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1N",
		"users": {
			"id": 3,
			"document": "xxxx",
			"fullName": "felipe bertanha",
	}
} 
```

thanks guys

**Comment by fbertanha** [comment]
Hello friends, after a long search, i figure out how make this works! here my samples:

**This is my base response**:

```
import 'package:json_annotation/json_annotation.dart';

part 'base_response.g.dart';

@JsonSerializable(genericArgumentFactories: true)
class BaseResponse<T> {
  final String message;
  final T content;

  BaseResponse({this.message, this.content});

  factory BaseResponse.fromJson(
          Map<String, dynamic> json, T Function(Object json) fromJsonT) =>
      _$BaseResponseFromJson(json, fromJsonT);

  Map<String, dynamic> toJson(Object Function(T value) toJsonT) =>
      _$BaseResponseToJson(this, toJsonT);
}
```

**Some response class that will be used with BaseResponse class**:
```
...
part 'auth_response.g.dart';

@JsonSerializable()
class AuthResponse {
  final String token;
  final UserResponse user;

  AuthResponse(this.token, this.user);

  factory AuthResponse.fromJson(Map<String, dynamic> json) {
    return _$AuthResponseFromJson(json);
  }

  Map<String, dynamic> toJson() => _$AuthResponseToJson(this);
}
```

**The json sample from the AuthReponse class above:**
```
{
	"message": "Usuário autenticado com sucesso!",
	"content": {
		"token": "eyJ0eXxxxx",
		"user": {
			"id": 3,
			"document": "0000",
			"fullName": "felipe bertanha",
			"email": "hide@nodomain.com",
			"phone": "11111111111",
			"type": "USER",
			"blocked": false
		}
	}
}
```

**That's the RestClient class that make de http call:**
```
...
@RestApi(baseUrl: kStg)
abstract class RestClient {
  factory RestClient(Dio dio, {String baseUrl}) = _RestClient;

  @POST("/auth")
  Future<BaseResponse<AuthResponse>> auth(@Body() AuthForm authForm);

}
```

links that helped me: 
https://github.com/google/json_serializable.dart/issues/759
https://github.com/google/json_serializable.dart/blob/master/example/lib/tuple_example.dart

**Comment by aryayudha** [comment]
Hi, how about your RestClient.g.dart class? i got some error on g.dart class.

**Comment by j05u3** [comment]
May I add one thing: you have to explicitly set `@JsonSerializable(genericArgumentFactories: true)` on the BaseResponse class as it won't pick it up from the build.yaml config (as in my screenshot below):

<img width="472" alt="image" src="https://user-images.githubusercontent.com/7897132/226988815-4c0f984d-6686-4eb7-a128-77630b5c936e.png">

✌️
