### ISSUE TITLE
Will retrofit support sockets at some point?

### ISSUE THREAD

**Issue by Turbozanik** [trevorwang/retrofit.dart#294]
**Is your feature request related to a problem? Please describe.**
I would like to have a socket connection support.

**Describe the solution you'd like**
We have @get, @post its annotations, we might implement it with the same approach by adding @socket annotation

**Describe alternatives you've considered**
Get lib has this feature, but its huge and it has all in one package, so I can't use it in a multi modular app, because my modules will have dependencies that are unrelated to  them at all.

**Additional context**
Nothing here I think.

**Comment by trevorwang** [comment]
Nope.   HTTP and sockets are different things.  The socket is out of the scope of what retrofit covers.
