### ISSUE TITLE
Pass URL to download file

### ISSUE THREAD

**Issue by qbait** [trevorwang/retrofit.dart#297]
I'm able to download `pdf` document using hardcoded string
  
```
  @GET('https://sample.com/sample.pdf')
  @DioResponseType(ResponseType.bytes)
  Future<List<int>> downloadSummaryPdf();
```
  
  However, I can't pass URL as a parameter. I've tried something like below, but without success
  
```
  @GET('{url}')
  @DioResponseType(ResponseType.bytes)
  Future<List<int>> downloadSummaryPdf(@Path() String url);
```

Can I achieve it somehow or that feature is missing?

**Comment by amebrahimi** [comment]
I need this too

**Comment by Caeruleo** [comment]
We did some "workarounds" like using 
@Post("$url")
Future<...> dowloadSomething(@Path() String url); and using an empty base url , 
or if you use a param called "baseUrl" on the method, the generated code will take that url : 
@Post("")
Future<...> downloadSomething(
String baseUrl,
...
)
Then if you look into the generated code : 
    final _result = await _dio.request<String>('',
        queryParameters: queryParameters,
        options: RequestOptions(
            method: 'POST',
            headers: <String, dynamic>{},
            extra: _extra,
            baseUrl: *baseUrl*), //This is the baseUrl you passed on the method as param
        data: _data);
    final value = _result.data;

**Comment by amebrahimi** [comment]
For now, I'm Using:
```
return _dio.download(
      '${InfrastructureConstants.BASE_URL_PLUGIN}/file',
      '$_path/${InfrastructureConstants.ZIP_FILE_NAME}',
      options: Options(
        method: 'POST',
        headers: {'Authorization': 'Bearer $token'},
      ),
      data: {
        'filename': InfrastructureConstants.ZIP_FILE_NAME,
      },
      // onReceiveProgress: _showDownloadProgress,
    );
```
