### ISSUE TITLE
Header doesn't accept null even though the docs say it does 

### ISSUE THREAD

**Issue by feinstein** [trevorwang/retrofit.dart#302]
The Header docs say "header parameters maybe null which will omit them from the request". But trying to pass a null header throws an exception by checkNotNull.

**Comment by feinstein** [comment]
This should be reviewed by someone before it's closed.

**Comment by paulVulog** [comment]
+1 
When we provide a null header, then an exception is fire in the generated code by the ArgumentError.checkNotNull check method and prevent the request to be sent.

it's against the documentation that notice :

/// Replaces the header with the value of its target.
///
/// Header parameters may be `null` which will omit them from the request.
@immutable
class Header {
 final String value;
 const Header(this.value);
}

**Comment by feinstein** [comment]
@paulVulog I don't remember seeing optional headers on the docs, how can I declare them?

**Comment by paulVulog** [comment]
@feinstein,   No I mean using optional parameters in dart : 

E.G : 

```java
  @GET("/myEndPoint")
  Future<MyData> getMyEndPoint(@Header("header-one") String headerOne, {@Header("header-two") String headerTwo});
```

Here, headerOne is mandatory (if you pass null, the request is not sent), and headerTwo is optional.  It looks like if you don't pass it (or pass null), the request is sent with null in the header.

**Comment by feinstein** [comment]
Oh, I see, interesting, thanks!

**Comment by nirbar89** [comment]
same here

**Comment by woprandi** [comment]
Fixed with https://github.com/trevorwang/retrofit.dart/pull/387

**Comment by woprandi** [comment]
@trevorwang it's fixed you can close it
