### ISSUE TITLE
Add mime type to file upload

### ISSUE THREAD

**Issue by Kimsoer** [trevorwang/retrofit.dart#303]
Hello team, I want to upload file with mime type, but I read your example , don't see it. Mime type is dynamic extension while upload

**Comment by trevorwang** [comment]
Does it meet your requirment?

```

  @POST("/post")
  Future<String> postFormData2(
      @Part() List<Map<String, dynamic>> task,
      @Part() List<String> tags,
      @Part(contentType: 'application/json') File file);
```

**Comment by Dakrain** [comment]
So if the File extension is dynamic? It could be "mp4", "png", "jpg", "video",... any kind of file. How can I resolve this?

**Comment by Kimsoer** [comment]
@POST("/post")
  Future<String> postFormData2(
      @Part() List<Map<String, dynamic>> task,
      @Part() List<String> tags,
      @Part(contentType:  'dynamic type file*') File file);

*I mean we want to dynamic file extension: 
- @Part(contentType:  'audio/aac') File file
- @Part(contentType:  'application/msword') File file
- @Part(contentType:  'text/html') File file
- @Part(contentType:  'video/mpeg') File file
- @Part(contentType:  'application/pdf') File file
- @Part(contentType:  'text/csv') File file

why i want like that because serverside they require mobile to pass it for them check file extension

**Comment by donpaul120** [comment]
The arguments should take something like a MultiPart file and necessary a file.. i think that's the issue with the design..

```
  @POST("/upload")
  Future<void> upload(@Part() MultipartFile? selfieImage);
  
  
 final file = await MultipartFile.fromFile(filePath, contentType:"dynamic type", fileName:"myPreferredName");
this._accountCreationService.upload(file);
```

This should be possible but i don't think it's currently possible!

**Comment by hermann-salto** [comment]
I have the problem, I need to specify mime type dynamically
