### ISSUE TITLE
Connection closed before full header was received

### ISSUE THREAD

**Issue by nirmalcirklestudio** [trevorwang/retrofit.dart#304]
DioError [DioErrorType.DEFAULT]: HttpException: Connection closed before full header was received, URI ="my URL
"
working on native android and ios app but not working with flutter

**Comment by trevorwang** [comment]
do you mean it didn't work for flutter web ?

**Comment by nirmalcirklestudio** [comment]
it's not working with both android and ios.

**Comment by trevorwang** [comment]
> it's not working with both android and ios.

Sample code please
