### ISSUE TITLE
How to indicate port

### ISSUE THREAD

**Issue by II11II** [trevorwang/retrofit.dart#307]
How to indicate port

**Comment by trevorwang** [comment]
Please explain more about the issue

**Comment by II11II** [comment]
I have url with port "htttp://payment.url.com:9999" and i need to do request to this url. So added port number to url and did request and this error:
DioError [DioErrorType.DEFAULT]: SocketException: OS Error: Operation timed out, errno = 60, address = pay.davrbank.uz, port = 61595 -> DioError 
But in http package it worked nice.

**Comment by alexaf2000** [comment]
Your url have an additional "t". Set "`http://payment.url.com:9999`" instead of "`htttp://payment.url.com:9999`".
