### ISSUE TITLE
Dynamically pass `fileName` to `@Part`

### ISSUE THREAD

**Issue by qbait** [trevorwang/retrofit.dart#308]
How to dynamically pass `fileName` as a parameter of function?
  Is there already a feature like that?
  
```
  @POST('import/file/')
  Future<void> importSpreadsheet(@Part(fileName: 'sheet.xlsx') List<int> file);
```

I would like to have sth like
```
  @POST('import/file/')
  Future<void> importSpreadsheet(@Part(fileName: {name}) List<int> file, String name);
```

**Comment by Kimsoer** [comment]
Do you get this solution yet? I have this issue too

**Comment by Kimsoer** [comment]
I meet that issue and I solve it by customize  generate function with manual :  
 _data.files.add(MapEntry(
          'file',
          MultipartFile.fromFileSync(file.path,
              filename: file.path.split(Platform.pathSeparator).last,
              contentType: MediaType.parse('$extension'))));

1. step :  Function
@POST("files")
  Future<CreateFileResponseEntity> uploadFile(
      {@Part() File file,
      String extension,
  });
2.  Generate Function : 

 @override
  Future<CreateFileResponseEntity> uploadFile(
      {file, extension}) async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    queryParameters.removeWhere((k, v) => v == null);
    final _data = FormData();
    if (file != null) {
      _data.files.add(MapEntry(
          'file',
          MultipartFile.fromFileSync(file.path,
              filename: file.path.split(Platform.pathSeparator).last,
              contentType: MediaType.parse('$extension'))));
    }

    final _result = await _dio.request<Map<String, dynamic>>('files',
        queryParameters: queryParameters,
        options: RequestOptions(
            method: 'POST',
            headers: <String, dynamic>{},
            extra: _extra,
            baseUrl: baseUrl),
        data: _data);
    final value = CreateFileResponseEntity().fromJson(_result.data);
    return value;
  }

**Comment by lvhuy1102** [comment]
i post file in postman ok when i using retrofit post file success but i can't have new change in profile 
![image](https://user-images.githubusercontent.com/34293410/120593944-60877680-c46a-11eb-891e-52690054f4b2.png)
![image](https://user-images.githubusercontent.com/34293410/120594138-b0663d80-c46a-11eb-858e-27635ad73a6d.png)

**Comment by Kimsoer** [comment]
is it already fixed?
