### ISSUE TITLE
Empty responses managment

### ISSUE THREAD

**Issue by vincentvulog** [trevorwang/retrofit.dart#310]
An http response with status code 204 can contain no payload at all, but it should'nt lead to a deserialization error

It should be possible to define an "empty" payload used in such a case to allow deserialization of the empty object.

**Comment by trevorwang** [comment]
try to use  `Future<void> ` as the reponse

**Comment by vincentvulog** [comment]
when the server reply with a 200 response, the body contains a payload that should be deserialized, therefore impossible to use Future<void>
The deserializes object, in my case, is a list of things...
An empty body response with a 204 status code is a valid http response.
In this case the deserialized "list" should be done successfully (and contain an empty list) without causing any error / exception

**Comment by trevorwang** [comment]
how about this https://github.com/trevorwang/retrofit.dart#get-orignal-http-reponse

**Comment by vincentvulog** [comment]
Sorry but it doesn't help
The deserialization is performed before  being encapsulated into the HttpResponse
`final value = SomeThing.fromJson(_result.data);`
So in case of a 204 (not an error) status code, the deserialization fail anyway, when it should'nt.

**Comment by trevorwang** [comment]
@vincentvulog  uh....

I think what you want is to get the response status code. And you don't case the response content.

Am I right?

if yes. The below is what you need.
https://github.com/trevorwang/retrofit.dart/blob/5aa66ef50f94645c585965339b9f0bd2eb00d3b9/example/lib/example.dart#L20

I can capture the response here like the following.
```
│ access-control-allow-credentials: true
│ connection: keep-alive
│ content-type: text/html; charset=utf-8
│ access-control-allow-origin: *
│ date: Fri, 05 Mar 2021 09:41:56 GMT
│ server: gunicorn/19.9.0

```

**Comment by vincentvulog** [comment]
@trevorwang 
What i miss is a method that could handle both 200 and 204 status codes
somethink like
@GET("https://api.some/resources")
 Future<HttpResponse<List<Tasks>>> reponseWith200or204whenEmpty();
When 200 a list of task should be given
in case of 204 with no payload, the same method should return an empty list of tasks (or null ?), but no failure

**Comment by vincentvulog** [comment]
it could be done by adding something like this in generated code:
```
if (response.request.method == "GET" && response.statusCode == 204) {
      response.data = <String, dynamic>{};//stub to allow deserialization
    }
```

**Comment by trevorwang** [comment]
when the status code is 204, there's no response content.  The response data **_is empty but not an empty list_**.   So you cannot use a list as the generic type.

And I don't believe it's common usage. So currently you have to use a `dynamic` as the generic type parameter for this special cinario. and then convert it to a list when the response code is 200.

**Comment by vincentvulog** [comment]
@trevorwang Some restfull apis uses it, and it's allowed by the http specifications, so not sure it can be considered useless.
Providing a way to handle this case nicely would be great. (other than do the deserialization yourself in that case)

**Comment by trevorwang** [comment]
Can you give some samples here?

What I mean is that 204 is definitely allowed in RESTFul APIs. And using two different response data structures for one request is really not recommend.

**Comment by mateusfccp** [comment]
I have the same problem, why hasn't this given any attention?

**Comment by victrmart** [comment]
I am having this same issue...

**Comment by feinstein** [comment]
@trevorwang what if the lib returns `null` in a 204? In that case we will need to pass a nullable type to the generator as in `Future<MyModel?> get204()`... Will that work?

**Comment by chnouman** [comment]
This issue is still open I guess. I faced the same issue. Any solution here?

**Comment by mobile-development-group-com** [comment]
@trevorwang I encountered below approach in multiple corporates and think it is normal for a restfull api. The thumb of rule is that an endpoint can't return more than one type of a response but a http 204 is what i think a valid exception. 

In my current use case a user can have promo_code_information that we fetch from a separate endpoint but not every user has that kind of data. So instead of returning the object with all null values or an empty object where all values have to be optional we return a 204 (no content) and otherwise a 200 (promo_code_information).

I'm not sure about this but maybe just a check if the type is optional:
```
  @GET('/api/mobile/users/v2/{uid}/partner-information')
  Future<HttpResponse<PartnerInformationResponse?>> getPartnerInformation({...});
```
and there is no data it should not throw an exception but at least complete with null?

What do you think?
