### ISSUE TITLE
JsonUnsupportedObjectError when passing MultiPart file

### ISSUE THREAD

**Issue by sooxt98** [trevorwang/retrofit.dart#317]
``` dart
abstract class RestClient {
  @POST("/register")
  Future<ApiResponse<Empty>> register(@Part() Map<String, dynamic> map);
}
```

The generated code should use ` FormData.fromMap(map)` instead of the commented red code

![image](https://user-images.githubusercontent.com/13378059/111541908-0270be80-87ac-11eb-8b8b-2c84f415b42a.png)

**Comment by andoutica** [comment]
Hi @sooxt98, I still got this issue on retrofit_generator 2.0.0-beta3.
Are you sure this already fixed?

**Comment by sooxt98** [comment]
@andoutica yes it works fine, could u tell me more about ur issue?

**Comment by andoutica** [comment]
omg, I saw the problem. 
I checked your code, this seem like you just check the parameter had one argument for Map field
``` final parts = _getAnnotations(m, retrofit.Part);
    if (parts.isNotEmpty) {
      if (m.parameters.length == 1 && m.parameters.first.type.isDartCoreMap) {
        blocks.add(refer('FormData')
            .newInstanceNamed('fromMap',
                [CodeExpression(Code(m.parameters.first.displayName))])
            .assignFinal(_dataVar)
            .statement);
        return;
      }
```
but when my code had two arguments, something like this: 
```@POST('user/profile')
  Future<Response> postAvatarWithFormData(@Part() Map<String, dynamic> profile,
      {@Part() File? avatar});
```
the code generator was: 
```final _data = FormData();
    _data.fields.add(MapEntry('profile', jsonEncode(profile)));
    if (avatar != null) {
      _data.files.add(MapEntry(
          'avatar',
          MultipartFile.fromFileSync(avatar.path,
              filename: avatar.path.split(Platform.pathSeparator).last)));
    }
```
can we remove ```m.parameters.length == 1``` condition?

**Comment by sooxt98** [comment]
Oh well u shouldnt be using mutliple param for that, since FormField already handle all these

**Comment by andoutica** [comment]
oh, I got this, 
Thank you, let me try to insert the File Part to the Map
