### ISSUE TITLE
Missing name for named argument _data in generated file. v 2.0.0-beta1

### ISSUE THREAD

**Issue by rugemo** [trevorwang/retrofit.dart#320]
There is a named parameter error in the generated file example.g.dart.
I noticed this separately in code that I am working on, whilst migrating an app to null safety.

![Screenshot 2021-03-20 at 13 30 20](https://user-images.githubusercontent.com/43332582/111869559-6d72ee80-8980-11eb-8f6f-c2df03feaf83.png)

Flutter details from flutter doctor -v

[✓] Flutter (Channel stable, 2.0.2, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-GB)
    • Flutter version 2.0.2 at /Users/.../Projects/Flutter/flutter
    • Framework revision 8962f6dc68 (9 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

Steps to reproduce the behaviour:
1. Set up a new project with the a pubspec.yaml

name: retrofit_generator_test
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  retrofit: ^2.0.0-beta1
  json_annotation: ^4.0.0
  logger: ^1.0.0-nullsafety.0
  dio: ^4.0.0-beta7

dev_dependencies:
  test: 1.16.5
  retrofit_generator: ^2.0.0-beta1
  build_runner: ^1.11.5
  json_serializable: ^4.0.2

flutter:

2. Fix any null safety issues in main,dart
3. Copy example.dart from retrofit repo
4. Run `flutter pub run build_runner build --delete-conflicting-outputs`

**Expected behaviour**
The generated file should name any parameters that `RequestOptions.compose(...)` in Dio expects.
Manually editing the generated file to add the name of the parameter removes the error.

![Screenshot 2021-03-20 at 13 40 41](https://user-images.githubusercontent.com/43332582/111869917-de66d600-8981-11eb-8231-dcb98a8608ac.png)

Thanks for all your time and effort maintaining this library.

**Comment by andoutica** [comment]
this also updated on version 2.0.0-beta3, pls upgrade your pubspec to using retrofit_generator 2.0.0-beta3

**Comment by mark-apn** [comment]
Is there any reason that beta-3 is not yet on pub.dev? And if so, can I do anything to help it become a reality :-)

**Comment by mark-apn** [comment]
Never mind, its already there, I tried updating both retrofit and retrofit_generator 🤦  Just updating the generator worked like a charm.
