### ISSUE TITLE
Update source_gen version to ^1.0.0 for retrofit_generator 2.0.0-beta1 

### ISSUE THREAD

**Issue by rugemo** [trevorwang/retrofit.dart#321]
**Describe the bug**
When using retrofit_generator and injectable_generator together, pub get fails due to a lower version of source_gen (^0.9.10+4) specified for retrofit_generator.

![Screenshot 2021-03-20 at 14 13 02](https://user-images.githubusercontent.com/43332582/111870680-6353ee80-8986-11eb-8a80-abe6830e1842.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Add the following dev_dependencies to a null safe pubspec file

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.2.1
  build_runner: ^1.12.2
  retrofit_generator: ^2.0.0-beta1

2. run pub get
3. See error mentioned above

**Expected behavior**
Both null safe generators should use the null safe version of source_gen and be able to run with out dependency_overrides.
injectable_generator uses source_gen ^1.0.0 which is the null safe version.

Please let me know if you need any more details. Thanks for all your work.

**Comment by Vladislav76** [comment]
@rugemo I have the same issue with _json_serializable_ package.

**Comment by NicolaChimerapps** [comment]
I have the implementation finished but we are waiting for #319 to be fixed and merged

**Comment by RakaAlrian** [comment]
I got same issue with _freezed_ package. Is there any temporary solution please?

**Comment by NicolaChimerapps** [comment]
See #323. Until this is merged you could use git references in your pubspec.yaml
