### ISSUE TITLE
Adding list query parameters

### ISSUE THREAD

**Issue by shoaib121** [trevorwang/retrofit.dart#328]
How do I add list query parameters? I have the following class:
`class Params{
final int intParam;
final List<String> listParams;
Params({this.intParam, this.listParams});

Map<String, dynamic> toJson() => {
'int_param': intParam,
'list_param[]': listParams,
}`

Below is my RestClient

`@GET("path")
Future<ResponseModel> getData({
@Queries() Params params,
}
);`

But my request was invalid and I got an empty response from the server, assuming it didn't recognize the parameters.

int_params: paramValue
list_params[]:  {list_params[]: [val1, val2, val3]}

What I expect is something like 

`list_param=val1&list_param=val2list_param=val3`

I have also tried it with **@Query("argName")** opting out the **intParam** to another positional parameter but it didn't work. 
Thanks in advance

**Comment by andoutica** [comment]
You can use this
```@GET("path") ```
```Future<ResponseModel> getData({ @Queries() Map<String,dynamic> params } );```

In your Repo, call: 
```getData(params : params.toJson());```

**Comment by shoaib121** [comment]
@andoutica Thank you. I got it working.
