### ISSUE TITLE
A way to handle non-200 status codes again

### ISSUE THREAD

**Issue by Lootwig** [trevorwang/retrofit.dart#33]
It seems that the Dio "Response" type is no longer supported as return type (the generated code tries to call `Response.fromJson()` which does not exist). How are server responses with a status other than "200" supposed to be handled from version 0.3.0 onwards?

**Comment by trevorwang** [comment]
Assume that we have defined the following code 
```
abstract class RestClient {
  @GET("/get")
  Future<HttpGet> ip(@Query('query1') String query);
}

final client = RestClient();

client.ip("aaa").then((httpGet){}).catchError((err){
/// non-200 error goes here.
});


```

**Comment by Lootwig** [comment]
Could you add a piece of documentation somewhere about the structure of the `err`-instance that gets thrown? I.e. how to get at the request/response properties? (This would help people who may not be able to force their server to generate something other than 200).

**Comment by trevorwang** [comment]
@Lootwig  Currently the document is not good. The improvement is scheduled to be done in coming weeks.

**Comment by trevorwang** [comment]
#34

**Comment by trevorwang** [comment]
#38
