### ISSUE TITLE
Is there a way to add "namespaced" clients?

### ISSUE THREAD

**Issue by pparadox11** [trevorwang/retrofit.dart#340]
Hi!

Is there a way to add namespaced like clients under the main client?

For example

```
@RestApi(baseUrl: 'https://jsonplaceholder.typicode.com/')
abstract class RestClient {
  final UserApi user;

  factory RestClient(Dio dio, {String? baseUrl}) {
    return _RestClient(dio, baseUrl: baseUrl);
  }
}

@RestApi(prefix: '/users')
abstract class UserApi {
  factory UserApi(Dio dio) = _UserApi;

  @GET('/')
  Future<List<User>> list();
}
```

So in end code you can use it like that, `restClient.user.list()`  ?

Just a question, i might be better in SO but other users might want it.. thanks again.

**Comment by trevorwang** [comment]
Exactly like what you said. It's not a common feature that everyone wants.

Please consider wrapping the APIs in another class then you can get something like what you want.
