### ISSUE TITLE
Nullable Value of Map<Key, Value> of Response isn't parsed correctly

### ISSUE THREAD

**Issue by WillowWisp** [trevorwang/retrofit.dart#354]
**Describe the bug**
Nullable Value of Map<Key, Value> of Response isn't parsed correctly in generated file

**To Reproduce**
1. Define an endpoint with a response type of Map<String, **MyClass?**>
2. Run generating command
3. In generated file, the value of type **MyClass?** ignores the null case

**Screenshots**
![image](https://user-images.githubusercontent.com/37970784/120961391-f59ab000-c787-11eb-93a6-4e8dbbe9738c.png)
![image](https://user-images.githubusercontent.com/37970784/120961420-00eddb80-c788-11eb-94df-6e682610e262.png)

**Expected behavior**
In the second picture, It should be:
`InstitutionInfoDto.fromJson(v as Map<String, dynamic>)` => `v == null ? null : InstitutionInfoDto.fromJson(v as Map<String, dynamic>)`

**Comment by WillowWisp** [comment]
@trevorwang I'm sorry for tagging you in but what do you think about this? This seems like a bug to me.

**Comment by ptmdmusique** [comment]
I got the same issue 💭I think it would greatly help if this bug got fix because the workaround looks really nasty 💫
