### ISSUE TITLE
Cannot use dynamic baseUrl endpoint

### ISSUE THREAD

**Issue by BTPDarren** [trevorwang/retrofit.dart#355]
Hi,

I used Retrofit in a Native Android application a few years ago

I am now learning flutter and found retrofit again

I want to use the API with a dynamic URL (from settings) but it wont let me

any guidance?

@RESTapi(baseUrl: AppPrefs().apiURL)
The constructor being called isn't a const constructor.

**Comment by NicolaVerbeeck** [comment]
That's because the value you are passing in the annotation is not a constant. This is also the case for java/kotlin. You can opt for providing the base url with the factory method instead. 

```dart
@RestApi()
abstract class RestClient {
  factory RestClient(Dio dio, {String baseUrl}) = _RestClient;```

**Comment by BTPDarren** [comment]
> That's because the value you are passing in the annotation is not a constant. This is also the case for java/kotlin. You can opt for providing the base url with the factory method instead.
> 
> ```dart
> @RestApi()
> abstract class RestClient {
>   factory RestClient(Dio dio, {String baseUrl}) = _RestClient;
> ```

Sorry, I am still learning this stuff, how would I pass my variable in this?

**Comment by BTPDarren** [comment]
nvm  - found it in the readme  i think you copied but missed the crucial line I needed :)

Thanks

**Comment by BTPDarren** [comment]
Ok

The example is not working

![image](https://user-images.githubusercontent.com/77784319/121392999-cf237300-c947-11eb-9fed-f5c88e2ad11d.png)

**Comment by AGenius** [comment]
I understand now. all sorted

**Comment by ccc-sseylani** [comment]
@AGenius @NicolaVerbeeck  Can you please explain how to pass variable with factory method ?  Thanks

**Comment by ccc-sseylani** [comment]
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/75082292/133843881-e34af788-7dcb-407a-aea5-13f393525496.png">

Even in the factory method, it is complaining!
I don't want to have const url. In my application, I ask the user for the url and I want to get it from shared preference.
@AGenius @NicolaVerbeeck @BTPDarren 
Can you please help me with this? 
Thanks

**Comment by ccc-sseylani** [comment]
> <img alt="image" width="1041" src="https://user-images.githubusercontent.com/75082292/133843881-e34af788-7dcb-407a-aea5-13f393525496.png">
> 
> Even in the factory method, it is complaining!
> I don't want to have const url. In my application, I ask the user for the url and I want to get it from shared preference.
> @AGenius @NicolaVerbeeck @BTPDarren
> Can you please help me with this?
> Thanks

as soon as I change It to const string, it works
<img width="967" alt="image" src="https://user-images.githubusercontent.com/75082292/133845167-85d79d72-88f9-462d-8b12-4186f5ee5bd3.png">
