### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by BTPDarren** [trevorwang/retrofit.dart#356]
Hi,

I am still new to flutter and retrofit in flutter

I see how to describe the header in the HTTP Methods 

My question is how can I dynamically set the x-api-key header to a variable so I dont have to hard code it

  @GET("/user/login")
  @Headers(<String, dynamic>{
    "x-api-key": "0576397FC823025FCE85BDA7C66CF81D3269BA8F"
  })
  Future<APIUserRecord?> userLogin(
    @Query("username") String username,
    @Query("password") String password,
    @Query("deviceid") String deviceid,
  );

if I try and set to a variable it shows an error

![image](https://user-images.githubusercontent.com/77784319/121662752-9bf2f800-ca9d-11eb-96f3-481205580598.png)

**Comment by NicolaVerbeeck** [comment]
You would have to make appGlobals a const and the apiKey a const too if you wish to use it like this (like in kotlin).

If this is not possible, consider using a dio interceptor to add the headers to the request (as with okhttp)

**Comment by BTPDarren** [comment]
Hi,

Thanks I forgot to make the appGlobals.apiKey a constant however, if the value came from a shared prefs how would I set that instead?

**Comment by NicolaVerbeeck** [comment]
Then you need to add it either as a parameter to every api call or use the dio interceptor: https://pub.dev/documentation/dio/latest/dio/Interceptor-class.html

**Comment by BTPDarren** [comment]
Thank you for the quick response, much appreciated.
