### ISSUE TITLE
Need support also to return errors and custom errors

### ISSUE THREAD

**Issue by pythonhubpy** [trevorwang/retrofit.dart#357]
**Retrofit is a perfect and easy-to-use library for making API calls. Thanks for the awesome package. I think this package lacks the main feature of returning errors in other words we need some kind of error handlers that can be caught in the logical part of the App itself instead of catching it in the UI because sometimes we would have custom errors that can also be returned from the API request while using some kind of functional programming**

**I would like to do something like this**
```
Future<Either<Failures, Sucess>> request(
      {required param1,
      required param2}) async {
    try {
        // Some code
        return right(Success);
    } on SomeException catch (e) {
      if (e.code == "error-message") {
        return left(const FailureClass.someFailure());
      } else {
        return left(const FailureClass.elseFailure());
      }
    }
  }
```
I am using `BloC` to consider I must map an event or show a snackbar based on the `FailureClass`, a `freezed` union that is returned from the API request.

I would like something like 
```
@POST("")
  Future<ReturnType>? requestMethod() {
    @Error() error((error) {
    return CustomFailure or Something;
  })
  }
```
or 
```
 Future<ReturnType>? requestMethod() {
  }.error((error) {
    return CustomFailure or Something;
  })
```

I don't know whether these two kinds of approaches are possible but just for a proposal, I am telling these.

**Comment by ipcjs** [comment]
I think that error handling should be done by the dio interceptor.

**Comment by pythonhubpy** [comment]
Can you give an example, please?

**Comment by trevorwang** [comment]
https://github.com/trevorwang/retrofit.dart/issues/168#issuecomment-861128426

**Comment by markfili** [comment]
> [#168 (comment)](https://github.com/trevorwang/retrofit.dart/issues/168#issuecomment-861128426)

now we're just going in circles...
