### ISSUE TITLE
Multiple parameters with same name

### ISSUE THREAD

**Issue by SlickSlime** [trevorwang/retrofit.dart#360]
**Is your feature request related to a problem? Please describe.**
I cannot create a query with multiple parameters of the same name.

**Describe the solution you'd like**
Retrofit should be able to perform the following request where there are multiple query parameters named `id` and its count is dynamic:
`https://example.com?id=1&id=2&id=3`

**Describe alternatives you've considered**
```
  @GET('')
  Future<...> getStuff(
    @Query('id') List<int> ids,
  );
```

Unfortunately, this results in the following URI:
`https://example.com?id%5B%5D=1&id%5B%5D=2&id%5B%5D=3`

**Additional context**
I think that this is a common use case which this library should certainly handle.

**Comment by BTPDarren** [comment]
Does this not depend on the API, from my understanding the API can only accept 1 parameter of the same name

**Comment by SlickSlime** [comment]
> Does this not depend on the API, from my understanding the API can only accept 1 parameter of the same name

Nope, that's not a limitation of HTTP. We can add multiple parameters with the same name.

You can see some discussions about the same here:
- https://github.com/square/retrofit/issues/1324
- https://stackoverflow.com/questions/24059773/correct-way-to-pass-multiple-values-for-same-parameter-name-in-get-request

**Comment by AGenius** [comment]
But not possible with PHP apparently

Still, learnt something

**Comment by AGenius** [comment]
But not possible with PHP apparently

Still, learnt something

**Comment by s2yed** [comment]
i am have problem 
The problem is, send last index the list<int>[1,2,3]


value send 3 not array

**Comment by trevorwang** [comment]
It depends on how `dio` handles this functionality.

**Comment by SlickSlime** [comment]
> It depends on how `dio` handles this functionality.

Ok. I see there is an open issue on `dio` repo itself - https://github.com/flutterchina/dio/issues/1189

**Comment by SlickSlime** [comment]
..
