### ISSUE TITLE
Problem sending a list, sending the last existing position This is after the update retrofit: ^1.3.4+1    dio: ^3.0.10  to me    retrofit: ^2.0.0    dio: ^4.0.0

### ISSUE THREAD

**Issue by s2yed** [trevorwang/retrofit.dart#361]
Problem sending a list, sending the last existing position
This is after the update
retrofit: ^1.3.4+1
   dio: ^3.0.10

to me
   retrofit: ^2.0.0
   dio: ^4.0.0

@MultiPart()
  @POST("gard/addGard")
  @FormUrlEncoded()
  Future<GardItemsAdd> addGard(
      @Field('OPType') String oPType,
      @Field('EmpID') int empID,
      @Field('StoreID') int storeID,
      @Field('BranchID') int branchID,
      @Field('UserID') int userID,
      @Field('OPCarryOver') String oPCarryOver,
      @Part() List<int> itemId,
      @Part() List<int> unitID,
      @Part() List<int> typeDirections,
      @Part() List<double> actualQty,
      @Part() List<String> expectedQty,
      @Part() List<double> diffQty,
      @Part() List<double> qty);

@override
  addGard(OPType, EmpID, StoreID, BranchID, UserID, OPCarryOver, ItemId, UnitID,
      TypeDirections, ActualQty, ExpectedQty, DiffQty, Qty) async {
 
    try {
 

      ArgumentError.checkNotNull(OPType, 'OPType');
      ArgumentError.checkNotNull(EmpID, 'EmpID');
      ArgumentError.checkNotNull(StoreID, 'StoreID');
      ArgumentError.checkNotNull(BranchID, 'BranchID');
      ArgumentError.checkNotNull(UserID, 'UserID');
      ArgumentError.checkNotNull(OPCarryOver, 'OPCarryOver');
      ArgumentError.checkNotNull(ItemId, 'ItemId');
      ArgumentError.checkNotNull(UnitID, 'UnitID');
      ArgumentError.checkNotNull(TypeDirections, 'TypeDirections');
      ArgumentError.checkNotNull(ActualQty, 'ActualQty');
      ArgumentError.checkNotNull(ExpectedQty, 'ExpectedQty');
      ArgumentError.checkNotNull(DiffQty, 'DiffQty');
      ArgumentError.checkNotNull(Qty, 'Qty');

      const _extra = <String, dynamic>{};

      final queryParameters = <String, dynamic>{};

      final _data =
      FormData.fromMap(
          {   'OPType': OPType,
        'EmpID': EmpID,
        'StoreID': StoreID,
        'BranchID': BranchID,
        'UserID': UserID,
        'OPCarryOver': OPCarryOver,
        'ItemId': ItemId,
        'UnitID': UnitID,
        'TypeDirections': TypeDirections,
        'ActualQty': ActualQty,
        'ExpectedQty': ExpectedQty,
        'DiffQty': DiffQty,
        'Qty': Qty
      }
      );

      final Response<dynamic>  _result = await _dio.fetch<dynamic>(
          _setStreamType<dynamic>(
              Options(
                  method: 'POST',
                  headers: <String, dynamic>{},
                  extra: _extra,
                  contentType: 'application/x-www-form-urlencoded'
              ).compose(
                  _dio.options,
                  'gard/addGard',
                  queryParameters: queryParameters, data: _data)
                  .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl)));

      // final Response<dynamic> _result = await _dio.request('gard/addGard',
      //     queryParameters: queryParameters,
      //     options: RequestOptions(
      //         method: 'POST',
      //         headers: <String, dynamic>{},
      //         extra: _extra,
      //         contentType: 'application/x-www-form-urlencoded',
      //         baseUrl: baseUrl),
      //     data: _data);

      if (_result.data is Map) return GardItemsAdd.fromJson(_result.data);
      if (_result.data is String)
        return GardItemsAdd.fromJson(statuesHttpEro(false, _result.data));

      return GardItemsAdd.fromJson(_result.data);
    } on DioError catch (e) {
      objectErrorBloc
          .getError(' Error ' + '   ' + e.message + ' invoice / updateInv');
      return GardItemsAdd.fromJson(statuesHttpEro(false, e.message));
    }
  }

**Comment by trevorwang** [comment]
Please make sure you have updated your project to null safety support.

If not, please keep using the previous verison.

**Comment by s2yed** [comment]
I am already using   null safety 
I can't go down to the lower version because there are many modifications made to this version

**Comment by trevorwang** [comment]
Have you tried the latest version?  It should be working with null safety.

**Comment by s2yed** [comment]
yes i user last versions
 
  pretty_dio_logger: ^1.1.1

  retrofit: ^2.0.1
  logger: ^0.8.3
  dio: ^4.0.0
#  pretty_dio_logger: ^1.2.0-beta-1
  json_annotation : ^4.0.0
  http_parser: ^4.0.0



dev_dependencies:
  flutter_test:
  retrofit_generator:
  build_runner: ^1.11.5




C:\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1165], locale ar-EG)
    • Flutter version 2.2.3 at C:\flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
