### ISSUE TITLE
Wrong content type

### ISSUE THREAD

**Issue by michalgauza** [trevorwang/retrofit.dart#367]
I want to send images to my API but only `png/jpg/jpeg images`. I cannot specify content type dynamically and default media type is set to `application/octet-stream` instead of be set based on file name. Why cant we just past content type form outside?

**Comment by michalgauza** [comment]
I was trying to do this like here https://github.com/trevorwang/retrofit.dart/pull/272 but get error `Exception: toJson() method have to add to MultipartFile?
`

**Comment by trevorwang** [comment]
It should be working.  show your code here.

**Comment by mj-hd** [comment]
Maybe retrofit.dart only supports `List<MultipartFile>` type, not `MultipartFile`.
