### ISSUE TITLE
How to post json body and file in same API

### ISSUE THREAD

**Issue by supermachaa** [trevorwang/retrofit.dart#369]
Hi, I am not asking about file upload through json, am asking about How to post json and file in same API?. 
I am in need of this, I am revamping native java android project to flutter.

Below example is native java android retrofit code. In this, it can able to send json body & file in same api.
> @Multipart
> @POST("api/postDocument")
> Observable<String> postDocuments(@Header("Authorization") String token, @Part("json") RequestBody json, @Part MultipartBody.Part image);

But in Flutter Retrofit unable to send json body and file in same api.
In below example, only body is gets posted, file is not uploaded.
> @POST("https://httpbin.org/post")
> @MultiPart()
> Future<HttpBinResponse> postHttpBin(@Query("username") String username, @Query("password") String password, @Part(fileName: "raj.png") File file, @Body() UserRegistrationDTO userRegistrationDTO);

example: 
File: bill document
JSON: assume it have lot of fields, in below json example i used less fields. I am using json_serializable BillDocumentDTOModel for below json.
> {
>   "billNumber": "ABCD124",
>   "billDate": "01:01:2021",
>   "paymentMode": "cash",
>   "billAmount": 10000,
>   "remarks": "transport rent rs.10000",
>   "billName": "Kanna M",
>   "mobile": 9876543210
> }

**Comment by sooxt98** [comment]
its by design, u cant send/upload file thru json, you need to use FormData instead.

take a look at this how we use it https://github.com/trevorwang/retrofit.dart/issues/317

**Comment by supermachaa** [comment]
Hi, I am not asking about file upload through json, am asking about How to post json and file in same API?. 
I am in need of this, I am revamping native java android project to flutter.

Below example is native java android retrofit code. In this, it can able to send json body & file in same api.
> @Multipart
> @POST("api/postDocument")
> Observable<String> postDocuments(@Header("Authorization") String token, @Part("json") RequestBody json, @Part MultipartBody.Part image);


But in Flutter Retrofit unable to send json body and file in same api.
In below example, only body is gets posted, file is not uploaded.
> @POST("https://httpbin.org/post")
> @MultiPart()
> Future<HttpBinResponse> postHttpBin(@Query("username") String username, @Query("password") String password, @Part(fileName: "raj.png") File file, @Body() UserRegistrationDTO userRegistrationDTO);


example: 
File: bill document
JSON: assume it have lot of fields, in below json example i used less fields. I am using json_serializable BillDocumentDTOModel for below json.
> {
>   "billNumber": "ABCD124",
>   "billDate": "01:01:2021",
>   "paymentMode": "cash",
>   "billAmount": 10000,
>   "remarks": "transport rent rs.10000",
>   "billName": "Kanna M",
>   "mobile": 9876543210
> }


## Please let me know, how to post json and file in same API, it will be very thankful.

**Comment by supermachaa** [comment]
Solved by importing "" import 'dart:convert'; "" in RestApiClientHttpBin class, it removes error message in _RestApiClientHttpBin class.

>  @POST("https://httpbin.org/post")
>  Future<HttpBinResponse> postHttpBinFileName6(@Part(name: "json") UserRegistrationDTO userRegistrationDTO, @Part() File file);


![image](https://user-images.githubusercontent.com/87132815/125036166-55021d80-e0b0-11eb-8c94-8fbbea08afec.png)



## Thanks to everyone

**Comment by himmatsingh019** [comment]
Hi may i know how you did this? Sending Field and Part in same POST request?
