### ISSUE TITLE
Generation of .g file when using constant baseUrl returns empty String

### ISSUE THREAD

**Issue by EdwynZN** [trevorwang/retrofit.dart#377]
When using a const String value from a class the generated file doesn't proper copy the value or the variable

Having a class of const attributes

```
class Env {
   const String baseUrl = 'https://myUrl:8000/";
   const String tenant = "sadjNUI65SFjna";
}
```

```
@RestApi(baseUrl: Env.baseUrl)
abstract class AuthenticationApi {
  factory AuthenticationApi(Dio dio, {String baseUrl}) = _AuthenticationApi;

  @POST('logout')
  Future<void> logout(
    @Header(HttpHeaders.authorizationHeader) String authToken, 
    [@CancelRequest() CancelToken? cancelToken]);

    ....
}
```
Won't build .g file with that baseUrl

```
class _AuthenticationApi implements AuthenticationApi {
  _AuthenticationApi(this._dio, {this.baseUrl});

   .....
}
```

**Expected behavior**
```
class _AuthenticationApi implements AuthenticationApi {
  _AuthenticationApi(this._dio, {this.baseUrl}) {
     baseUrl ??= Env.baseUrl;
  }

   .....
}
```
Using a const value outside of a class doesn't give this error but I find it weird that it copies its correctly with normal variables

I already tested it using the same class with `Freezed `annotations and they work without problem, copying the variable instead of the value it holds and i think this could solve the error and maybe some silent bugs when you change the value of a const variable but it won't change it inside retrofit until you run build_runner or at least fix copying the value of const Strings inside of classes like `json_serializable`

**Comment by mahdimoaz** [comment]
`salam`
