### ISSUE TITLE
[ re-name a field from the WS entry inApp code ]

### ISSUE THREAD

**Issue by Gobmichet** [trevorwang/retrofit.dart#378]
**Is your feature request related to a problem? Please describe.**
Webservices return snake case fields but the rest of my app is in camel case.

**Describe the solution you'd like**
An annotation that'd allow to rename fields from webservices

**Describe alternatives you've considered**
Well to stay with Snake and Camel case but that' ugly :s

**Additional context**
@JsonSerializable() seems to force us to keep the field name given from the webservice...
Is there another way to do in order to rename a field as we want after the WS call ?

**Comment by trevorwang** [comment]
Try this  https://github.com/google/json_serializable.dart/issues/279
