### ISSUE TITLE
List嵌套（比如List<List<T>>时）生成的代码有误

### ISSUE THREAD

**Issue by awq14789** [trevorwang/retrofit.dart#379]
大神你好，我在使用多List嵌套时生成的代码有问题：

	@POST('/smallTarget/gameZone/futureOpenArea')
  	Future<BaseApiResponse<List<List>>> getFutureOpenAreaList();

生成的代码如下：

      final value = BaseApiResponse<List<List<dynamic>>>.fromJson(
              _result.data!,
              (json) => (json as List<dynamic>)
                  .map<List<dynamic>>(
                      (i) => List<dynamic>.fromJson(i as Map<String, dynamic>)) <---此处代码会报错，List没有fromJson方法
                  .toList());

我目前暂时用dynamic接收返回值，但这样的话代码看着就很别扭。。。请问这个问题应该如何解决，谢谢

**Comment by trevorwang** [comment]
由于不支持反射，只能支持2层嵌套，就只忽略了多级List嵌套的情况
