### ISSUE TITLE
Nullability issue in generated MultiPart endpoint with List<MultipartFile> argument.

### ISSUE THREAD

**Issue by SynSzakala** [trevorwang/retrofit.dart#382]
**Describe the bug**
Multipart requests allow for providing a `List<MultipartFile>` argument. However, it doesn't work with nullsafety.

**To Reproduce**
Declare following endpoint:
```
@GET(...)
@MultiPart
Future<void> example(@Part() List<MultipartFile> file);
```
Generated code:
```
_data.files.addAll(data?.map((i) => MapEntry('data', i)));
```
Error:
```
The argument type 'Iterable<MapEntry<String, MultipartFile>>?' can't be assigned to the parameter type 'Iterable<MapEntry<String, MultipartFile>>'.
```

**Expected behavior**
Should generate:
```
if(data != null) {
  _data.files.addAll(data.map((i) => MapEntry('data', i)));
}
```

**Comment by mj-hd** [comment]
@SynSzakala 
This issue should be fixed by https://github.com/trevorwang/retrofit.dart/pull/422. 
Release: https://github.com/trevorwang/retrofit.dart/releases/tag/3.0.0%2B2
