### ISSUE TITLE
Cannot use dynamic baseUrl endpoint 

### ISSUE THREAD

**Issue by ccc-sseylani** [trevorwang/retrofit.dart#383]
**Describe the bug**

Almost Same as #355, but the solution is not working. 

I want to use dynamic baseUrl which provides by the user, and tried to pass it through factory method but it did not work.
I don't want to have const url, and I want to get base url from shared preferences.
Can you please help me with this?
Thanks

<img width="887" alt="image" src="https://user-images.githubusercontent.com/75082292/133845490-7637cb67-f16e-4fc2-a65d-4714f0b26f22.png">

as soon as I change It to const string, it works

<img width="884" alt="image" src="https://user-images.githubusercontent.com/75082292/133845524-1d257404-7dcd-4273-b41c-60f6adb0291c.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by NicolaVerbeeck** [comment]
You can specify a dummy base url and have a Dio interceptor (https://pub.dev/documentation/dio/latest/dio/Interceptor-class.html) to rewrite if for every request.

**Comment by ccc-sseylani** [comment]
Can you please explain more? 
How to add it ?
Thanks

**Comment by NicolaVerbeeck** [comment]
```
import 'package:dio/dio.dart';

class URLInterceptor extends Interceptor {

  @override
  void onRequest(RequestOptions options, RequestInterceptorHandler handler) {
    handler.next(options.copyWith(baseUrl: 'whateveryouwant'));
  }
}

ApiClient create() {
  final dio = Dio(BaseOptions(contentType: 'application/json'));
  dio.interceptors.add(URLInterceptor());

  return ApiClient(dio);
}
```
