### ISSUE TITLE
Can i post null with @Header?

### ISSUE THREAD

**Issue by Sotatek-DatThai** [trevorwang/retrofit.dart#384]
Hi! I have a post api like this
```
  @POST("v1/request/withdraw")
  Future<Account> postWithdraw(
    @Header("otpcode") String? otpcode,
    @Header("nonce") String? nonce,
    @Header("signature") String? signature,
    @Body() WithdrawSchema withdrawSchema,
  );
```
I want to send `nonce` and `signature` as null but its show me error `[DioErrorType.other]: type 'Null' is not a subtype of type 'Object'`
Can you show me how to do it?

**Comment by tatsuyayasuhara** [comment]
I want to do that, too. But I have the same error.

**Comment by woprandi** [comment]
The underlying http library does not allow nullable header. I send a PR https://github.com/trevorwang/retrofit.dart/pull/387  to avoid throwing exception by ignoring null value. You will have to convert yourself to a string if you want to have the header presents in the request

**Comment by woprandi** [comment]
@trevorwang You can close this

**Comment by woprandi** [comment]
@trevorwang same
