### ISSUE TITLE
[ Allow @Body() to ignore some object parameters ]

### ISSUE THREAD

**Issue by Gobmichet** [trevorwang/retrofit.dart#386]
**Is your feature request related to a problem? Please describe.**
Actually when my @body object is sent, i got 400 bad request 'cause sending too much parameters on a Symfony API which form validate doesn't allow to send non significant parameters...

**Describe the solution you'd like**
an annotation so that when passing some object representing the @Body of a request, we'd be able to ignore some of the parameters and do not send them when @POSTing...

**Describe alternatives you've considered**
the only alternative i see is to manually delete those parameters from the generated .g.dart file...
and that's ugly :s

**Comment by NicolaVerbeeck** [comment]
Alternatively you create a special object that only contains the relevant information to send to symfony

**Comment by Gobmichet** [comment]
Well that sounds as dirty as deleting from .g.dart file...
1 - it's a non sense from conception point of view.
2 - when 1st object will change you'll have to keep in mind to change the second one... so, this is ugly...

Wouldn't it be possible to write a method "toFormattedWSBody()" for example that wouls return the expeccted body ??
But which type should it return ?
Would a String be possible for retrofit ?
