### ISSUE TITLE
Unable to update Dio client

### ISSUE THREAD

**Issue by devsideal** [trevorwang/retrofit.dart#388]
I want to update Dio client before passing it to Rest client But its showing syntax error:

```
@RestApi(baseUrl: "https://example.com/api")
abstract class RestClient {

  factory RestClient(Dio dio){
    dio.options = BaseOptions(receiveTimeout: 5000, connectTimeout: 5000);
    return _RestClient(dio,  baseUrl : baseUrl); // Showing syntax error: Undefined name 'baseUrl'
  }
  ........
}
```

What I'm doing wrong?

**Comment by leoshusar** [comment]
I believe your factory constructor should be `factory RestClient(Dio dio, {String baseUrl})`

**Comment by devsideal** [comment]
Yes this way it's working but I want to add options in Dio like `dio.options = BaseOptions(receiveTimeout: 5000, connectTimeout: 5000);`
