### ISSUE TITLE
@SerializedName option (or similar)

### ISSUE THREAD

**Issue by rfogar2** [trevorwang/retrofit.dart#39]
**Is your feature request related to a problem? Please describe.**
The auto generated `toJson` functions are great, but they require your fields to be named exactly as the API keys. It'd be great if we could annotate our fields with @SerializedName (or something similar) to provide a different key to look for while maintaining naming conventions on our end.

**Describe the solution you'd like**
```
@JsonSerializable()
class Task {
  String id;
  @SerializedName("Name") String name;
  @SerializedName("TaskAvatar") String avatar;
  String createdAt;

  Task({this.id, this.name, this.avatar, this.createdAt});

  factory Task.fromJson(Map<String, dynamic> json) => _$TaskFromJson(json);
  Map<String, dynamic> toJson() => _$TaskToJson(this);
}
```

for an API response which looks like: 
```
{
    "id": "123123",
    "Name": "Bobby",
    "TaskAvatar": "Avatar",
    "createdAt": "111"
}
```

**Comment by trevorwang** [comment]
Retrofit uses jason_serializable to support this function. It is supposed to be supported already.

**Comment by trevorwang** [comment]
I closed this issue. Feel free to open it if any question.

**Comment by rfogar2** [comment]
Thanks for the example and quick response. :)
