### ISSUE TITLE
Cannot use the same Dio client for two APIs with different baseUrls

### ISSUE THREAD

**Issue by rfogar2** [trevorwang/retrofit.dart#40]
**Describe the bug**
I have two `RestApi`s with different baseUrls which use the same Dio client. Whichever one gets created first breaks because the second one overwrites the `_dio.options.baseUrl` in the generated `.g.dart` constructor. 

**To Reproduce**
1. Create two `RestApi`s with different baseUrls
2. Build them with the same Dio client
3. Whichever `RestApi` is built first will use the baseUrl for the `RestApi` built second.

**Example**
```
@RestApi(baseUrl: "https://my.baseurl.com/")
abstract class MyBaseUrlService {
   factory MyBaseUrlService(Dio dio) = _MyBaseUrlService;

    ...
}
```
```
@RestApi(baseUrl: "https://myother.baseurl.com/")
abstract class MyOtherBaseUrlService {
   factory MyOtherBaseUrlService(Dio dio) = _MyOtherBaseUrlService;

    ...
}
```

```
final dio = Dio();
final myBaseUrlService = MyBaseUrlService(dio);
final myOtherBaseUrlService = MyOtherBaseUrlService(dio);

// myBaseUrlService will use the baseUrl from MyOtherBaseUrlService
```

**Expected behavior**
`RestApi`s with different baseUrls should be able to use the same Dio client to benefit from shared Dio options, interceptors, etc.

**Possible solution**
Instead of changing the `dio.options.baseUrl`, prepend it to the `path` before calling `_dio.request`

**Comment by trevorwang** [comment]
https://github.com/flutterchina/dio/issues/385

I have create a pull request to dio to apply the base url in each request.

You should have  to use the dio

**Comment by rfogar2** [comment]
This doesn't solve the issue I raised. 

Dio should not set the baseUrl to the `baseUrl` param of `RestApi`. Instead, the `baseUrl` param should be prepended to the `path`. 

```
@RestApi(baseUrl: "https://my.baseurl.com/")
abstract class MyBaseUrlService {
   factory MyBaseUrlService(Dio dio) = _MyBaseUrlService;

    ...
}
```
```
@RestApi(baseUrl: "https://myother.baseurl.com/")
abstract class MyOtherBaseUrlService {
   factory MyOtherBaseUrlService(Dio dio) = _MyOtherBaseUrlService;

    ...
}
```


These two files generate the following

```
class _MyBaseUrlService implements MyBaseUrlService {
    _MyBaseUrlService(this._dio) {
       _dio.options.baseUrl = "https://my.baseurl.com/";
   }

    @Get("/path/to/api")
    doSomething();
   ...
}
```
```
class _MyOtherBaseUrlService implements MyOtherBaseUrlService {
    _MyOtherBaseUrlService(this._dio) {
       _dio.options.baseUrl = "https://myother.baseurl.com/";
   }
   ...
}
```

When we pass the same `Dio` instance to create both services, _dio.options.baseUrl is overwritten so one of the classes uses the same baseUrl as the other, which breaks the API.


To solve this problem, the generated file should use the `baseUrl` in this way.

```
class _MyBaseUrlService implements MyBaseUrlService {
    _MyBaseUrlService(this._dio)


   @override
   doSomething() async {
       final fullUrl = "https://my.baseurl.com/" + "/path/to/api"
       final response = await _dio.request(
            fullUrl,
           ...);
   ...
}
```

**Comment by trevorwang** [comment]
@rfogar2 

Did you use the latest version 0.6.0?

There should not be some code ` _dio.options.baseUrl = "https://my.baseurl.com/";` here.

**Comment by rfogar2** [comment]
Sorry, it works. Thanks!
