### ISSUE TITLE
Class type was wrong in generated _RestClient when the class type is defined in a generated file

### ISSUE THREAD

**Issue by badhorse** [trevorwang/retrofit.dart#401]
My code in api.dart:  
```
@RestApi()
abstract class RestClient {
  ...
  @GET("/getLoggedInUser.do")
  Future<User> getLoggedInUser();
  ...
}
```
Generated code in apt.g.dart by running `flutter packages pub run build_runner build`
```
class _RestClient implements RestClient {
  ...
    @override
  Future<dynamic> getLoggedInUser() async {
    ...
  }
  ...
}
```
The class type "User" became "dynamic" in generated file, that's wrong.

**To Reproduce**
Just let the class "User" defined in a generated file (also generated when running `flutter packages pub run build_runner build`),
in my case, "User" was defined in "schema.g.dart" which was generated by drift_dev (A code generator which generates code for db schema)

**Comment by trevorwang** [comment]
Please provide a minimum workable sample code here.
