### ISSUE TITLE
Dio naming conflict

### ISSUE THREAD

**Issue by cahix** [trevorwang/retrofit.dart#409]
My generated code can not be compiled due to a naming conflict.

`  @POST('/users/request')
  Future<HttpResponse> createRequest(@Body() Request request);`

leads to this problem when generated.
```
 Error: The argument type 'Response/*1*/<dynamic>' can't be assigned to the parameter type 'Response/*2*/<dynamic>'.
 - 'Response/*1*/' is from 'package:dio/src/response.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/dio-4.0.1/lib/src/response.dart').
 - 'Response/*2*/' is from 'package:dio_http/src/response.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/dio_http-5.0.4/lib/src/response.dart').
    final httpResponse = HttpResponse(value, _result);
```
                                           
I am using the Dio package as well as the Retrofit package. But it seems like the Retrofit package also uses the dio_http package which results in a conflict.

**Comment by veresvit** [comment]
The temporary fix is to pin version 2.0.1 and wait until the fix from 45b72bb5162367de9f9915a3c8afa3e2f084c963 commit is released.

``` yaml
retrofit: 2.0.1
```

**Comment by trevorwang** [comment]
please update generator  to 2.2.0

**Comment by veresvit** [comment]
@trevorwang Works great. Thank you for your great work!
