### ISSUE TITLE
Nested generics support

### ISSUE THREAD

**Issue by Rody66** [trevorwang/retrofit.dart#42]
Hi there! Please add nested generic types supporting. Like this case:
```dart
Future<ObjectResponse<List<Item>>> getItems();

class ObjectResponse<T> {
  T value;
  bool success;
  String message;
}
class Item {
  String val1;
  String val2;
}
```

**Comment by trevorwang** [comment]
Currently there's no perfect solution for this.

See https://github.com/dart-lang/json_serializable/issues/202

**Comment by Rody66** [comment]
I got it. Thank you for your answer! And thanks for great tool :)

**Comment by devkabiir** [comment]
@Rody66  Try using built_value, It is much more powerful than json_serializable. built_value supports nested generics. You can easily create serializers for any custom class.

See: https://github.com/google/built_value.dart

**Comment by vanlooverenkoen** [comment]
@trevorwang is it possible to generate just another fromJson and tojson method?

How it is now:
```
final value = ResponseWrapper<Status>.fromJson(_result.data);
    return Future.value(value);
```

How it should be:

```
final value = ResponseWrapper.fromJson<<Status>>(_result.data);
    return Future.value(value);
```

This way we can support generics without the use of json_serializable. And generate the generics models ourselfs
