### ISSUE TITLE
Support protobuf

### ISSUE THREAD

**Issue by lcdsmao** [trevorwang/retrofit.dart#424]
**Is your feature request related to a problem? Please describe.**
Is there any plan to support convert [protobuf](https://pub.dev/packages/protobuf) like [retrofit-converters/protobuf](https://github.com/square/retrofit/tree/master/retrofit-converters/protobuf) do?
If so I would like to help. 😃

**Describe the solution you'd like**
We have done a raw implementation here https://github.com/WinTicket/retrofit.dart/pull/1

**Describe alternatives you've considered**
Maybe we need to create a new package like `retorfit_protobuf`, because we need to import some packages for the generated `foo.g.dart` files.

**Additional context**

**Comment by trevorwang** [comment]
This lib was designed only for json. There's no plan right now to supoort protobuf.
I would appreciate to take PRs here if you can provide help.
