### ISSUE TITLE
Flutter web directly uses Dio to request data, but there is a problem with Dio+retrofit requesting data. What is the reason?

### ISSUE THREAD

**Issue by xsy2015** [trevorwang/retrofit.dart#428]
pubspec.yaml

-  dio: ^4.0.2-beta1
-  retrofit: ^2.0.1 

Flutter web directly uses Dio to request data, but there is a problem with Dio+retrofit requesting data. What is the reason?

**The request interface error is as follows**
Uncaught TypeError: Cannot read properties of null (reading 'nY')
    at main.dart.js:116183
    at bs9.a (main.dart.js:23275)
    at bs9.$2 (main.dart.js:50787)
    at Object.E (main.dart.js:23261)
    at aOp.nY (main.dart.js:116188)
    at main.dart.js:137190
    at bs9.a (main.dart.js:23275)
    at bs9.$2 (main.dart.js:50787)
    at Object.E (main.dart.js:23261)
    at UY.agN (main.dart.js:137208)

[main.dart.txt](https://github.com/trevorwang/retrofit.dart/files/7640070/main.dart.txt)

**Comment by xsy2015** [comment]
![微信截图_20211203172114](https://user-images.githubusercontent.com/12710053/144577047-c6fb424f-b5a4-4698-9843-b189babb4e5a.png)
The first two interfaces only use dio, the interface that reports errors in the middle uses retrofit, and the latter interface only uses dio, which is no problem.

**Comment by trevorwang** [comment]
Please provide more details here?   variables are obfuscated.

**Comment by xsy2015** [comment]
[request.txt](https://github.com/trevorwang/retrofit.dart/files/7648746/request.txt)
Details are in the attached txt file below

**Comment by xsy2015** [comment]
The Web application built in Release mode is compressed,
The problem with retrofit, the Debug version request data is no problem

**Comment by leoshusar** [comment]
[This](https://github.com/dart-lang/sdk/tree/main/pkg/dart2js_tools) or [this](https://pub.dev/packages/source_map_stack_trace) should help with the obfuscated stack traces.
I'm not sure now if dart2js generates source maps by default, but using `--source-maps` flag should generate them.

**Comment by xsy2015** [comment]
How can I solve it now?

**Comment by trevorwang** [comment]
please use the below as a workaround
https://stackoverflow.com/a/38817901/4423292
