### ISSUE TITLE
Issue with sending name with List<List<int>>

### ISSUE THREAD

**Issue by xoltawn** [trevorwang/retrofit.dart#430]
When using ```List<List<int>>``` , you are only allowed to pass a name which is used for each one of the files.

**example of current state:**
  ```@Part(name: 'files[]', fileName: 'givenConstantName') List<List<int>> files```

What about replacing it with Map<String, List<int>> so we can give each file a unique name, so the ```fileName``` won't be used in this situation?

**example of suggested state:**
  ```@Part(name: 'files[]') Map<String, List<int>> files```

**Comment by xoltawn** [comment]
I can help implementing it

**Comment by trevorwang** [comment]
Very appreciated to takek PR from here.
