### ISSUE TITLE
Unable to request data by 'flutter build web' to pack release package 

### ISSUE THREAD

**Issue by wenzhiming** [trevorwang/retrofit.dart#432]
**Describe the bug**

Unable to request data by 'flutter build web' to pack release package 

**To Reproduce**
Enter the command in terminal：
1. flutter build web 
   **(pack release package ,can not request data)**

2，flutter build web --profile --dart-define=Dart2jsOptimization=O0 
**(pack profile package or debug package is ok, can get the api data )**

**envi**
  dio: ^4.0.4       
  retrofit: ^3.0.0  

**Additional context**
简单来说：
1，用retrofit+dio插件：打release包发布到服务器后，无法网络请求，而打profile包或debug包的话就正常。
2，不用retrofit，直接用dio是可以正常release打包并正常获取数据的。
初步结论：retrofit插件代码在release打包的时候被混淆了的无法工作。建议作者做兼容处理。@trevorwang

**Comment by wenzhiming** [comment]
@trevorwang

**Comment by trevorwang** [comment]
close  due to #428
