### ISSUE TITLE
analyzer 3.0.0

### ISSUE THREAD

**Issue by amebrahimi** [trevorwang/retrofit.dart#439]
Hi, When updating the analyzer to version 3.0.0 and running pub get there is an issue with retfoit_generator.

```
flutter pub get
Running "flutter pub get" in smith...                           
Because retrofit_generator 3.0.0+2 depends on analyzer ^2.0.0 and no versions of retrofit_generator match >3.0.0+2 <4.0.0, retrofit_generator ^3.0.0+2 requires analyzer ^2.0.0.
```

**Comment by trevorwang** [comment]
any reason to update the analyzer?

**Comment by trevorwang** [comment]
any reason to update the analyzer?

**Comment by amebrahimi** [comment]
@trevorwang Other libraries are updating their analyzer and soon it will be a problem.

**Comment by trevorwang** [comment]
close due to #446
