### ISSUE TITLE
Retrofit Generator put path variables in braces

### ISSUE THREAD

**Issue by LiamConan** [trevorwang/retrofit.dart#447]
**Describe the bug**
When generating .g.dart file, the generator put the path variables in braces instead of standalone still version 2.2.0 ex:
'path/of/url/${value}' instead of 'path/of/url/$value'

**To Reproduce**
1. Create a call with a path variable like:
@GET("path/to/api/{term}")
  Future<Data> getData(@Path("value") String value);
2. Generate .g.dart file with retrofit ^3.0.1 and generator any

**Expected behavior**
The generator generate files with variables in standalone instead of with braces

**Comment by trevorwang** [comment]
Please provide the sample code

**Comment by leoshusar** [comment]
Isn't it [this](https://github.com/trevorwang/retrofit.dart/pull/416)?

**Comment by LiamConan** [comment]
Yes it is @leoshusar , thank you, I didn't see it before but still not working for me with the latest version (retrofit 3.0.1 and retrofit_generator 4.0.0)

For the sample code :
```
part 'api.g.dart';

@RestApi(baseUrl: Strings.baseUrl)
abstract class Api {
  factory Api(Dio dio, {String baseUrl}) = _Api;

  @DELETE("meal/{mealId}")
  Future<Diary> deleteMeal(@Path("mealId") String mealId);
}
```

gives the following code when generated :

```
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'api.dart';

// **************************************************************************
// RetrofitGenerator
// **************************************************************************

// ignore_for_file: unnecessary_brace_in_string_interps

class _Api implements Api {
  _Api(this._dio, {this.baseUrl}) {
    baseUrl ??= 'https://forest-dot-balanz-298312.ew.r.appspot.com/api/';
  }

  final Dio _dio;

  String? baseUrl;

  @override
  Future<Diary> deleteMeal(mealId) async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final _result = await _dio.fetch<Map<String, dynamic>>(
        _setStreamType<Diary>(
            Options(method: 'DELETE', headers: _headers, extra: _extra)
                .compose(_dio.options, 'meal/${mealId}',
                queryParameters: queryParameters, data: _data)
                .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl)));
    final value = Diary.fromJson(_result.data!);
    return value;
  }

  RequestOptions _setStreamType<T>(RequestOptions requestOptions) {
    if (T != dynamic &&
        !(requestOptions.responseType == ResponseType.bytes ||
            requestOptions.responseType == ResponseType.stream)) {
      if (T == String) {
        requestOptions.responseType = ResponseType.plain;
      } else {
        requestOptions.responseType = ResponseType.json;
      }
    }
    return requestOptions;
  }
}
```

and the variable "mealId" is under braces : ${mealId} instead of just $mealId

**Comment by leoshusar** [comment]
I'm sorry, I think I don't understand. Is there any problem when the variable is in braces like `${mealId}`?
That change was made because if you had route `/{id}_something`, it wouldn't work without braces like `/$id_something`, because `_something` would be part of the variable. But `/${id}_something` fixes it.

**Comment by LiamConan** [comment]
Ok I understand, the problem was that it sends me a lot of warnings due to the braces and it was disturbing

**Comment by leoshusar** [comment]
Ah, I see now.
Well I see in your generated file there is `// ignore_for_file: unnecessary_brace_in_string_interps`, that should tell the analyzer to ignore these warnings, that *should* hide them...

You can also exclude all generated files from analysis by adding this:
```yml
analyzer:
  exclude:
    - "**/*.g.dart"
```
to your `analysis_options.yaml`.
Be aware this also hides them from autocomplete, so if you are importing something from `.g.dart` file (happens quite rarely imo), it won't autocomplete it. But you can still import it manually and use it without any problem.

**Comment by LiamConan** [comment]
It works ! Thank you a lot ! Sorry for the issue, it was not relevant, I close it :)
