### ISSUE TITLE
Error in the generated file

### ISSUE THREAD

**Issue by iamisathya** [trevorwang/retrofit.dart#454]
**Describe the bug**
Error in the generated file

**To Reproduce**
Steps to reproduce the behaviour:
retrofit_generator: '>=3.0.0 <4.0.0'
retrofit: ^3.0.1

**Expected behaviour**
Should generate .g file normally

**Screenshots**
<img width="468" alt="Screenshot 2022-01-23 at 10 25 01 PM" src="https://user-images.githubusercontent.com/24954048/150689232-a96fa0a8-5d33-4277-a219-f4a8e660f5cc.png">
<img width="942" alt="Screenshot 2022-01-23 at 10 24 54 PM" src="https://user-images.githubusercontent.com/24954048/150689233-709abfa4-2c53-433c-8595-cf5dc4abee61.png">

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone11]
 - OS: [e.g. iOS12.1]

**Additional context**

**Comment by trevorwang** [comment]
Did you try generator 4.0.1?

**Comment by leoshusar** [comment]
That error is because you are using `@required` annotation and Retrofit generates `required` keyword.
`@required` annotations were used before null safety, just remove the `@` and it should work.

**Comment by trevorwang** [comment]
Yes. you are right.   Please use required instead of @required
