### ISSUE TITLE
How to send an array of queryParameters?

### ISSUE THREAD

**Issue by chihao10711** [trevorwang/retrofit.dart#457]
**Describe the bug**
I have queryParameters with name "include" and value as image
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/91370163/155846586-cea9fa8e-7fd4-4ed1-a580-d42f757bfdf1.png">

However, the URI when using DIO is not sent to the array, but it is duplicated "include".
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/91370163/155846685-53e858f8-3221-40ac-af95-fd5b4d56f68e.png">

I tried using Do().get with queryParameters like that and it works fine. And here is the URI when using Dio().get
<img width="1101" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/91370163/155846842-cd99fa7a-950c-4598-880e-e82c2fd4b353.png">
Is there a way can generator code can work like this?

**Comment by tanwarjigyasu** [comment]
Can you tell me how you did that using Dio.get() ? I have a similar problem like you, my API needs array for a particular parameter but retrofit just copies it multiple times so it doesn't work overall. I don't have any experience in Dio as I haven't really used it before

**Comment by chihao10711** [comment]
@tanwarjigyasu I add FixQueryStringRequestOptions in to interceptors, please see more detail https://github.com/cfug/dio/issues/734
