### ISSUE TITLE
Response<T>

### ISSUE THREAD

**Issue by parthsakariyasworks** [trevorwang/retrofit.dart#479]
Hi,
I need a Response like this way can you plz help me.

import 'package:dio/dio.dart';
`Response<T> getUsers();`

**Comment by ilovelinux** [comment]
Is it a RetroFit method? If yes, it should return a `Future`.
Can't you use `dynamic` instead of `T`?
Give us more informations please.

**Comment by trevorwang** [comment]
@parthsakariyasworks 

https://github.com/trevorwang/retrofit.dart#get-original-http-response
