### ISSUE TITLE
Add integration tests checking basic use-cases

### ISSUE THREAD

**Issue by Czocher** [trevorwang/retrofit.dart#48]
**Is your feature request related to a problem? Please describe.**
After developing the last PR I noticed, since I haven't taken some dynamic type cast problems into consideration, my lack of Dart expertise caused a new bug. 

**Describe the solution you'd like**
The basic library use-cases should be tested not only by the generator unit tests but also with proper integration tests with a mocked example service.

Some potential use cases which should be taken into consideration include:
- Returning basic types (`String`, `int`, `bool`, `double`)
- Returning a collection of basic types (`List`, `Map`?)
- Returning a single self-made type (the inner properties shouldn't matter since that part is handled by `json_serialization` anyway, but we can add some basic types plus one self-made type)
- Returning a collection of self-made types (`List`, `Map`?)

This should not only allow us to have better test coverage (another thing which can be checked!) of edge cases but also grant us peace of mind when developing in the future as well as guard us from potential regressions in runtime situations (such as the one described above).

**Describe alternatives you've considered**
I should really learn Dart better before providing PRs :D.

**Comment by trevorwang** [comment]
Yes.  More integration and unit tests should be added into the test. The current tests added just check that whether the code is generated as you wished. But it might not work.
