### ISSUE TITLE
Add FieldMap annotation

### ISSUE THREAD

**Issue by romawizard** [trevorwang/retrofit.dart#480]
Sometimes it will be useful to use FieldMap (like in Retrofit for Android) to pass a batch of fields on a POST request. It's also useful when you are filling with FormData and want to pass files along with some text field (I know that we can use JSON to pass a parameter as a single value, but Backend from time to time uses only simple fields).
From the Retrofit for Android documentation:

Named key/value pairs for a form-encoded request.
Simple Example:
   @FormUrlEncoded
   @POST("/things")
   Call<ResponseBody> things(@FieldMap Map<String, String> fields);
   
Calling with foo.things(ImmutableMap.of("foo", "bar", "kit", "kat") yields a request body of foo=bar&kit=kat.
A null value for the map, as a key, or as a value is not allowed.

Also, I found this package https://pub.dev/packages/dartrofit that contains this annotation, but I'd like to use this lib instead. 
Please add this feature

**Comment by trevorwang** [comment]
Please try  @Body

Please feel free to reopen this issue if it doesn't work.

**Comment by masreplay** [comment]
it doesn't work

**Comment by Ridje** [comment]
Hello there.
I have a situation where I need to use both @Body and @Field together:
```kotlin
  @POST('%{someexample}')
  @FormUrlEncoded()
  Future<String> getMyEndpoint({
    @Field("SERVICE_CODE") required String serviceCode,
    @Body() required Map<String, String> parameters,
    @Field("ACTION") String action = "ONLINE_CHECK",
  });
```
However, in this case, `action` and `serviceCode` are not even used in the generated file. Any chances to fix this, or am I doing something wrong ideologically?
