### ISSUE TITLE
Optional and optional named query parameters are not handled properly

### ISSUE THREAD

**Issue by Aidanvii7** [trevorwang/retrofit.dart#50]
**Description**
This is arguably a feature request, however it can be considered a bug as well as the optional and optional named parameters are accepted.

**To Reproduce**
Implement something like:
```
import 'package:dio/dio.dart';
import 'package:retrofit/http.dart';
import 'package:meta/meta.dart';

part 'my_client.g.dart';

@RestApi()
abstract class MyClient {

  factory MyClient(Dio dio) = _MyClient;

  @GET("content/api")
  Future<Result> namedExample(@Query("apikey") String apiKey,
      @Query("scope") String scope,
      @Query("type") String type, {
        @required @Query("from") int from
      });

  @GET("content/api")
  Future<Result> optionalNamedExample(@Query("apikey") String apiKey,
      @Query("scope") String scope,
      @Query("type") String type, {
        @Query("from") int from
      });

  @GET("content/api")
  Future<Result> optionalExample(@Query("apikey") String apiKey,
      @Query("scope") String scope,
      @Query("type") String type, [
        @Query("from") int from
      ]);
}
```
**Expected behavior**
In the case of `namedExample`, I would expect a null assertion to occur for the `from` parameter as of the existence of the `@required` annotation, however this is not the case.

In the case of `optionalNamedExample`, I would expect no null assertion for the `from` parameter as `@required` is not present. This is correct, however I would expect it to only be added to the `queryParameters` if `from` is not null (I think Square's Retrofit handles this). This could be done simply with Dart 2.3's control flow collections by doing:
```
final queryParameters = <String, dynamic>{
      'apikey': apiKey,
      'scope': scope,
      'type': type,
      if(from != null) 'from': from
    };
```

In the case of `optionalExample`, I would expect the same sort of behaviour as above.

**Comment by Aidanvii7** [comment]
p.s. great job with the library!

**Comment by devkabiir** [comment]
`@required` is deprecated, Work is in progress for the new `required` syntax see: https://github.com/dart-lang/language/issues/15.

Temporarily I can enable the `@required` But It will go away in the future.

**Comment by marinat** [comment]
is this realized? optional query parameter now adds even it is null
