### ISSUE TITLE
Unable to fetch data from response Headers.

### ISSUE THREAD

**Issue by ShankarKakumani** [trevorwang/retrofit.dart#501]
Unable to fetch data from response Headers.

I get pagination data in ResponseHeader, how to extract/fetch pagination info from Response Headers.

**Screenshots**
<img width="1019" alt="Screenshot 2022-09-25 at 11 31 03 AM" src="https://user-images.githubusercontent.com/35686278/192130600-ee0c219d-3514-4055-9a32-7cf013acfdf0.png">

**Comment by fedser** [comment]
As option you could get full response like this (taken from example):
```
@GET("/tasks/{id}")
  Future<HttpResponse<Task>> getTask(@Path("id") String id);
```
