### ISSUE TITLE
Split requests into services

### ISSUE THREAD

**Issue by appinteractive** [trevorwang/retrofit.dart#502]
Hey first thanks for that nice package.

I’m wondering how to structure the client when we have a lot of requests, it’s a bit cumbersome to have a huge client definition like shown in the examples. It’s hard to navigate. 

I looked into the chopper package an they solve it by using the services approach where you have only one client but multiple request definitions that stand for their own. 

```dart
 void main() async {
  final chopper = ChopperClient(
      baseUrl: "http://my-server:8000",
      services: [
        // Create and pass an instance of the generated service to the client
        TodosListService.create()
      ],
    );

  /// Get a reference to the client-bound service instance...
  final todosService = chopper.getService<TodosListService>();
  /// ... or create a new instance by explicitly binding it to a client.
  final anotherTodosService = TodosListService.create(chopper);
}
```

Is something like that possible?

**Comment by leoshusar** [comment]
I just have multiple Retrofit services, for example `UserService`, `PlaylistService`, ... and then inject `Dio` singleton into them.

Then I simply inject my `UserService` using `GetIt`.

**Comment by appinteractive** [comment]
Ahh of cause it does use the provided client 😅 looked to me as if Dio gets initialized multiple times but now I get it. 

Thanks for the hint. 🙏
