### ISSUE TITLE
depends on code_builder

### ISSUE THREAD

**Issue by a1573595** [trevorwang/retrofit.dart#504]
**Describe the bug**
Because mockito >=5.3.1 depends on code_builder ^4.3.0 and retrofit_generator >=4.1.0+1 depends on code_builder >=4.0.0 <4.3.0, version solving failed.

**To Reproduce**
1. Use retrofit_generator: ^4.1.0+1 and mockito: ^5.3.2.

**Expected behavior**
Compile success.

**Additional context**
retrofit_generator: ^4.0.3+2 work fine with mockito: ^5.3.2, but retrofit_generator: ^4.1.0+1 has conflict.

**Comment by Carapacik** [comment]
@trevorwang It's time to update code_builder

**Comment by Carapacik** [comment]
This happens because in the new code_builder they changed the generation

**Comment by trevorwang** [comment]
Close since fixed in #507
