### ISSUE TITLE
How about to add lints package for project and fix issues with code_builder?

### ISSUE THREAD

**Issue by Carapacik** [trevorwang/retrofit.dart#507]
I can fix code_builder 4.3.0.
I also think it's worth adding [lints](https://pub.dev/packages/lints) to style the project

**Comment by Carapacik** [comment]
Fix for #504 and #505

**Comment by trevorwang** [comment]
Thanks for your contribution

**Comment by trevorwang** [comment]
Agree. Please add lints in a separate pull request.
