### ISSUE TITLE
Generator fail after update to retrofit 3.3.0 and retrofit_generator 4.1.2

### ISSUE THREAD

**Issue by camillobucciarelli** [trevorwang/retrofit.dart#511]
After the update I have this issue:
```
[WARNING] ../../../../../../.pub-cache/hosted/pub.dartlang.org/retrofit_generator-4.1.2/lib/src/generator.dart:81:7: Error: No named parameter with the name 'autoCastResponse'.
      autoCastResponse: annotation?.peek('autoCastResponse')?.boolValue,
      ^^^^^^^^^^^^^^^^
../../../../../../.pub-cache/hosted/pub.dartlang.org/retrofit-3.3.0/lib/http.dart:66:9: Context: Found this candidate, but the arguments don't match.
  const RestApi({
        ^^^^^^^
../../../../../../.pub-cache/hosted/pub.dartlang.org/retrofit_generator-4.1.2/lib/src/generator.dart:494:27: Error: The getter 'autoCastResponse' isn't defined for the class 'RestApi'.
 - 'RestApi' is from 'package:retrofit/http.dart' ('../../../../../../.pub-cache/hosted/pub.dartlang.org/retrofit-3.3.0/lib/http.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'autoCastResponse'.
        (clientAnnotation.autoCastResponse ?? true);
```

flutter doctor:
```
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-x64, locale en-GB)
    • Flutter version 3.3.4 on channel stable at /Users/camillobucciarelli/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (27 hours ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0
```

**Comment by camillobucciarelli** [comment]
@vikasp52  I workaround to fix the version of retrofit to 3.0.2 meanwhile

**Comment by donpaul120** [comment]
I'm also equally facing this issue...

**Comment by Constans** [comment]
Currently "fixed" it with an override:
`
dependency_overrides:
  retrofit:
    git:
      url: https://github.com/trevorwang/retrofit.dart.git
      ref: master
      path: retrofit
      commit: befa7fad6072ac712a45b2b5ee14d58919865b00
`

**Comment by Constans** [comment]
> @vikasp52 I applied the following workaround for now
> 
> add dependency like the following: `retrofit: 3.0.2`
> 
> and after run:
> 
> * `flutter clean`
> * `flutter pub get`

Note that `3.0.2` contains a bug: https://github.com/trevorwang/retrofit.dart/commits/master

**Comment by camillobucciarelli** [comment]
> > @vikasp52 I applied the following workaround for now
> > add dependency like the following: `retrofit: 3.0.2`
> > and after run:
> > 
> > * `flutter clean`
> > * `flutter pub get`
> 
> Note that `3.0.2` contains a bug: https://github.com/trevorwang/retrofit.dart/commits/master

Ok I'll override dependency as reported above

**Comment by vikasp52** [comment]
> @vikasp52 I applied the following workaround for now
> 
> add dependency like the following: `retrofit: 3.0.2`
> 
> and after run:
> 
> * `flutter clean`
> * `flutter pub get`

@camillobucciarelli  I have tried this, Still not working for me.

```

-   retrofit: ^3.0.2
-    json_serializable: ^6.4.1
-   build_runner: ^2.2.1
-   retrofit_generator: ^4.1.2

```

Do I need to update the version for other packages as well ? And Is there any major issue in this `3.0.2` version ?

**Comment by camillobucciarelli** [comment]
> Currently "fixed" it with an override:
> 
> ```
> dependency_overrides:
>   retrofit:
>     git:
>       url: https://github.com/trevorwang/retrofit.dart.git
>       ref: master
>       path: retrofit
>       commit: befa7fad6072ac712a45b2b5ee14d58919865b00
> ```
> 
> This seems to be the latest commit to master. I'm not sure where the v. 3.3.0 comes from. It should be something like 3.0.2+1

@vikasp52 use this approch, as said by @Constans version 3.0.2 contains bug

**Comment by donpaul120** [comment]
> > @vikasp52 I applied the following workaround for now
> > add dependency like the following: `retrofit: 3.0.2`
> > and after run:
> > 
> > * `flutter clean`
> > * `flutter pub get`
> 
> @camillobucciarelli I have tried this, Still not working for me.
> 
> ```
> -   retrofit: ^3.0.2
> -   json_serializable: ^6.4.1
> -   build_runner: ^2.2.1
> -   retrofit_generator: ^4.1.2
> ```
> 
> Do I need to update the version for other packages as well ? And Is there any major issue in this `3.0.2` version ?

Change `retrofit: ^3.0.2` to `retrofit: 3.0.2`

**Comment by constantin-wundermart** [comment]
The bug is here: https://github.com/trevorwang/retrofit.dart/commit/c80af8cbc31c2a06696bdeb9b962afbd0a258d59 
If you're not affected by it, then use the `3.0.2` version. Don't use it with or higher symbol `^` like: `^3.0.2` or pub upgrade will fetch the `3.3.0` version.

**Comment by Constans** [comment]
The bug is here: [c80af8c](https://github.com/trevorwang/retrofit.dart/commit/c80af8cbc31c2a06696bdeb9b962afbd0a258d59)
If you're not affected by it, then use the `3.0.2` version. Don't use it with or higher symbol `^` like: `^3.0.2` or pub upgrade will fetch the `3.3.0` version.

**Comment by vikasp52** [comment]
> The bug is here: [c80af8c](https://github.com/trevorwang/retrofit.dart/commit/c80af8cbc31c2a06696bdeb9b962afbd0a258d59) If you're not affected by it, then use the `3.0.2` version. Don't use it with or higher symbol `^` like: `^3.0.2` or `pub upgrade` will fetch the `3.3.0` version.

Understood, this is working.

**Comment by trevorwang** [comment]
retracted the versions of above 3.0.1

**Comment by trevorwang** [comment]
forgot to publish the generator accordingly. Please try generator 4.2.0  @camillobucciarelli
