### ISSUE TITLE
[statusCode: 400] After upgrade 3.3.1 version

### ISSUE THREAD

**Issue by khanhnt3010** [trevorwang/retrofit.dart#512]
I reported https://github.com/trevorwang/retrofit.dart/issues/510
But when lib update to 3.3.1

```
 statusCode: 400
 headers:
  x-powered-by: ASP.NET
  cache-control: no-store, no-cache, max-age=0
  date: Mon, 10 Oct 2022 03:09:56 GMT
  transfer-encoding: chunked
  x-robots-tag: noindex
  pragma: no-cache
  content-type: application/json; charset=UTF-8
  server: Kestrel
 Response Text:
{"error":"invalid_request"}
```

I'm still looking to find the root cause, so if you have time please take a look

**Comment by tuan-khanhnguyen** [comment]
retrofit: ^3.3.1
build_runner: ^2.2.1
retrofit_generator: ^4.2.0

**Comment by tuan-khanhnguyen** [comment]
package using:

```
retrofit: ^3.3.1
build_runner: ^2.2.1
retrofit_generator: ^4.2.0
```

**Comment by trevorwang** [comment]
@khanhnt3010  Does it work on previous version?

**Comment by khanhnt3010** [comment]
Yes, I have to clean project, and rerun
it's worked :)
I would like to close this issue
