### ISSUE TITLE
@Headers still not work

### ISSUE THREAD

**Issue by nEdAy** [trevorwang/retrofit.dart#514]
Add static HTTP headers

```
	@GET("/tasks")
	@Headers(<String, dynamic>{
		"Content-Type" : "application/json",
		"Custom-Header" : "Your header"
	})
        Future<Task> getTasks();
```

```
part 'rest_client.g.dart';

@RestApi()
abstract class RestClient {
  factory RestClient(Dio dio, {String? baseUrl}) = _RestClient;

  @GET("/tasks")
  @Headers(<String, dynamic>{
    "Content-Type" : "application/json",
    "Custom-Header" : "Your header"
  })
  Future<Task> getTasks();
}
```

Annotation must be either a const variable reference or const constructor invocation. (Documentation)

The name 'Headers' is defined in the libraries 'package:dio/src/headers.dart (via package:dio/dio.dart)' and 'package:retrofit/http.dart (via package:retrofit/retrofit.dart)'. (Documentation) 

Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.

  dio: ^4.0.6
  retrofit: ^3.3.1
  retrofit_generator: ^4.2.0

import 'package:dio/dio.dart' as dio;
import 'package:retrofit/retrofit.dart';

However, dio.* will not be used in the generated .g file.

So @Headers still won't work.

#232

**Comment by trevorwang** [comment]
try `import 'package:dio/dio.dart' hide Headers;`

**Comment by nEdAy** [comment]
> try `import 'package:dio/dio.dart' hide Headers;`

Good job!
