### ISSUE TITLE
Add 'BaseOptions' as an annotation to have the ability to override default dio options

### ISSUE THREAD

**Issue by devmuaz** [trevorwang/retrofit.dart#516]
🔸 **What's missing**
I recently tried to make changes to the baseOptions property in the dio (which is used by retrofit), I was not able to find a proper way to achieve such behavior.

🔸 **Usecase**
At some point, I wanted to change the options of dio which I already setup at app initialization (basically, not changing main dio options, but overriding default values at each request), so I could for instance change timeout values, which currently I don't have control over them.

🔸 **What it could be**
It would be better if we have some sort of special annotation that can take an argument of type BaseOptions as a function argument, in which then retrofit takes this options and combine it with the default existing one in the dio.

🔸 **Code samples**
```dart
abstract class Api {
  @GET('some/api/path')
  Future<void> getInfo(
    @Options() BaseOptions options,
  );
}

 class GeneratedCode implements Api {
  Future<void> getInfo(BaseOptions options) async {
    // Compose `options` with `dio options`, which in this case
    // will override the dio options to the new one in this function's
    // argument
  }
}
```

I don't know if this is actually achievable or not, but it would save lives SERIOSLY!!

Looking forward to read your opinion

**Comment by DelcoigneYves** [comment]
I am looking for this as well, for customising timeouts on a specific API call, would be very helpful!

**Comment by devmuaz** [comment]
Hey @DelcoigneYves,

Now you use the options as follow

```dart
abstract class Api {
  @GET('some/api/path')
  Future<void> getInfo(
    @DioOptions() Options options,
  );
}
```

or 

```dart
abstract class Api {
  @GET('some/api/path')
  Future<void> getInfo(
    @DioOptions() RequestOptions options,
  );
}
```

**Comment by DelcoigneYves** [comment]
I had no idea this existed, thx!
