### ISSUE TITLE
Support Dart-Define

### ISSUE THREAD

**Issue by a1573595** [trevorwang/retrofit.dart#523]
Support Dart-Define to dynamically set port or part of the path(token、key...).

```
flutter run --dart-define=port=1234
```

```dart
@RestApi(baseUrl: 'https://xxxxxx')
abstract class ApiClient {
  @POST(":${String.fromEnvironment('port')}/api/v1/login")
  Future<LoginRes> login(@Body() LoginReq req);
}
```

I don't want to use the injectable package because it depended on the get_it state management library.

**Comment by trevorwang** [comment]
How about using the baseUrl as a parameter?

You can pass any kind of URLs then.

```dart
abstract class RestClient {
  factory RestClient(Dio dio, {String baseUrl}) = _RestClient;
}
```

**Comment by a1573595** [comment]
> 

Thanks for the response, 
baseUrl is fixed in my project,
but the port or part of the path(token、key...) is variable, 
Is there a way to do this dynamically?

**Comment by trevorwang** [comment]
use your baseUrl + port.  as new baseUrl, then pass it to RestClient

For other scenarios, please use dio interceptors.

**Comment by a1573595** [comment]
> 

Ok, thanks for replying.
