### ISSUE TITLE
null' is not a subtype of type 'string' in Post MultiPart

### ISSUE THREAD

**Issue by yusifahmadov** [trevorwang/retrofit.dart#527]
<img width="436" alt="Screenshot 2022-12-03 at 10 57 29" src="https://user-images.githubusercontent.com/77955404/205429201-c5c7b54c-568e-403f-ace0-7c53ec3219f8.png">

Hello, i want to set some fields dynamic, but i got error like this 'null is not subtype of type 'string''. How can i fix it?
Is it possible to send null data together File?

**Comment by OmarYehiaDev** [comment]
I have the same issue too and can't resolve it

**Comment by trevorwang** [comment]
Please add `?` after the type like which you put after the File

**Comment by yusifahmadov** [comment]
If you want to send null to any field, just use "".
"username": null -> "username": "". It is working for me.
`@Part(name: "username") String userName`
