### ISSUE TITLE
toJson() method have to add to MultipartFile

### ISSUE THREAD

**Issue by Carapacik** [trevorwang/retrofit.dart#529]
With this input I get an error:
`Exception: toJson() method have to add to MultipartFile`
```dart
  @MultiPart()
  @PATCH('/api/Recipe/{id}/edit')
  Future<void> editRecipe({
    @Path('id') required int id,
    @Part(name: 'Title') required String title,
    @Part(name: 'RecipeImage') required MultipartFile recipeImage,
  });
```  
However, if you insert a `List<MultipartFile>`, then everything goes well.

**Expected behavior**
What if instead of this code on `List<MultipartFile>`:
```dart
_data.files.addAll(recipeImage.map((i) => MapEntry('RecipeImage', i)));
```
Generate code on a regular `MultipartFile`:
```dart
_data.fields.add(MapEntry( 'RecipeImage',  recipeImage));
```

**Comment by Carapacik** [comment]
#464

**Comment by OmarYehiaDev** [comment]
@Carapacik Nothing new about a solve to this issue? @trevorwang

**Comment by Carapacik** [comment]
> @Carapacik Nothing new about a solve to this issue? @trevorwang

Try to replace **`MultipartFile`** to **`File`** (from dart:io)
```dart
  @MultiPart()
  @PATCH('/api/Recipe/{id}/edit')
  Future<void> editRecipe({
    @Path('id') required int id,
    @Part(name: 'Title') required String title,
    @Part(name: 'RecipeImage') required File recipeImage,
  });```

**Comment by omi-tutm** [comment]
> > [@Carapacik](https://github.com/Carapacik) Nothing new about a solve to this issue? [@trevorwang](https://github.com/trevorwang)
> 
> Try to replace **`MultipartFile`** to **`File`** (from dart:io)
> 
>   @MultiPart()
>   @PATCH('/api/Recipe/{id}/edit')
>   Future<void> editRecipe({
>     @Path('id') required int id,
>     @Part(name: 'Title') required String title,
>     @Part(name: 'RecipeImage') required File recipeImage,
>   });

@Carapacik I use Flutter web and don't have dart:io File — is there any way to handle this?

**Comment by brun0xon** [comment]
> > > [@Carapacik](https://github.com/Carapacik) Nothing new about a solve to this issue? [@trevorwang](https://github.com/trevorwang)
> > 
> > 
> > Try to replace **`MultipartFile`** to **`File`** (from dart:io)
> > [@multipart](https://github.com/multipart)()
> > [@patch](https://github.com/patch)('/api/Recipe/{id}/edit')
> > Future editRecipe({
> > [@path](https://github.com/path)('id') required int id,
> > [@part](https://github.com/part)(name: 'Title') required String title,
> > [@part](https://github.com/part)(name: 'RecipeImage') required File recipeImage,
> > });
> 
> [@Carapacik](https://github.com/Carapacik) I use Flutter web and don't have dart:io File — is there any way to handle this?

@omi-tutm just use `List<MultipartFile>` and pass collection with single file
