### ISSUE TITLE
Is it possible to migrate dependencies from dio to diox? Or is there a plan to do so?

### ISSUE THREAD

**Issue by ykaito21** [trevorwang/retrofit.dart#534]
https://github.com/flutterchina/dio/issues/1608#issue-1502019874
It looks like the Dio package has not been actively maintained recently.

**Comment by saharvx9** [comment]
Pls change it

**Comment by yairsts** [comment]
Please 🙏🏻

**Comment by SebastianKlaiber** [comment]
The membership is transferred, and the package is maintained again. https://pub.dev/packages/dio

**Comment by ykaito21** [comment]
> The membership is transferred, and the package is maintained again. https://pub.dev/packages/dio

The problem seems to be solved!
Hope retrofit will support the latest version of dio
