### ISSUE TITLE
What do you plan to do when Dio is deprecated?

### ISSUE THREAD

**Issue by emintolgahanpolat** [trevorwang/retrofit.dart#537]
@wendux, one of the dio developers, said he won't be maintaining the dio library. Do you plan to develop a version of the Retrofit library that works with the http library? I don't think the Chopper library is as functional as Retrofit.

**Comment by trevorwang** [comment]
Dio should be replaced seamlessly by https://github.com/cfug/diox.

Pull request is appreciated.

**Comment by gauravmehta13** [comment]
https://github.com/trevorwang/retrofit.dart/pull/538

**Comment by emintolgahanpolat** [comment]
Thanks @trevorwang. I didn't know about the Diox library.

Thanks @gauravmehta13 for supporting open source. It's a fast development.

**Comment by trevorwang** [comment]
😭

**Comment by trevorwang** [comment]
Get the notice just after I merge the PR.
