### ISSUE TITLE
using dio 5.0 does not format body properly

### ISSUE THREAD

**Issue by serendipity1004** [trevorwang/retrofit.dart#544]
**Describe the bug**
Using dio 4.x and retrofit 3.x was fine but when I migrate to dio 5.x and retrofit 4.x body does not get formatted properly when sending request.

**To Reproduce**
create json model like below

```dart
/*
* {
*   "basket": [
*     {
*       PatchBasketBodyBasket
*     }
*   ]
* }
* */

@JsonSerializable()
class PatchBasketBody {
  final List<PatchBasketBodyBasket> basket;

  PatchBasketBody({
    required this.basket,
});

  Map<String, dynamic> toJson() => _$PatchBasketBodyToJson(this);
}

@JsonSerializable()
class PatchBasketBodyBasket {
  final String productId;
  final int count;

  PatchBasketBodyBasket({
    required this.productId,
    required this.count,
  });

  factory PatchBasketBodyBasket.fromJson(Map<String, dynamic> json)
  => _$PatchBasketBodyBasketFromJson(json);

  Map<String, dynamic> toJson() => _$PatchBasketBodyBasketToJson(this);
}
```

create repository like below

```dart
  @PATCH('/basket')
  @Headers({
    'accessToken': 'true',
  })
  Future<List<BasketItemModel>> patchBasket({
    @Body() required PatchBasketBody body,
  });
```

it does not call toJson() and create JSON body but it sends body like below

```dart
{ basket: "Instance of 'PatchBasketBodyBasket'" }
```
body is just stringified.

when I change dio version to 4.x and matching retrofit version, it works perfectly fine.

I am suspecting that it is an issue with content type update merged in the recent version 
https://github.com/cfug/dio/issues/1653

**Expected behavior**
I would expect the body to be correctly parsed to JSON

**Comment by jnelle** [comment]
@trevorwang any feedback? I also faced the same issue

**Comment by trevorwang** [comment]
Does it work on latest retrofit?  @woogi-kang

**Comment by trevorwang** [comment]
free free to reopen it if it still exists.

**Comment by hrafnthor** [comment]
@trevorwang This seems to still be an issue when using the latest `retrofit` version (as of recording `4.0.3`). Any ideas what might be done to remedy the situation?
