### ISSUE TITLE
Package no longer stable after dio 5

### ISSUE THREAD

**Issue by gauravmehta13** [trevorwang/retrofit.dart#545]
There are several issues while calling API here and there,
The API calls that were working fine earlier and are working fine In postman are giving error now.

I have reverted my complete code to dio 4.0.6 and retrofit 3.3.1
hope this gets fixed soon

**Comment by jnelle** [comment]
just switch to chopper, this guy is ignoring the community

**Comment by trevorwang** [comment]
Thanks for your feedback.
I don't have enough time in the coming weeks. So PRs are appreciated.

**Comment by trevorwang** [comment]
Thanks for your feedback.
I don't have enough time in the coming weeks. So PRs are appreciated.

**Comment by gauravmehta13** [comment]
@jnelle  Is chopper having same functionalities like retrofit?

**Comment by dhaval-k-simformsolutions** [comment]
Do we have any update on this @trevorwang ?

**Comment by trevorwang** [comment]
It works with latest dio now.  Feel free to reopen it.
