### ISSUE TITLE
your client has issued a malformed or illegal request. on GET request

### ISSUE THREAD

**Issue by hibbert-de** [trevorwang/retrofit.dart#547]
When I want to do a normal get request, i got an 400 error from the server: "your client has issued a malformed or illegal request.".

if i use the normal Dio get request everything is working fine:
```
Dio dio = Dio();
Response res = await dio.get("https://my-server.de/test?test=true");
```
but when i use Retrofit generator, i got this error message:  "your client has issued a malformed or illegal request.".
```
part 'MyClient.g.dart';
abstract class MyClient {
 factory MyClient(Dio dio, {String baseUrl}) = _MyClient;
///...
@GET("https://my-server.de/test)
Future<myResponseDTO> test({@Query("test") bool test});
```
the generated file:
```
 @override
  Future<myResponseDTO> test({required test}) async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{r'test': test};
    final _headers = <String, dynamic>{};
    final _data = <String, dynamic>{}; // <--- this should be null in a GET request
 final _result = await _dio.fetch<List<dynamic>>(
        _setStreamType<myResponseDTO>(Options(
      method: 'GET',
      headers: _headers,
      extra: _extra,
    )
            .compose(
              _dio.options,
              '/test',
              queryParameters: queryParameters,
              data: _data, // <-- or this must be removed in GET request
            )
            .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl)));
```
my only workaround is to add an optional Body with null value:
```
@GET("https://my-server.de/test)
Future<myResponseDTO> test({@Query("test") bool test, @Body() String? bla,});
```
is there a better solution, or did i missed some config properties, saying: body in GET requests are always null?
i generate the files with this command in flutter root dir:
` flutter pub run build_runner build` or `flutter pub run build_runner build --delete-conflicting-outputs`, same result
```
dependencies:
  flutter:
    sdk: flutter
  retrofit: ^4.0.1
  dio: ^5.0.1
dev_dependencies:
  retrofit_generator: ^5.0.0
```

[✓] Flutter (Channel stable, 3.7.3, on macOS 13.2 22D49 darwin-x64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by trevorwang** [comment]
closed due to pr #549
