### ISSUE TITLE
Build Bug

### ISSUE THREAD

**Issue by ValerioLeite** [trevorwang/retrofit.dart#55]
In comand : `flutter pub run build_runner build`

Error:
`[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
[SEVERE] /D:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/retrofit_generator-0.6.3/lib/src/generator.dart:499:38: Error: Getter not found: 'UploadFileInfo'.      final uploadFileInfo = refer('$UploadFileInfo')                                     ^^^^^^^^^^^^^^/
D:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/retrofit_generator-0.6.3/lib/src/generator.dart:499:38: Error: The getter 'UploadFileInfo' isn't defined for the class 'RetrofitGenerator'. - 'RetrofitGenerator' is from 'package:retrofit_generator/src/generator.d
art' ('/D:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/retrofit_generator-0.6.3/lib/src/generator.dart').Try correcting the name to the name of an existing getter, or defining a getter or field named 'UploadFileInfo'.      final uploadFileInfo = refer('$Upload
FileInfo')                                     ^^^^^^^^^^^^^^
pub failed (78)
`

**Comment by trevorwang** [comment]
Please refer to #53

**Comment by ValerioLeite** [comment]
Thank you =)
