### ISSUE TITLE
Dio error after introducing null data object in `5.0.0+1`

### ISSUE THREAD

**Issue by behnamsattar** [trevorwang/retrofit.dart#562]
With version '5.0.0+1', there is a change where data objects are set to null when they are empty. This is breaking my code due to causing an error on Dio side with the following message:
```
DioError [DioErrorType.other]: type 'Null' is not a subtype of type 'Object'
```

**Comment by chaeMil** [comment]
@behnamsattar [This PR](https://github.com/trevorwang/retrofit.dart/pull/561) is fixing it in the generator. CC @trevorwang
