### ISSUE TITLE
How to save dio instance with factory constructor?

### ISSUE THREAD

**Issue by moshe5745** [trevorwang/retrofit.dart#574]
Hi, can anyone explain how I can save the Dio instance in the constructor of retrofit?
`  factory ApiClient(Dio dio, {String baseUrl}) = _ApiClient;
`
This is the syntax from docs. Couldn't figure out how to do it.

**Comment by trevorwang** [comment]
@moshe5745  Please refer here https://github.com/trevorwang/retrofit.dart#use-it

And @basselalsayed 's implement is also the correct way to archive this.

**Comment by trevorwang** [comment]
Just close it  and feel free to open it if any question
