### ISSUE TITLE
More convenient mock integration.

### ISSUE THREAD

**Issue by moshe5745** [trevorwang/retrofit.dart#575]
I am trying to mock my HTTP requests. Right now I am using http_mock_adapter. The first problem I have is that I don't know how to save Dio instance in the retrofit constructor. Opened a separate issue for that: https://github.com/trevorwang/retrofit.dart/issues/574

The second issue is that I need to declare the paths in consts, so I can use them in my mock logic.
```dart
const pathToken = "/token";

@RestApi(
    baseUrl: String.fromEnvironment('BASE_URL'))
abstract class ApiClient {
  factory ApiClient(Dio dio, {String baseUrl}) = _ApiClient;

  @POST(pathToken)
  Future<IToken> token(...);

class HttpMockingService {
  late DioAdapter dioAdapter;

  HttpMockingService(Dio dio) {
    dioAdapter = DioAdapter(dio: dio, matcher: const UrlRequestMatcher());

    dioAdapter.onPost(
        pathToken,
        (request) => request.reply(
            200,
            IToken(
                token_type: "bearer",
                expires_in: 259199999,
                access_token: token)));
```
The best solution I could think of is that the mocks would be a part of the plugin and could be used like this:

```dart
  @POST('/token')
  Future<IToken> token(...);
@MOCK((request) => request.reply(200, {...some data...}))
```
I don't know if it is suitable for the plugin architecture, so any other solution that would decrease the boilerplate would be appreciated.

Thanks.

**Comment by trevorwang** [comment]
You can define a dio instance by following the docs here.
https://github.com/trevorwang/retrofit.dart#use-it  
Then you can access it and do any thing about dio
