### ISSUE TITLE
Data class generated by freezed cannot be used in return variables.

### ISSUE THREAD

**Issue by TimestampWombat** [trevorwang/retrofit.dart#578]
**Describe the bug**
When I use the `Dog` class which is generated by `freezed` library as the return generic type in `RestClient` method, the generated `rest_client.g.dart` file will generate error `InvalidType` type.

**To Reproduce**
1. `data.dart` 
```
import 'package:freezed_annotation/freezed_annotation.dart';

part 'data.freezed.dart';
part 'data.g.dart';

@freezed
class Animal with _$Animal {
  factory Animal.dog() = Dog;

  factory Animal.fromJson(Map<String, dynamic> json) => _$AnimalFromJson(json);
}
```
2. `rest_client.dart`
```
import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';

import 'data.dart';

part 'rest_client.g.dart';

@RestApi(baseUrl: "https://example.com")
abstract class RestClient {
  factory RestClient(Dio dio, {String baseUrl}) = _RestClient;

  @GET("/dogs")
  Future<Dog> getDogs();
}
```
3. after running `dart run build_runner build`, the generated `rest_client.g.dart` as below:
```
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'rest_client.dart';

// **************************************************************************
// RetrofitGenerator
// **************************************************************************

// ignore_for_file: unnecessary_brace_in_string_interps,no_leading_underscores_for_local_identifiers

class _RestClient implements RestClient {
  _RestClient(
    this._dio, {
    this.baseUrl,
  }) {
    baseUrl ??= 'https://example.com';
  }

  final Dio _dio;

  String? baseUrl;

  @override
  Future<InvalidType> getDogs() async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _headers = <String, dynamic>{};
    final Map<String, dynamic>? _data = null;
    final _result = await _dio
        .fetch<Map<String, dynamic>>(_setStreamType<InvalidType>(Options(
      method: 'GET',
      headers: _headers,
      extra: _extra,
    )
            .compose(
              _dio.options,
              '/dogs',
              queryParameters: queryParameters,
              data: _data,
            )
            .copyWith(baseUrl: baseUrl ?? _dio.options.baseUrl)));
    final value = InvalidType.fromJson(_result.data!);
    return value;
  }

  RequestOptions _setStreamType<T>(RequestOptions requestOptions) {
    if (T != dynamic &&
        !(requestOptions.responseType == ResponseType.bytes ||
            requestOptions.responseType == ResponseType.stream)) {
      if (T == String) {
        requestOptions.responseType = ResponseType.plain;
      } else {
        requestOptions.responseType = ResponseType.json;
      }
    }
    return requestOptions;
  }
}
```
the expected `Dog` type became to `InvalidType`.

**Expected behavior**
Hope the freezed generated type can be used as return type.

**smallest reproducible example zip file**
[freezed_for_retrofit_issue.zip](https://github.com/trevorwang/retrofit.dart/files/11664438/freezed_for_retrofit_issue.zip)

**Comment by TimestampWombat** [comment]
The issue is related to multiple generators' build order.
[related issue dart/lang#2701](https://github.com/dart-lang/build/issues/2701#issue-621152368)

**Comment by TimestampWombat** [comment]
Although It feels a little awkward to fork a generator library just for the generators' running order, the problem should be solved by dart team. 
IMAO, since `freezed` library is so popular, there is good enough reason to include it to the `generator/build.yaml`.

**Comment by trevorwang** [comment]
Here's  the solution for you https://github.com/trevorwang/retrofit.dart/pull/571#issue-1712263259

add the following configuration in your build.yaml file

```yaml
global_options:
  freezed:
    runs_before:
    - json_serializable
  json_serializable:
    runs_before:
    - retrofit_generator
 ```

**Comment by TimestampWombat** [comment]
> Here's the solution for you [#571 (comment)](https://github.com/trevorwang/retrofit.dart/pull/571#issue-1712263259)
> 
> add the following configuration in your build.yaml file
> 
> ```yaml
> global_options:
>   freezed:
>     runs_before:
>     - json_serializable
>   json_serializable:
>     runs_before:
>     - retrofit_generator
> ```

Thanks for your help!
