### ISSUE TITLE
Allow base url switching during runtime

### ISSUE THREAD

**Issue by gfranks** [trevorwang/retrofit.dart#6]
When constructing the RestApi annotation, which is **required** after some testing, you must specify a `baseUrl`. After creating your RestClient instance, you modify the `dio.baseUrl` to use the annotated `baseUrl`. Could you also have a priority to use the `baseUrl` already set on the `dio` instance? 

I have always built in an environment switch into all of my apps so testers or developers can quickly change environments without having to re-build and then re-deploy.

For the time being, a workaround would be:
```
static RestClient _instance(Dio dio) {
    final String baseUrl = dio.options.baseUrl;
    _ RestClient service = _ RestClient(dio);
    service._dio.options.baseUrl = baseUrl;
    return service;
}
```

Much appreciated.

**Comment by trevorwang** [comment]
Won't set baseUrl  if the base url from the annotation is not set.

**Comment by gfranks** [comment]
Thanks Trevor, however, this is incorrect. Here's a snippet of the generated code. Let me know if I am doing this incorrectly but still seems to be an issue to me.

Annotated Class:
```
@RestApi()
abstract class RestClient {
    ...
}
```

Generated Code:
```
_ RestClient([Dio dio]) {
    _dio = dio;
    if (_dio == null) {
      _dio = Dio();
    }
    _dio.options.baseUrl = '/'; <----- this line should not exist for an empty base url
}
```

**Comment by gfranks** [comment]
@trevorwang I did not see your commit to allow an empty base url. Thanks for the update!
