### ISSUE TITLE
How to receive a Multipart response?

### ISSUE THREAD

**Issue by shubhamsinghshubham777** [trevorwang/retrofit.dart#601]
I am converting an existing Android app to a Flutter app and in the Android app, I have the following piece of code:
```java
import javax.mail.internet.MimeMultipart;

import retrofit.client.Response;
import retrofit.http.Body;
import retrofit.http.GET;
import retrofit.http.POST;
import retrofit.http.Query;
import rx.Observable;

public interface UpdatesApi {

    String PATH_UPDATES = "/bb/updates";

    @POST(PATH_UPDATES)
    Observable<MimeMultipart> get(@Body UpdatesRequestBody body);

    @GET(PATH_UPDATES)
    Observable<Response> check(@Query("firmware") String firmware, @Query("hardware") String hardware);

    class UpdatesRequestBody {
        public final String hardware;
        public final String firmware;

        public UpdatesRequestBody(String hardware, String firmware) {
            this.hardware = hardware;
            this.firmware = firmware;
        }
    }
}
```

I want to write the same thing in Flutter but I'm not sure how to do so.

In `Postman`, for this POST request, I'm receiving the file data (details below), I'm also able to get a List<int> giving me all the response bytes, but I'm not able to convert those bytes into a Multipart file and consume its sections.

My current implementation using Retrofit:
```dart
part 'puck_updates_api.g.dart';

@RestApi(baseUrl: EnvironmentVariables.apiBaseUrl)
abstract class PuckUpdatesApi {
  static const String _apiPath = "updates";

  factory PuckUpdatesApi(Dio dio, {String baseUrl}) = _PuckUpdatesApi;

  @POST(_apiPath)
  @DioResponseType(ResponseType.bytes)
  Future<HttpResponse<List<int>>> getUpdateFileBytes(
    @Body() PuckUpdatesRequestBody puckUpdatesRequestBody,
  );

  @GET(_apiPath)
  Future<HttpResponse<PuckUpdateAvailability>> getIsUpdateAvailable(
    @Query("firmware") firmwareVersion,
    @Query("hardware") hardwareVersion,
  );
}
```

In the `Postman` response (https://pastebin.com/RfmqwLf5), I can see there is a `manifest` file, and some `.dat` and `.bin` files. The context is that this is a BLE DFU file expected to be used with the [nordic_dfu](https://pub.dev/packages/nordic_dfu) library by converting whatever response I'm getting from the network call into a valid `.zip` file.

Any ideas are appreciated. Thanks in advance 🌟

**Comment by trevorwang** [comment]
I think there's no MimeMultipart here in dart, so you have to get it as zip file and  then handle it later.

**Comment by shubhamsinghshubham777** [comment]
Right.. I had to create a manual parser for my particular case. We can close this issue if there's nothing else we can discuss about this topic.

**Comment by trevorwang** [comment]
I close this issue and feel free to reopen it any time
