### ISSUE TITLE
RestApi的 baseUrl参数感觉可有可无

### ISSUE THREAD

**Issue by Dboy233** [trevorwang/retrofit.dart#603]
Dio 中可以设置 baseUrl,那通过注解RestApi中设置的 baseUrl 的作用又是什么呢。我能想到的就是将 API 通过模块进行区分。好像也没别的了。

**Comment by jiechic** [comment]
某些公司的模型是，不同资源使用不同的域名的。

**Comment by trevorwang** [comment]
总有需求需要自定义 url
