### ISSUE TITLE
[WARNING] retrofit_generator on retrofit @RestApi() must provide a toJson() method which return a Map

### ISSUE THREAD

**Issue by lucasdidur** [trevorwang/retrofit.dart#607]
Reopen of #577.

Still not fixed

**Comment by mister-rao** [comment]
Did you find any resolution for this?

**Comment by mister-rao** [comment]
this works:

https://github.com/trevorwang/retrofit.dart/issues/609#issuecomment-1714847188

**Comment by trevorwang** [comment]
Please upgrade to latest version of generator. Feel free to reopen it if it's still not working..
