### ISSUE TITLE
Retrofit with Freezed don't have toJson

### ISSUE THREAD

**Issue by VladislavYakonyuk** [trevorwang/retrofit.dart#609]
Hi, I'm having a problem with generating retrofit and freezed. Retrofit is complaining that the DTO model does not have toJSON

```bash
[WARNING] retrofit_generator:retrofit on lib/src/features/auth/src/api/auth_api_client.dart:
LoginRequestDto must provide a `toJson()` method which return a Map.
```

```dart
...
  @POST("/auth/login/")
  Future<LoginResponseDto> login({
    @Body() required LoginRequestDto body
  });
}

@freezed
class LoginRequestDto with _$LoginRequestDto {
  const factory LoginRequestDto({
    required String username,
    required String password
  }) = _LoginRequestDto;

  factory LoginRequestDto.fromJson(Map<String, dynamic> json) =>
      _$LoginRequestDtoFromJson(json);
}
```

```dart
// generator file

/// @nodoc
mixin _$LoginRequestDto {
  String get username => throw _privateConstructorUsedError;
  String get password => throw _privateConstructorUsedError;

  Map<String, dynamic> toJson() => throw _privateConstructorUsedError;
  @JsonKey(ignore: true)
  $LoginRequestDtoCopyWith<LoginRequestDto> get copyWith =>
      throw _privateConstructorUsedError;
}
```

Maybe I'm doing something wrong?

**Comment by vulpeep** [comment]
Have you added the `.g.dart` part to your DTO file?
```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'login_request_dto.freezed.dart';
part 'login_request_dto.g.dart';

@freezed
class LoginRequestDto with _$LoginRequestDto {
  const factory LoginRequestDto(
      {required String username, required String password}) = _LoginRequestDto;

  factory LoginRequestDto.fromJson(Map<String, dynamic> json) =>
      _$LoginRequestDtoFromJson(json);
}
```
With this code, I don't encounter the warning that you are receiving.

**Comment by trevorwang** [comment]
please refer to https://pub.dev/packages/freezed#fromjsontojson

**Comment by BetterB0y** [comment]
Its not working. retrofit_generator is not using toJson

**Comment by thang510023** [comment]
**Hi @BetterB0y I tried it and it works, add it at the end of the build.yaml file, maybe it will help you**

`build.yaml`

```
global_options:
  freezed:
    runs_before:
      - json_serializable
  json_serializable:
    runs_before:
      - retrofit_generator
```

**Comment by BetterB0y** [comment]
It works. Thank you. @trevorwang Can we add this somewhere in documentation?

**Comment by iamriajul** [comment]
> **Hi @BetterB0y I tried it and it works, add it at the end of the `build.yaml` file, maybe it will help you**
> 
> `build.yaml`
> 
> ```
> global_options:
>   freezed:
>     runs_before:
>       - json_serializable
>   json_serializable:
>     runs_before:
>       - retrofit_generator
> ```

This solution didn't work for me, it is saying: 
`[WARNING] Invalid builder key `retrofit_generator:retrofit_generator` found in global_options config of build.yaml. This configuration will have no effect.`

**Comment by iamriajul** [comment]
> > **Hi @BetterB0y I tried it and it works, add it at the end of the `build.yaml` file, maybe it will help you**
> > `build.yaml`
> > ```
> > global_options:
> >   freezed:
> >     runs_before:
> >       - json_serializable
> >   json_serializable:
> >     runs_before:
> >       - retrofit_generator
> > ```
> 
> This solution didn't work for me, it is saying: `` [WARNING] Invalid builder key `retrofit_generator:retrofit_generator` found in global_options config of build.yaml. This configuration will have no effect. ``

Fixed it by upgrading to `retrofit_generator: ^7.0.2`.
Thanks.
