### ISSUE TITLE
Generation Issue with Nested Lists in Retrofit for Dart

### ISSUE THREAD

**Issue by vulpeep** [trevorwang/retrofit.dart#610]
I'm encountering an issue with Retrofit's code generation for Dart when dealing with nested lists. This issue seems to be related to a previously reported issue [#262](https://github.com/trevorwang/retrofit.dart/issues/262), which was closed without a resolution.

Specifically, I have tried two different approaches, and both lead to incorrect code generation:

1. **Using Nested Lists Directly:**
   I tried using a `Future<ApiResponse<List<List<MyEntity>>>>`, but encountered the error:
   ```
   Error: Couldn't find constructor 'List.fromJson'.
   ```

2. **Using Wrapper Class:**
   To circumvent the above issue, I tried wrapping the inner list inside a class:
   ```dart
   class MyListWrapper {
     final List<MyEntity> items;

     MyListWrapper(this.items);

     factory MyListWrapper.fromJson(List<dynamic> json) {
       return MyListWrapper(
         json.map((e) => MyEntity.fromJson(e as Map<String, dynamic>)).toList(),
       );
     }
   }
   ```
   ```dart
   @GET('/path/to/endpoint')
   Future<ApiResponse<List<MyListWrapper>>> getItems();
   ```

   However, the generated code seems to be incorrect, treating each item in the JSON list as `Map<String, dynamic>` while `MyListWrapper.fromJson` expects `List<dynamic>`:
   ```dart
   final value = ApiResponse<List<MyListWrapper>>.fromJson(
     _result.data!,
     (json) => json is List<dynamic>
         ? json
             .map<MyListWrapper>((i) =>
                 MyListWrapper.fromJson(i as Map<String, dynamic>))
             .toList()
         : List.empty(),
   );
   ```

**Environment:**
- Dart SDK version: 3.0.5
- Flutter version: 3.10.5
- retrofit version: 4.0.1
- retrofit_generator version: 7.0.8
- OS: Windows 11

This issue is causing a roadblock in my project, and I am unable to find a workaround. Since this topic was previously brought up but closed without a clear resolution, I would greatly appreciate any assistance or guidance on how to properly handle nested lists with Retrofit.

**Comment by vulpeep** [comment]
I managed to resolve the issue with nested lists by introducing a specialized class for handling API responses containing nested lists.

Here's my original `ApiResponse` class:

```dart
@Freezed(genericArgumentFactories: true, fromJson: true)
sealed class ApiResponse<T> with _$ApiResponse<T> {
  const factory ApiResponse.data(T data) = ApiResponseData;
  const factory ApiResponse.errors(List<String> errors) = ApiResponseErrors;

  factory ApiResponse.fromJson(
    Map<String, dynamic> json,
    T Function(Object?) fromJsonT,
  ) {
    String runtimeType = 'errors';
    if (json['success'] == true) {
      runtimeType = 'data';
    }
    json['runtimeType'] = runtimeType;
    return _$ApiResponseFromJson(json, fromJsonT);
  }
}
```

And here's the modified class, `ApiResponseNestedList`, specifically designed for handling nested lists:

```dart
@Freezed(genericArgumentFactories: true, fromJson: true)
sealed class ApiResponseNestedList<T> with _$ApiResponseNestedList<T> {
  const factory ApiResponseNestedList.data(List<T> data) =
      ApiResponseNestedListData;
  const factory ApiResponseNestedList.errors(List<String> errors) =
      ApiResponseNestedListErrors;

  factory ApiResponseNestedList.fromJson(
    Map<String, dynamic> json,
    T Function(Object?) fromJsonT,
  ) {
    String runtimeType = 'errors';
    if (json['success'] == true) {
      runtimeType = 'data';
    }
    json['runtimeType'] = runtimeType;
    return _$ApiResponseNestedListFromJson(json, fromJsonT);
  }
}
```

This approach seems to handle the nested list scenario correctly. I'm sharing this here in case others encounter a similar issue.

**Comment by trevorwang** [comment]
close it due to beding resolved.
