### ISSUE TITLE
File does not upload when using @Field() File avatar, but works when using @Field()  MultipartFile avatar and passing: MultipartFile.fromFileSync(avatar.path)

### ISSUE THREAD

**Issue by iamriajul** [trevorwang/retrofit.dart#62]
**Describe the bug**
File does not upload when using @Field() File avatar, but works when using @Field()  MultipartFile avatar and passing: MultipartFile.fromFileSync(avatar.path)

**To Reproduce**
pass a file to retrofit api method @Field() File avatar; parameter.

**Expected behavior**
passing File to retrofit should upload the file to the server. but it doesn't.

**Smartphone (please complete the following information):**
 - Device: Emulator
 - OS: Android Oreo 28 API Level
 - Version 28 API Level

**Comment by trevorwang** [comment]
Could you provide the error message?

**Comment by iamriajul** [comment]
There is no error being thrown by Retrofit, but my server returning there is no file in the body.
My Server Response when using @Field() File avatar:
It is Laravel validation message.
`{
  "message": "The given data was invalid.",
  "errors": {
    "avatar": [
      "The avatar field is required."
    ]
  }
}`
Current Solution I'm using:
Using parameter @Field() Multipart File avatar and passing MultipartFile.fromFileSync(); File is being uploaded smoothly.

**Comment by RakaAlrian** [comment]
Hello, is there any sample or documentation about uploading file or files? I don't find it in readme. Thanks
