### ISSUE TITLE
please use analyzer 6.0

### ISSUE THREAD

**Issue by neiljaywarner** [trevorwang/retrofit.dart#620]
using freezed 2.4.2 gives
Because retrofit_generator >=4.1.1 <6.0.0 depends on analyzer >=4.7.0 <6.0.0 and freezed >=2.4.2 depends on analyzer ^6.0.0, retrofit_generator >=4.1.1 <6.0.0 is incompatible with freezed >=2.4.2.
So, because dths depends on both freezed 2.4.2 and retrofit_generator ^5.0.0, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on freezed: flutter pub add freezed:^2.4.1

**Comment by trevorwang** [comment]
It should be working.   Please remove pubspec.lock file and run `dart pub get` again.
