### ISSUE TITLE
Does retrofitGenerator not support multipartFile?

### ISSUE THREAD

**Issue by jihanga** [trevorwang/retrofit.dart#621]
I see this issue.
https://github.com/trevorwang/retrofit.dart/issues/612

My request is similar to this, but a little different.
I'm implementing the action of uploading a list of files.
The mime of each file may be different (video, photo, music, etc.), so I want to define the content-type of those files separately.
```dart
@POST('api/files')
@MultiPart()
@Headers(<String, dynamic>{
  "accept": "*/*",
  "Content-Type": "multipart/form-data",
})
Future<String> uploadFile({
  @Part() required List<MultipartFile> fileList,
});
```
If you define it like this and run the retrofit generator 
```
[SEVERE] retrofit_generator on lib/data/file_api.dart:

Exception: toJson() method have to add to MultipartFile
```

An error occurs such as . 
Does retrofit not support MultipartFile?
I don't know if it's something that requires additional features or if I don't even know how to deal with it. If anyone knows, I'd appreciate it if you could answer.

Additionally, I wonder if it is possible to use `dio` directly without using retrofit to do this if this behavior is not done with retrofit.

**Comment by jihanga** [comment]
It's my mistake... I tried again and it worked fine.
I don't know why I was mistaken

**Comment by trevorwang** [comment]
feel free to reopen if it occurs again.
