### ISSUE TITLE
to GET a List of objects, do i really have to create an extra dummy class and convert later to a List again?

### ISSUE THREAD

**Issue by hansbak** [trevorwang/retrofit.dart#625]
**Describe the feature?**
A clear and concise description of what the question is.

I am just starting retrofit,
i like to get a list of objects with a GET REST call which return a list of objects and defined it as:
```
  @GET("/tasks")
  Future<List<Task>> getTasks();
```
The error i get:
Exception has occurred.
_TypeError (type '_Map<String, dynamic>' is not a subtype of type 'List<dynamic>?' in type cast)

According the readme at pub.dev i have to solve this with
``` 
@GET('/tasks_names')
  Future<TaskNames> getTaskNames();
and create the additional TaskNames class which i later have to convert back to List<Task>
```
and yes this works, however is this the only solution?
would be nice to get a list without the extra dummy class?

**Comment by trevorwang** [comment]
Something like `List<Task> ` should be working with retrofit.dart. please check whether the return data is a JSON array format for a JSON object

**Comment by hansbak** [comment]
Thanks for your answer,

i think i found the problem. My backend returns a list within a Map like {tasks: List<task>}

I tried to change the model (I use freezed) adding the map item "tasks"
to: 

factory Task.fromJson(Map<String, dynamic> json) =>
      _$TaskFromJson(json["tasks"]);

that also did not help, 
you have a suggestion?

By the way you are looking to support an open source project(github profile), have a look at: https://github.com/growerp/growerp ?

**Comment by trevorwang** [comment]
And then you have to define a class like:

```dart
class Tasks {
    LIst<Task> tasks;
}
```

**Comment by hansbak** [comment]
thanks for your reply, however that means i need to create a class for every list i will receive...
but sure this works, thanks for your answer and the very useful package.
The project [growerp is now  ](https://github.com/growerp/growerp/tree/development) is now completely switched over to retrofit.
