### ISSUE TITLE
Extend Retrofit & Freezed Serialization with Custom fromJson for Generic Types

### ISSUE THREAD

**Issue by Okladnoj** [trevorwang/retrofit.dart#627]
**Is your feature request related to a problem? Please describe.**
Yes, when using Retrofit along with Freezed in Flutter, I am facing a challenge with handling generic types in my API response model. Specifically, I am unable to provide a custom `fromJson` method for a generic type when deserializing the JSON response. This becomes a bottleneck when trying to automate the serialization/deserialization process for various data models.

```dart
// Example of the API response model
@Freezed(genericArgumentFactories: true)
class ApiResponseModel<T> with _$ApiResponseModel<T> {
  const factory ApiResponseModel({
    @JsonKey(name: 'data') T? data,
  }) = _ApiResponseModel<T>;

  factory ApiResponseModel.fromJson(Map<String, dynamic> json, T Function(Object? json) fromJsonT) =>
      _$ApiResponseModelFromJson(json, fromJsonT);
}
```

**Describe the solution you'd like**
I would appreciate an option in Retrofit to specify a custom `fromJson` method for generic types on a per-method basis. This could be done by introducing a new annotation that can be used alongside `@GET`, `@POST`, etc., to specify the `fromJson` function for the generic type.

```dart
// Desired usage with Retrofit
@RestApi()
abstract class MyApi {
  @POST('/endpoint')
  @JsonFunc(fromJsonFunc: myCustomFromJson)
  Future<ApiResponseModel<MyModel>> fetchData();
  ...
}
```

**Describe alternatives you've considered**
I have considered creating custom converters for each data type, but this approach is not scalable and leads to a lot of boilerplate code. Also, I tried using mixins and factory constructors, but these solutions do not integrate well with Retrofit and Freezed, and make the code more complex.

**Additional context**
Handling generic types efficiently is crucial for reducing boilerplate and making the code more maintainable, especially in larger projects with many data models and API endpoints. Providing a way to specify the `fromJson` method on a per-method basis would allow for greater flexibility and ease of use when working with Retrofit and Freezed in Flutter projects.

**Comment by trevorwang** [comment]
I do understand that you want to find a flexible way to do the serialization/deserialization.  What I am confusing is that each `toJson` method  is implemented by yourself.  Did it not meet your requirement if you just give a customized implementation for special cases.

**Comment by Okladnoj** [comment]
Yes, I fully understand that each `fromJson` method is implemented by ourselves. However, the core issue here is that with the current approach, if we have a multitude of typed requests, we would need to create separate models and `fromJson` implementations for each. This will lead to a significant increase in boilerplate code, which violates the **DRY (Don't Repeat Yourself)** principle and makes code maintenance and extension more challenging in the future.

For instance, if we have dozens or even hundreds of different data types that could be returned through the API, we would have to create and maintain dozens or hundreds of different models and `fromJson` methods. This can quickly become impractical, especially in larger projects with numerous API endpoints and data types.

What I am proposing is a more flexible and scalable approach that would allow us to define a general `fromJson` method for handling generic types in our **API** response model, and then override this method on a per-method basis if specialized serialization/deserialization logic is required. This would reduce the amount of boilerplate code, simplify maintenance, and improve code reusability, which is a key aspect of effective programming.

My goal is to maximize code reuse and minimize duplication, creating a cleaner, more manageable, and extensible architecture. The utilization of Retrofit alongside **Freezed** in **Flutter** can be significantly enhanced by introducing the ability to specify a custom `fromJson` method for generic types on a per-method basis, as proposed in my feature request.

**Comment by Okladnoj** [comment]
The code snippets provided below demonstrate the current setup and the associated challenges. We have a generic `ApiWrapperModel` class designed to handle various types of data models (`ModelN1`, `ModelN2`, `ModelN3`, etc.), and a `TestRetrofitApi` class with multiple methods, each returning a different data model.

```dart
// File: api_wrapper_model.dart
import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'api_wrapper_model.freezed.dart';
part 'api_wrapper_model.g.dart';

@immutable
@Freezed(makeCollectionsUnmodifiable: false, genericArgumentFactories: true)
class ApiWrapperModel<T> with $ApiWrapperModel<T> {
const ApiWrapperModel.();

const factory ApiWrapperModel({
@JsonKey(name: 'success') @Default(false) bool success,
@JsonKey(name: 'message') @Default('') String message,
@JsonKey(name: 'data') T? data,
}) = _ApiWrapperModel<T>;

factory ApiWrapperModel.fromJson(
Map<String, dynamic> json,
T Function(Object?) fromJsonT,
) =>
_$ApiWrapperModelFromJson(json, fromJsonT);
}

// ... Other ModelN1, ModelN2, ... ModelN7 classes
```

```dart
// File: test_retrofit_api.dart
import 'package:dio/dio.dart';
import 'package:injectable/injectable.dart';
import 'package:retrofit/retrofit.dart';

import '../../../models/api/api_wrapper_model.dart';
import '../../constants/api_constants.dart';

part 'test_retrofit_api.g.dart';

@module
abstract class TestRetrofitApiModule {
@lazySingleton
TestRetrofitApi getInstance(Dio dio) {
return TestRetrofitApi(dio, baseUrl: ApiConstants.baseUrl);
}
}

@RestApi()
abstract class TestRetrofitApi {
factory TestRetrofitApi(Dio dio, {String baseUrl}) = _TestRetrofitApi;

@GET('/path1')
Future<ApiWrapperModel<ModelN1>> getMod1();

@GET('/path2')
Future<ApiWrapperModel<ModelN2>> getMod2();

@GET('/path3')
Future<ApiWrapperModel<ModelN3>> getMod3();

@GET('/path4')
Future<ApiWrapperModel<ModelN4>> getMod4();

@GET('/path5')
Future<ApiWrapperModel<ModelN5>> getMod5();

@GET('/path6')
Future<ApiWrapperModel<ModelN6>> getMod6();

@GET('/path7')
Future<ApiWrapperModel<ModelN7>> getMod7();
}
```

With the current setup, for every new data model, we need to create a new `ModelN` class and a corresponding `fromJson` method. However, the serialization logic for `ApiWrapperModel` remains the same. What we are looking for is a way to specify a custom `fromJson` method on a per-method basis within `TestRetrofitApi` to allow for more flexible serialization/deserialization, thus adhering to the DRY principle and reducing boilerplate.

The desired functionality would allow us to specify a custom `fromJson` method for each `GET` method in `TestRetrofitApi`, thereby reducing redundancy and improving code maintainability, especially in larger projects with many data models and API endpoints.

**Comment by trevorwang** [comment]
The main purpose of this project is to generate the boilerplate instead of manual.
Anyway, you can submit a PR and then we can discuss furture.

**Comment by TekExplorer** [comment]
why is this "to be discussed"? and why in the hell is this not an included feature?
i opted to use IList from `fast_immutable_collections`, where it has json_serializable support.
this
```dart
    final value = IList<ApiKey>.fromJson(_result.data!);
```
should be this
```dart
final value = IList<ApiKey>.fromJson(_result.data!, (json) => ApiKey.fromJson(json as Map<String, Object?>));
```
so why isnt it? why not 
- check if a type has a fromJson first
- if it has only one argument, pass it in `as` the argument's type
- if it has two and the second argument is a `T Function(Object?)` then it should pass in the inner-inner type's fromJson

**Comment by trevorwang** [comment]
Waiting for your contributions. I would be appreciated if there was new PR here.

**Comment by Okladnoj** [comment]
> There would be some misunderstanding here. I thought it would be discussed when PR's submitted.

I tried to figure it out... But I couldn’t solve this problem.  I have never worked on builders... Please tell me where and in what direction I should spend my efforts to solve the problem.  However, I’m still not sure what will happen (

**Comment by TekExplorer** [comment]
Had we been using json_serializable directly instead of freezed, it would have worked, but this was a bad way to do it.

**Comment by ekuleshov** [comment]
Could we get an example how genericArgumentFactories works with the retrofit-generated endpoints?
The merged PR doesn't have any tests or examples.

**Comment by ekuleshov** [comment]
Additionally it seems like the newly generated code can't handle generic types.

E.g. endpoint declared like this:

```
Future<Config<T>> config<T>(@Path('id') id);
```

gets the following generated code, which is obviously not going to work (also common types like `List`, `Map` or `String` instead of `T` probably also not going to work here:

```
Config<T>.fromJson(
      _result.data!,
      (json) => T.fromJson(json as Map<String, dynamic>),
    );
```

Generally it seems like the only way to address this is to declare the endpoint (optionally) with generic fromJson/toJson factories and have generator to wire them in the above call if they are specified.

For example the above endpoint could be declared like:

```
Future<Config<T>> config<T>(@Path('id') id,
  Object? Function(T value) toJson,
  T Function(Object? json) fromJson,
);
```

**Comment by TekExplorer** [comment]
> Additionally it seems like the newly generated code can't handle generic types.
> 
> E.g. endpoint declared like this:
> 
> ```
> Future<Config<T>> config<T>(@Path('id') id);
> ```
> 
> gets the following generated code, which is obviously not going to work (also common types like `List`, `Map` or `String` instead of `T` probably also not going to work here:
> 
> ```
> Config<T>.fromJson(
>       _result.data!,
>       (json) => T.fromJson(json as Map<String, dynamic>),
>     );
> ```
> 
> Generally it seems like the only way to address this is to declare the endpoint (optionally) with generic fromJson/toJson factories and have generator to wire them in the above call if they are specified.
> 
> For example the above endpoint could be declared like:
> 
> ```
> Future<Config<T>> config<T>(@Path('id') id,
>   Object? Function(T value) toJson,
>   T Function(Object? json) fromJson,
> );
> ```

That should be it's own issue. Supporting generic-generics is a completely different thing. related yes, but not the same.

The only thing my PR actually does is improve the already-there `genericArgumentFactories` detection. (by... actually looking at the signature)

**Comment by ekuleshov** [comment]
Quote your own statement:

> My guy, this is terrible.

Unlike before, your change now generates code that does NOT compile.

At very least you should have handled that and fall back to the old behavior.

Having tests and documentation would also help.

**Comment by TekExplorer** [comment]
Additionally, it does compile. At least as far as I can tell.

If my changes don't compile for you, then the previous would not have either.

**Comment by ekuleshov-idexx** [comment]
> If my changes don't compile for you, then the previous would not have either.

You know that how? No tests. Making changes without adding tests you fixed something and broken something else.

One would expect more than that from someone making comments like this:

<img width="871" alt="image" src="https://github.com/trevorwang/retrofit.dart/assets/77167568/183a0c3c-1648-4960-b532-d824852d17f7">

**Comment by ekuleshov** [comment]
> If my changes don't compile for you, then the previous would not have either.

You know that how? No tests. Making changes without adding tests you fixed something and broken something else.

One would expect more than that from someone making comments like this:

<img width="871" alt="image" src="https://github.com/trevorwang/retrofit.dart/assets/77167568/183a0c3c-1648-4960-b532-d824852d17f7">

**Comment by woprandi** [comment]
@ekuleshov I have same issue but even with version before @TekExplorer changes

**Comment by Raviteja11122** [comment]
Is there any work around for this

**Comment by TekExplorer** [comment]
> Is there any work around for this

For what? Use the latest version for the support I added.

**Comment by Raviteja11122** [comment]
> Is there any work around for this

asking about the #646 issue

**Comment by TekExplorer** [comment]
> > Is there any work around for this
> 
> asking for the #646 issue 

Ask there then, not here. This issue is already complete.

**Comment by Raviteja11122** [comment]
> > > Is there any work around for this
> > 
> > 
> > asking for the #646 issue
> 
> Ask there then, not here. This issue is already complete.

I added my comment there after some time, and that comment appeared here. Someone linked that issue here that caused my comment appeared here.
