### ISSUE TITLE
@Part(name: 'param') required File? param has compile error

### ISSUE THREAD

**Issue by dfdgsdfg** [trevorwang/retrofit.dart#666]
**Describe the bug**
In case multipart with required and nullable with File type, It generate compile error.
- `@Part(name: 'param') required File? param`
- Compile Error: Property 'path' cannot be accessed on 'File?' because it is potentially null.

Errors occur only with the File type.

```
// @Part(name: 'param') required File? param
// g.dart
_data.files.add(MapEntry(
  'param',
  MultipartFile.fromFileSync(
    portraitImage.path,    // Compile Error: Property 'path' cannot be accessed on 'File?' because it is potentially null.
    filename: param.path.split(Platform.pathSeparator).last,
  ),
));

// @Part(name: 'param') File? param
// g.dart
if (param != null) {
  _data.files.add(MapEntry(
    'param',
    MultipartFile.fromFileSync(
      portraitImage.path,
      filename: param.path.split(Platform.pathSeparator).last,
    ),
  ));
}
```

**Comment by irangareddy** [comment]
Hey there, is this issue fixed fully?

**Comment by mihir-kandoi** [comment]
I had this same issue a while back. Can you try changing your request to accept the `File` as an optional parameter instead?

**Comment by htetaunglin** [comment]
I have same issue.

**Comment by htetaunglin** [comment]
@dfdgsdfg 
This pull request [#720](https://github.com/trevorwang/retrofit.dart/pull/720) can help your issue, please update your retrofit generator version.
