### ISSUE TITLE
No MultiPart FormData support

### ISSUE THREAD

**Issue by gfranks** [trevorwang/retrofit.dart#7]
Any usage of a MultiPart aka Dio's `FormData` option, fails when supplying this as the `Body()` argument.

Here's an example block of the generated code:
```
Future<Response> uploadPhoto( int userId, FormData formData) async {
    final queryParameters = <String, dynamic>{};
    final data = <String, dynamic>{}; <------- my FormData should be set here
    data.addAll(formData ?? {}); <----- this is wrong
    return _dio.request<dynamic>('users/$userId/photos',
        queryParameters: queryParameters,
        options: RequestOptions(
            method: 'POST', headers: {'Content-Type': 'multipart/form-data'}),
        data: data); 
}
```

Consider adding an annotation for `FormData` that then sets the `data: <formdata>` value appropriately on the request or adjusting the `Body` annotation to take into account the argument class type.

Edit: I've created a PR for this change (https://github.com/trevorwang/retrofit.dart/pull/8)

**Comment by trevorwang** [comment]
@gfranks Sorry for the late respose. 

You should put an annotion to the Map which defined as a pamameter of `FormData.from`.
