### ISSUE TITLE
ParseErrorLogger isn't a type after update

### ISSUE THREAD

**Issue by ValeriusGC** [trevorwang/retrofit.dart#700]
Here is an errors 
<img width="907" alt="image" src="https://github.com/user-attachments/assets/9d3d2c77-cd44-40a9-b1f0-6ec6ef8dbfb3">

**pubspec.yaml**
  retrofit: ^4.2.0
  build_runner: ^2.4.12
  retrofit_generator: ^8.2.0

**pubspec.lock:**
<img width="384" alt="image" src="https://github.com/user-attachments/assets/1f638ca3-d78d-4639-a47c-7674fa9909c9">

`flutter doctor`
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.5 23F79 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] Connected device (4 available)
    ! Error: Browsing on the local area network for iPhone (Frostyland). Ensure the device is unlocked and attached with a cable or associated with
      the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

• No issues found!

```

**Comment by ValeriusGC** [comment]
Trouble was on my side!
1import 'package:retrofit/http.dart';`
instead
`import 'package:retrofit/retrofit.dart';`

**Comment by khaled-0** [comment]
Well, it doesn't work even with new import.
This is definitely a newly introduced bug/ undocumented change.
I'm rolling back to older version till this gets fixed

**Comment by Vera-Spoettl** [comment]
@khaled-0 might be a silly question, but how did you switch between branches?

**Comment by khaled-0** [comment]
> @khaled-0 might be a silly question, but how did you switch between branches to get this solved?
```
dependency_overrides:
  retrofit:
    git:
      url: https://github.com/trevorwang/retrofit.dart
      path: retrofit
```

The normal dependency has `^4.2.0`
Run `flutter pub get`
Observe pubspec.lock changes
Remove the dependency overrides and run pub get again
Boom, everything's fixed

**Comment by rddewan** [comment]
this seems to be a bug in the new version @khaled-0 thanks your step worked

**Comment by TJMusiitwa** [comment]
@trevorwang this is still an error that would be great to get solved without having to jump through the hoops and solutions mentioned above.
I am still on version 4.1.0 in my pubspecs and this issue came up even then.

**Comment by trevorwang** [comment]
@TJMusiitwa  @rddewan @khaled-0 

upgrade to retrofit 4.2.0 with generator 8.2.0, and use `import 'package:retrofit/retrofit.dart';` to import that class
