### ISSUE TITLE
add converter plugin to handle data converting

### ISSUE THREAD

**Issue by jiechic** [trevorwang/retrofit.dart#71]
对比了chopper，这个库还是过于简单，很多自定义的逻辑没有实现，不知道作者有没有计划做
Converter？比如参数Converter，还有body Converter
我们这边业务服务到需要自定义数据转换器来实现请求的通用化。

**Comment by trevorwang** [comment]
@jiechic   retrofit 目前封装了https://github.com/flutterchina/dio 的API，减少了一些重复性的工作。
 看一下 https://github.com/flutterchina/dio#Transformer 能不能满足你的需求

**Comment by jiechic** [comment]
看了眼Transformer，用法太复杂，而且是为了生成body的时候做的，而我需要的转换器是，比如queryParamer里面有个createTime，但是我给retrofit定义的是datetime类型，但是输出的时候是2019-10-16 17:23:00 这样的字符串。所以需要你这层的转换器，我在chopper有看到这方面的支持。

**Comment by trevorwang** [comment]
你是说类似这个？

https://github.com/dart-lang/json_serializable/blob/13547e6dee95572541a09ed77e495c06adcbbb08/example/lib/example.dart#L17

**Comment by jiechic** [comment]
不是这个，是我请求的query要用各种类型，并转换成相应的string提交到服务器
你这个是body里面的form，如果在body里面，我是可以用序列化来做了。
是这个里面的
https://github.com/square/retrofit/blob/master/retrofit/src/main/java/retrofit2/Converter.java
类似这个逻辑
/**
     * Returns a {@link Converter} for converting {@code type} to a {@link String}, or null if
     * {@code type} cannot be handled by this factory. This is used to create converters for types
     * specified by {@link Field @Field}, {@link FieldMap @FieldMap} values,
     * {@link Header @Header}, {@link HeaderMap @HeaderMap}, {@link Path @Path},
     * {@link Query @Query}, and {@link QueryMap @QueryMap} values.
     */
    public @Nullable Converter<?, String> stringConverter(Type type, Annotation[] annotations,
        Retrofit retrofit) {
      return null;
    }

**Comment by trevorwang** [comment]
Please refer [here](https://github.com/dart-lang/json_serializable/blob/6a628c922d025ace8e2c25358b6ccea2df5f6317/example/lib/json_converter_example.dart#L33
)

**Comment by jiechic** [comment]
![image](https://user-images.githubusercontent.com/518977/89157968-f8dd7200-d59f-11ea-8948-43364c4a4e98.png)
![image](https://user-images.githubusercontent.com/518977/89157987-03980700-d5a0-11ea-915e-1f341d3fdd3d.png)
在现版本生成的代码中，可否去掉生成tojson的代码逻辑，然后可以通过dio自身的拦截器来转换判断数据类型来做数据转换。

**Comment by jiechic** [comment]
#226 添加了一个PR，移除toJson的方法输出，直接把对象放到map中，后面可以通过dio拦截器去进行内容变换。
