### ISSUE TITLE
Flutter Retrofit: Error: 'ParseErrorLogger' isn't a type.

### ISSUE THREAD

**Issue by Abhisek-Dash-open** [trevorwang/retrofit.dart#715]
**Description**
After updating retrofit from version 4.1.0 to 4.4.1 and retrofit_generator from version 8.0.4 to 9.1.2 and running `dart run build_runner build --delete-conflicting-outputs` and generating files, in some of the generated files, I get the following error when running the app:

`../../packages/open_core/lib/service/repository/banking/pobo_cobo_repository/pobo_cobo_repository_data_source.g.dart:22:9: Error: Type 'ParseErrorLogger' not found.
  final ParseErrorLogger? errorLogger;

**To Reproduce**
1. Create new flutter project
1. Setup dio and retrofit for api calls with code generator. Use retrofit(v 4.4.1), dio(5.7.0) and retrofit_generator(9.1.2) and also build_runner (latest)
2. Run `flutter clean && flutter pub get`
3. Run `dart run build_runner build --delete-conflicting-outputs`
4. Try to run the app.

**Expected behavior**
App should run without above error : `Error: Type 'ParseErrorLogger' not found.`

**Smartphone:**
 - Device: Samsung SM M315F (Galaxy M31)
 - OS: Android Version 12
 - Version API Level 31

**Comment by farmery** [comment]
Hi @Abhisek-Dash-open verify that you have `package:retrofit/retrofit.dart` imported in your  `pobo_cobo_repository_data_source.dart` file

**Comment by Abhisek-Dash-open** [comment]
Hi @farmery , that fixed it I had imported `package:retrofit/dio.dart` instead of `package:retrofit/retrofit.dart`. Thanks for the help.
