### ISSUE TITLE
[retrofit_generator] Error: Property 'path' cannot be accessed on 'File?' because it is potentially null.

### ISSUE THREAD

**Issue by nebojsa-licina** [trevorwang/retrofit.dart#717]
**Describe the bug**
If we want to use an `@MultiPart()` API for sending Files where some of them are optional, retrofit generator ignores the fact that File can be null which leads to the compile error described in the title. 

**To Reproduce**

For example, declare an API call like this:
```dart
@MultiPart()
@POST("upload")
Future<String> uploadSelfExamRecordings(
    @Part(name: "user") String user,
    @Part(name: "firstFile", contentType: "text/plain") File? firstFile,
    @Part(name: "secondFile", contentType: "text/plain") File? secondFile);
``` 

Retrofit generator will generate `.g.dart` file that will look like this:
```dart
_data.files.add(MapEntry(
      'firstFile',
      MultipartFile.fromFileSync(
       firstFile.path,
        filename: firstFile.path.split(Platform.pathSeparator).last,
        contentType: MediaType.parse('text/plain'),
      ),
    ));
```

During compile, you will be able to see the above error since `firstFile` can be null.

**Expected behavior**
Introduce null check when adding MultipartFile to the list.
```dart
if (firstFile != null) { 
      _data.files.add(MapEntry(
          'firstFile',
          MultipartFile.fromFileSync(
           firstFile.path,
            filename: firstFile.path.split(Platform.pathSeparator).last,
            contentType: MediaType.parse('text/plain'),
          ),
        ));
}
```

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
Doesn't matter, this is compile issue.

**Smartphone (please complete the following information):**
Doesn't matter, this is compile issue.

**Additional context**
Retrofit generator version used is 9.1.3

The workaround for the issue is to mark nullable File objects as optional.

**Comment by htetaunglin** [comment]
@nebojsa-licina , I also facing this issue. So, I forked the repo and edit some code lines. Now, I request to merge this pull request https://github.com/trevorwang/retrofit.dart/pull/720. This request can help your issue.
