### ISSUE TITLE
Allow Nullable @Field()

### ISSUE THREAD

**Issue by iamriajul** [trevorwang/retrofit.dart#73]
In my case, I have this api: 
`submitComplaint(@Field() String bin, @Field() String taxpayer, @Field() File photo, @Field() String details)`
Here, the `photo` is not a required parameter.
Solutions can be:
1. add Annotation for Nullable.
2. add an optional parameter to @Field(), like @Field(nullable: true)

**Comment by iamriajul** [comment]
It can be achieved with something like this in retrofit generator.
dart support inline if statement in list, map.

![image](https://user-images.githubusercontent.com/24244379/67573813-0802da00-f75b-11e9-97a9-258b107aa78f.png)

**Comment by trevorwang** [comment]
Hi @iamriajul 

Please use the following way, mark the parameter as optional

```
submitComplaint(@Field() String bin, @Field() String taxpayer, @Field() File photo, [@Field() String details])
```

**Comment by iamriajul** [comment]
![image](https://user-images.githubusercontent.com/24244379/67686379-ce330d00-f9c0-11e9-9cc4-e6ea2fed3fc5.png)
![image](https://user-images.githubusercontent.com/24244379/67686410-db4ffc00-f9c0-11e9-82c3-75eb9ec1f3e2.png)

Please Add Null check on File @Field() for Optional Parameter.

**Comment by iamriajul** [comment]
Doing this fixes the issue
![image](https://user-images.githubusercontent.com/24244379/67686863-8b256980-f9c1-11e9-942d-d6101aec8da7.png)

**Comment by SBNTT** [comment]
Why this issue is closed ?
Using optional parameters does not solve it at all.
null values passed to optional `@Field` still send an empty string in the request

currently I must edit the generated file and add inline if statements to exclude null value from _data
