### ISSUE TITLE
Unhandled Exception: DioError [DioErrorType.DEFAULT]: type 'String' is not a subtype of type 'List<dynamic>'

### ISSUE THREAD

**Issue by poojadev** [trevorwang/retrofit.dart#76]
Hello, 
Thank you for the awesome library..
I'm unable to convert below JSON structure.
```
{
	"total": "14006",
	"page": 1,
	"pages": 701,
	"tv_shows": [{
		"id": 35624,
		"name": "The Flash",
		"permalink": "the-flash"
	}]
}

```
I'm getting  following exception :
E/flutter (23069): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: DioError ```
[DioErrorType.DEFAULT]: type 'String' is not a subtype of type 'List<dynamic>'
E/flutter (23069): #0      DioMixin.assureResponse (package:dio/src/dio.dart:1120:9)
E/flutter (23069): #1      DioMixin._request.<anonymous closure> (package:dio/src/dio.dart:883:14)
E/flutter (23069): #2      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (23069): #3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (23069): #4      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
E/flutter (23069): #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
E/flutter (23069): #6      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
E/flutter (23069): #7      Future._complete (dart:async/future_impl.dart:512:7)
E/flutter (23069): #8      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (23069): #9      Future.any.<anonymous closure> (dart:async/future.dart:459:45)
E/flutter (23069): #10     _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (23069): #11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (23069): #12     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
E/flutter (23069): #13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
E/flutter (23069): #14     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
E/flutter (23069): #15     Future._completeWithValue (dart:async/future_impl.dart:522:5)
E/flutter (23069): #16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
E/flutter (23069): #17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
E/flutter (23069): #18     DioMixin._dispatchRequest (package:dio/src/dio.dart)
E/flutter (23069): <asynchronous suspension>
E/flutter (23069): #19     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:828:37)
E/flutter (23069): #20     DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1099:22)
E/flutter (23069): #21     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:825:22)
E/flutter (23069): #22     new Future.<anonymous closure> (dart:async/future.dart:176:37)
E/flutter (23069): #23     _rootRun (dart:async/zone.dart:1120:38)
E/flutter (23069): #24     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (23069): #25     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (23069): #26     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (23069): #27     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (23069): #28     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (23069): #29     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
E/flutter (23069): #30     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
E/flutter (23069): #31     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
E/flutter (23069): #32     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
E/flutter (23069): #33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
E/flutter (23069): 
E/flutter (23069): #0      DioMixin._request.<anonymous closure> (package:dio/src/dio.dart:886:9)
E/flutter (23069): #1      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (23069): #2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (23069): #3      _FutureListener.handleError (dart:async/future_impl.dart:155:20)
E/flutter (23069): #4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:690:47)
E/flutter (23069): #5      Future._propagateToListeners (dart:async/future_impl.dart:711:24)
E/flutter (23069): #6      Future._complete (dart:async/future_impl.dart:512:7)
E/flutter (23069): #7      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (23069): #8      Future.any.<anonymous closure> (dart:async/future.dart:459:45)
E/flutter (23069): #9      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (23069): #10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (23069): #11     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
E/flutter (23069): #12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
E/flutter (23069): #13     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
E/flutter (23069): #14     Future._completeWithValue (dart:async/future_impl.dart:522:5)
E/flutter (23069): #15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
E/flutter (23069): #16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
E/flutter (23069): #17     DioMixin._dispatchRequest (package:dio/src/dio.dart)
E/flutter (23069): <asynchronous suspension>
E/flutter (23069): #18     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonym

```

**Comment by trevorwang** [comment]
Please provide your code here/

**Comment by poojadev** [comment]
Json structure 
{
	"total": "14006",
	"tv_shows": [{
		"name": "The Flash",
		"permalink": "the-flash"
	}]
`}`




Service class
```
import 'package:json_annotation/json_annotation.dart';
import 'package:retrofit/retrofit.dart';
import 'package:dio/dio.dart' hide Headers;
import 'dart:io';

part 'tvShows.g.dart';

@RestApi(baseUrl: "https://www.episodate.com/api/")
abstract class RestClient {
  factory RestClient(Dio dio) = _RestClient;

  @GET("/most-popular")
  Future<TvShows> getAllTvShows();

}

@JsonSerializable()
class TvShows {

  String total;

  List<TvShowList>tv_shows;
  TvShows({this.total,this.tv_shows});
  factory TvShows.fromJson(Map<String, dynamic> json) => _$TvShowsFromJson(json);
}
class TvShowList {
  int id;
  String name;
  String permalink;
  TvShowList(
      {this.name, this.permalink,});
  factory TvShowList.fromJson(Map<String, dynamic> parsedJson) {
    return TvShowList(
        name: parsedJson['name'],
        permalink: parsedJson['permalink'],
    );
  }
  Map<String, String> toJson() =>
  {
    'name':this.name,
    'permalink':this.permalink

  };

}

```
Generated class
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'tvShows.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

TvShows _$TvShowsFromJson(Map<String, dynamic> json) {
  return TvShows(
    total: json['total'] as String,
    tv_shows: (json['tv_shows'] as List)
        ?.map((e) =>
            e == null ? null : TvShowList.fromJson(e as Map<String, dynamic>))
        ?.toList(),
  );
}

Map<String, dynamic> _$TvShowsToJson(TvShows instance) => <String, dynamic>{
      'total': instance.total,
      'tv_shows': instance.tv_shows,
    };

// **************************************************************************
// RetrofitGenerator
// **************************************************************************

```
class _RestClient implements RestClient {
  _RestClient(this._dio) {
    ArgumentError.checkNotNull(_dio, '_dio');
  }

  final Dio _dio;

  final String baseUrl = 'https://www.episodate.com/api/';

  @override
  getAllTvShows() async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final Response<Map<String, dynamic>> _result = await _dio.request(
        '/most-popular',
        queryParameters: queryParameters,
        options: RequestOptions(
            method: 'GET',
            headers: <String, dynamic>{},
            extra: _extra,
            baseUrl: baseUrl),
        data: _data);
    final value = TvShows.fromJson(_result.data);
    return Future.value(value);
  }
}

```

**Comment by poojadev** [comment]
copied the same code just refereed by you 


```
import 'package:retrofit/retrofit.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:dio/dio.dart';

part  'DemoClient.g.dart';

//final data = {
//"total": "14006",
//"page": 1,
//"pages": 701,
//"tv_shows": [
//{"id": 35624, "name": "The Flash", "permalink": "the-flash"}
//]
//};

@RestApi(baseUrl: "https://www.episodate.com/api/")
abstract class DemoClient {
  factory DemoClient(Dio dio) = _DemoClient;

@GET('/most-popular')
Future<Result> getData();
}

@JsonSerializable()
class Result {
String total;
int page;
int pages;
List<Tv> tv_shows;

Result({this.total, this.page, this.pages, this.tv_shows});

factory Result.fromJson(Map<String, dynamic> json) => _$ResultFromJson(json);
Map<String, dynamic> toJson() => _$ResultToJson(this);
}

@JsonSerializable()
class Tv {
int id;
String name;
String permalink;

Tv({this.id, this.name, this.permalink});
factory Tv.fromJson(Map<String, dynamic> json) => _$TvFromJson(json);
Map<String, dynamic> toJson() => _$TvToJson(this);
}``
```

Generated file


// GENERATED CODE - DO NOT MODIFY BY HAND

```
part of 'DemoClient.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Result _$ResultFromJson(Map<String, dynamic> json) {
  return Result(
    total: json['total'] as String,
    page: json['page'] as int,
    pages: json['pages'] as int,
    tv_shows: (json['tv_shows'] as List)
        ?.map((e) => e == null ? null : Tv.fromJson(e as Map<String, dynamic>))
        ?.toList(),
  );
}

Map<String, dynamic> _$ResultToJson(Result instance) => <String, dynamic>{
      'total': instance.total,
      'page': instance.page,
      'pages': instance.pages,
      'tv_shows': instance.tv_shows,
    };

Tv _$TvFromJson(Map<String, dynamic> json) {
  return Tv(
    id: json['id'] as int,
    name: json['name'] as String,
    permalink: json['permalink'] as String,
  );
}

Map<String, dynamic> _$TvToJson(Tv instance) => <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'permalink': instance.permalink,
    };

// **************************************************************************
// RetrofitGenerator
// **************************************************************************

class _DemoClient implements DemoClient {
  _DemoClient(this._dio) {
    ArgumentError.checkNotNull(_dio, '_dio');
  }

  final Dio _dio;

  final String baseUrl = 'https://www.episodate.com/api/';

  @override
  getData() async {
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _data = <String, dynamic>{};
    final Response<Map<String, dynamic>> _result = await _dio.request(
        '/most-popular',
        queryParameters: queryParameters,
        options: RequestOptions(
            method: 'GET',
            headers: <String, dynamic>{},
            extra: _extra,
            baseUrl: baseUrl),
        data: _data);
    final value = Result.fromJson(_result.data);
    return Future.value(value);
  }
}
```

but getting exception 

```
E/flutter ( 2932): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: type 'String' is not a subtype of type 'Map<String, dynamic>'
E/flutter ( 2932): #0      DioMixin.assureResponse (package:dio/src/dio.dart:1120:9)
E/flutter ( 2932): #1      DioMixin._request.<anonymous closure> (package:dio/src/dio.dart:883:14)
E/flutter ( 2932): #2      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 2932): #3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 2932): #4      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
E/flutter ( 2932): #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
E/flutter ( 2932): #6      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
E/flutter ( 2932): #7      Future._complete (dart:async/future_impl.dart:512:7)
E/flutter ( 2932): #8      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter ( 2932): #9      Future.any.<anonymous closure> (dart:async/future.dart:459:45)
E/flutter ( 2932): #10     _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 2932): #11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 2932): #12     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
E/flutter ( 2932): #13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
E/flutter ( 2932): #14     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
E/flutter ( 2932): #15     Future._completeWithValue (dart:async/future_impl.dart:522:5)
E/flutter ( 2932): #16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
E/flutter ( 2932): #17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
E/flutter ( 2932): #18     DioMixin._dispatchRequest (package:dio/src/dio.dart)
E/flutter ( 2932): <asynchronous suspension>
E/flutter ( 2932): #19     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:828:37)
E/flutter ( 2932): #20     DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1099:22)
E/flutter ( 2932): #21     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:825:22)
E/flutter ( 2932): #22     new Future.<anonymous closure> (dart:async/future.dart:176:37)
E/flutter ( 2932): #23     _rootRun (dart:async/zone.dart:1120:38)
E/flutter ( 2932): #24     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 2932): #25     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 2932): #26     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter ( 2932): #27     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 2932): #28     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 2932): #29     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
E/flutter ( 2932): #30     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
E/flutter ( 2932): #31     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
E/flutter ( 2932): #32     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
E/flutter ( 2932): #33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
E/flutter ( 2932): 
E/flutter ( 2932): #0      DioMixin._request.<anonymous closure> (package:dio/src/dio.dart:886:9)
E/flutter ( 2932): #1      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 2932): #2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 2932): #3      _FutureListener.handleError (dart:async/future_impl.dart:155:20)
E/flutter ( 2932): #4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:690:47)
E/flutter ( 2932): #5      Future._propagateToListeners (dart:async/future_impl.dart:711:24)
E/flutter ( 2932): #6      Future._complete (dart:async/future_impl.dart:512:7)
E/flutter ( 2932): #7      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter ( 2932): #8      Future.any.<anonymous closure> (dart:async/future.dart:459:45)
E/flutter ( 2932): #9      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 2932): #10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 2932): #11     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
E/flutter ( 2932): #12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
E/flutter ( 2932): #13     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
E/flutter ( 2932): #14     Future._completeWithValue (dart:async/future_impl.dart:522:5)
E/flutter ( 2932): #15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
E/flutter ( 2932): #16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
E/flutter ( 2932): #17     DioMixin._dispatchRequest (package:dio/src/dio.dart)
E/flutter ( 2932): <asynchronous suspension>
E/flutter ( 2932): #18     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.

```

**Comment by poojadev** [comment]
I'm using 
```

retrofit: ^1.0.1
 dio: ^3.0.4
 retrofit_generator: ^1.0.2

```

**Comment by trevorwang** [comment]
https://www.episodate.com/api/most-popular  returns value with content type  text/html not json

**Comment by poojadev** [comment]
Yes you are right i checked with postman..the  returns value is not json ..but is there any way out ??
I just  tried with other API which includes nested Array and nested objects in that case  this  library is working like a charm :) 👍  
the only issue is with content type text/html..
Let me know if any solution is there for content type text/html
And Thanks for retrofit  👍

**Comment by trevorwang** [comment]
You can have a try with DioResponseType add json as the response type.

or you need to use transformer or a response interceptor

**Comment by bedel-lemotio** [comment]
@trevorwang please there are solution for content type text/html.????

**Comment by trevorwang** [comment]
Can you provide the scenario in which you have to use an HTML type?

**Comment by bedel-lemotio** [comment]
I just followed the history of your conversation actually I had the same problem the API returns a result with the contentype text / html; charset = UTF-8
is it possible to transform this answer in json with Dio if yes how?

**Comment by trevorwang** [comment]
Please use https://github.com/trevorwang/retrofit.dart/blob/79c07cb5580bb0d39f67373c837a900b25d1b54b/annotation/lib/dio.dart#L30
to mark your response using `json` content-type  forcefully.

**Comment by softronaut** [comment]
There is an elegant solution with latest major `Dio` release. Simply add these lines to your `Interceptor`'s `onResponse` parameter:
```dart
    onResponse: (res, handler) async {
      if (res.headers.map[Headers.contentTypeHeader]?.first.startsWith('text') == true) {
        res.data = jsonDecode(res.data as String);
        return handler.next(res);
      }
      return handler.next(res);
    }
```

**Comment by SelanDeemantha** [comment]
@softronaut Thank you very much. It's working perfectly for response type text/html.

**Comment by momoDragon** [comment]
> ```dart
>  onResponse: (res, handler) async {
>       if (res.headers.map[Headers.contentTypeHeader]?.first.startsWith('text') == true) {
>         res.data = jsonDecode(res.data as String);
>         return handler.next(res);
>       }
>       return handler.next(res);
>     }
> ```

Thanks very much this worked for me

**Comment by onats1** [comment]
Hello, please which interceptor was used here?
