### ISSUE TITLE
Do you have opinions on supporting the annotations server side?

### ISSUE THREAD

**Issue by TobiasBales** [trevorwang/retrofit.dart#82]
**Is your feature request related to a problem? Please describe.**
There are some frameworks (e.g. micronaut in the jvm space) that let you define an interface with a set of annotations that can be used on the client and on the server side. I was curious if you were interested in this?
I am not talking about turning retrofit into a server side framework but maybe extracting the annotations into it's own package (e.g. `GET` etc) and then have a second package that offers something similar to `RestAPI` that actually works on the server. I would be down to working on the server side but figured I'd check out your interest in cooperating on something like this.
This would have the nice benefit that if you have a backend and frontend app in dart you can use shared api declarations and use them on both sides.

Sorry for braking the issue template. And thank you for making retrofit, it really is a joy to use!

**Comment by trevorwang** [comment]
Hi @TobiasBales  

It sounds great.  But I don't have much time on this currently.

PR is really appreciated. 
I would suggest you add a `rest_server_genterator` package in this project and use annotation in http file.
Now the annotation package has some dio related classes.  We can move those classes out of package in future release.
