### ISSUE TITLE
Option to Cancel Request

### ISSUE THREAD

**Issue by choiruru** [trevorwang/retrofit.dart#85]
There is **search** feature in my project.
This feature do call request every I type a letter.
How to cancel previous requests..??

thanks.

**Comment by feronetick** [comment]
You can use dio's cancellation feature (https://github.com/flutterchina/dio#cancellation) with `@CancelRequest` annotation
```
  @override
  @GET("/cities/")
  Future getCities([@CancelRequest() CancelToken cancelToken]);
```
