### ISSUE TITLE
Generator doesn't work if file contains extension

### ISSUE THREAD

**Issue by ookami-kb** [trevorwang/retrofit.dart#86]
**Describe the bug**
Generator silently fails when file with `RestApi` class contains `extension` method. The generated file contains only class stub without any methods, e.g.:
```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'client.dart';

// **************************************************************************
// RetrofitGenerator
// **************************************************************************

class _RestClient implements RestClient {
  _RestClient(this._dio, {this.baseUrl}) {
    ArgumentError.checkNotNull(_dio, '_dio');
  }

  final Dio _dio;

  String baseUrl;
}
```

**To Reproduce**
1. Create file with `RestApi` class, e.g.:
```dart
import 'package:dio/dio.dart';
import 'package:retrofit/retrofit.dart';

part 'client.g.dart';

@RestApi()
abstract class RestClient {
  factory RestClient(Dio dio) = _RestClient;

  @POST('/api/general/v1/users/signIn')
  Future<Map<String, dynamic>> signIn();
}
```
2. Launch generator and ensure that proper implementation class was generated.
3. Add any extension method to the file, e.g.:
```dart
extension on Future {
  String test() => 'test';
}
```
4. Re-launch generator and ensure that only stub implementation was generated without any methods. No errors were found in generator output.

**Expected behavior**
Implementation class should be properly generated.

**Environment:**
 - OS: macOS 10.15.1
 - `flutter --version`:
```
Flutter 1.12.15-pre.29 • channel master • https://github.com/flutter/flutter.git
Framework • revision 84a1de5c74 (13 days ago) • 2019-11-27 07:40:51 -0500
Engine • revision fad1b23c42
Tools • Dart 2.7.0
```

**Comment by windrunner414** [comment]
I think extension cause the returnType.isDartAsyncFuture not true, file generator/lib/src/generator.dart, line 120

**Comment by trevorwang** [comment]
I have added the following code to my demo class. It works well. **(version:1.2.0)**

```
extension on Future {
  String test() => "hello";
}

```

Could you update to the latest version and try again?
