### ISSUE TITLE
Nested generic support

### ISSUE THREAD

**Issue by windrunner414** [trevorwang/retrofit.dart#87]
```
class Response<T extends Object> {
    T result;
    Response({this.result});
}
```
```
@GET("/")
Future<Response<OtherModel>> get();
```

we can support it by generating a code like:
```
Response.fromJson(json, OtherModel.fromJson);
```
and change the Response code to
```
class Response<T extends Object> {
    @JsonKey(ignore: true)
    T result;
    Response({this.result});
    factory Response.fromJson(Map<String, dynamic> json, T Function(Map<String, dynamic>) fromJson) {
        var response = _$ResponseFromJson(json);
        response.result = fromJson(json["result"]);
        return response;
    }
}
```

**Comment by windrunner414** [comment]
and can add an annotation `@CAST` to control `fromJson(json, fromJson)` or `fromJson(json)`

**Comment by windrunner414** [comment]
or @CAST(nestedCast: "result", nestedCastJsonName: "result")
and generate
```
Response ret = Response.fromJson(json);
ret.result = OtherModel.fromJson(json["result"]);
```

**Comment by trevorwang** [comment]
Would you mind submitting a pull request to implement what you mentioned above?

**Comment by windrunner414** [comment]
@trevorwang I implement it in another way so I closed this issue. I generate a generic json converter for JsonSerializable. so Response<User>.fromJson is ok

**Comment by xellDart** [comment]
Can you post an example, I have same problem @windrunner414

**Comment by trevorwang** [comment]
https://github.com/windrunner414/generic_json_converter_generator  @xellDart Hopefully it can give you some help.
