### ISSUE TITLE
Generic response type with bytes

### ISSUE THREAD

**Issue by riccardocalligaro** [trevorwang/retrofit.dart#89]
Hi, can you guys help me with this?

I have an endpoint where you can download a file but the file name and so the extension is given with the response headers, is there any way that I can have a 'generic response' so that and in addition to the content of the response I can get also the headers?

This is my code: 
```dart
  @GET("/students/{studentId}/didactics/item/{fileId}")
  @DioResponseType(ResponseType.bytes)
  Future<List<int>> getAttachmentFile(
      @Path() String studentId, @Path("fileId") int fileId);
```

In Kotlin you just needed to wrap the type in a generic Response like this

```kotlin
@GET("/students/{studentId}/didactics/item/{fileId}")
fun getAttachmentFile(x): Observable<Response<ResponseBody>>
````

Thanks 👍🏻

**Comment by trevorwang** [comment]
close this due to duplicated with #81
