### ISSUE TITLE
Is there anyway to use baseUrl dynamically?

### ISSUE THREAD

**Issue by Katekko** [trevorwang/retrofit.dart#93]
I want to call my service (retrofit class) passing a dynamic URL to fill my base URL. 
Is there anyway to do that?

**Comment by trevorwang** [comment]
Please refer to #80

**Comment by trevorwang** [comment]
Please leave the baseUrl as empty and then change value by dio.option.baseUrl

**Comment by trevorwang** [comment]
I close this issue. Feel free to open it if you still have a question here.
