### ISSUE TITLE
Use a child of the response to deserialize

### ISSUE THREAD

**Issue by chriswiesner** [trevorwang/retrofit.dart#95]
I'm doing a GET request to an endpoint. 

```
@GET("mylist")
Future<List<Task>> getTasks();

```

The response looks like this:
```
{
property1: sth
listItems: [...]
property2: sth
}
```

now i want to map the `listItems` to my list of task.

Is it possible to "select" a child of the response to be mapped in the end?

**Comment by trevorwang** [comment]
I could be. But I don't think it's a good idea to add this kind of feature to a HTTP library. 
The purpose of this library is to reduce the template code when dio_http is being used. I think this feature itself is not a common thing.
