### ISSUE TITLE
Use Either with then() and catchError()

### ISSUE THREAD

**Issue by don-prog** [trevorwang/retrofit.dart#97]
I want to use `Either` in this way:
```
Either<Failure, MyResponse> result = await restClient.request() // Future<MyResponse> request();
    .then((response) => Right(response))
    .catchError((failure) => Left(failure));
```
But it seems that I can't do this:

> error: A value of type 'Right< dynamic, MyResponse>' can't be assigned to
> a variable of type 'Either< Failure, MyResponse>'.

So, how can I catch an error or get a result in this way?

**Comment by trevorwang** [comment]
The erorr returns  as dynamic  So you must use Either<dynamic, MyResponse>  or cast the error type in your catchError function

**Comment by don-prog** [comment]
@trevorwang `Either<dynamic, MyResponse>` gives an exception:

> type 'Left<dynamic, dynamic>' is not a subtype of type 'FutureOr<Right<dynamic, MyResponse>>' .

And `.catchError((error) => Left(Failure()));` produces the same error as the first time:

> error: A value of type 'Right<dynamic, MyResponse>' can't be assigned to a variable of type 'Either<Failure, MyResponse>'.

**Comment by trevorwang** [comment]
```
  @POST('http://httpbin.org/post')
  Future<String> postFormData(String username, String password);


  Either<dynamic, String> res = await client
      .postFormData("aaaa", "bbbbb")
      .then((it) => Right(it))
      .catchError((it) => Left(it));

  print(res);
```

and herer's the response

```
Right({
  "args": {},
  "data": "{}",
  "files": {},
  "form": {},
  "headers": {
    "Accept-Encoding": "gzip",
    "Content-Length": "2",
    "Content-Type": "application/json",
    "Demo-Header": "demo header",
    "Host": "httpbin.org",
    "User-Agent": "Dart/2.7 (dart:io)"
  },
  "json": {},
  "origin": "119.237.167.90, 119.237.167.90",
  "url": "https://httpbin.org/post"
}
)
```

**Comment by don-prog** [comment]
@trevorwang thanks, but how can I use `MyCustomClass` instead of `dynamic` (`Either<MyCustomClass, String>`) in your example?

**Comment by don-prog** [comment]
@trevorwang so, can you help me with your example?

**Comment by trevorwang** [comment]
You must handle it manually in your ` .catchError((it) => Left(it));` method.
The error returns as a dynamic type, you have to cast it by your self

**Comment by don-prog** [comment]
@trevorwang  I understand it, the question was about how can I return not dynamic, but something other type. Please, reread [this comment](https://github.com/trevorwang/retrofit.dart/issues/97#issuecomment-577919492).

**Comment by trevorwang** [comment]
Is it clear now?

```
.catchError((it) { 
//// do your cast
var error = MyCustomClass(....)
return Left(error);
});
```

**Comment by don-prog** [comment]
@trevorwang thanks, but as I said, I already tried `.catchError((error) => Left(Failure()));`.
As I understand I can't use `Failure` in `Either` like this:
```
Either<Failure, MyResponse> result = await restClient.request() // Future<MyResponse> request();
    .then((response) => Right(response))
    .catchError((failure) => Left(Failure())); 
```
I necessarily need to use explicit type casting, like this:

```
Either<Failure, MyResponse> result = await restClient.request() // Future<MyResponse> request();
    .then((response) => Right(response))
    .catchError((failure) => Left(Failure())) as Either<Failure, MyResponse>; 
```

even if I already return `Left(Failure())` in the `catchError()`.
So, is explicit casting the most concise solution?

**Comment by trevorwang** [comment]
I think it's not an issue of this library but an issue how to use `either ` package.

Could you  provide the library which you are using?

**Comment by don-prog** [comment]
I found [solution here](https://github.com/spebbe/dartz/issues/34). Thanks anyway.
